// Code generated by ebm2go at https://github.com/on-keyday/rebrgen, DO NOT EDIT.
package frame

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("frame")*/
type FrameType uint8

const (
	FrameType_Stdin   FrameType = 0
	FrameType_Stdout  FrameType = 1
	FrameType_Stderr  FrameType = 2
	FrameType_Control FrameType = 3
)

func (e FrameType) String() string {
	switch e {
	case FrameType_Stdin:
		return "Stdin"
	case FrameType_Stdout:
		return "Stdout"
	case FrameType_Stderr:
		return "Stderr"
	case FrameType_Control:
		return "Control"
	default:
		return fmt.Sprintf("FrameType(%d)", e)
	}
}

type FrameHeader struct {
	Type FrameType
	Len  uint32
}

func (f *FrameHeader) Write(tmp61 io.Writer) error {
	tmp181 := [1]uint8{}
	tmp181[0] = uint8(f.Type)
	if _, err := tmp61.Write(tmp181[:1]); err != nil {
		return err
	}
	tmp180 := [4]uint8{}
	binary.BigEndian.PutUint32(tmp180[:], uint32(f.Len))
	if _, err := tmp61.Write(tmp180[:4]); err != nil {
		return err
	}
	return nil
}
func (s *FrameHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *FrameHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (f *FrameHeader) EncodeSlice(tmp61 []byte, tmp61Offset *int) error {
	tmp181 := []uint8{}
	if len(tmp61)-*tmp61Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"FrameHeader::Type\"")
	}
	tmp181 = tmp61[*tmp61Offset : *tmp61Offset+int(1)]
	tmp181[0] = uint8(f.Type)
	*tmp61Offset += int(1)
	tmp180 := []uint8{}
	if len(tmp61)-*tmp61Offset < int(4) {
		return errors.New("not enough space to reserve data for field \"FrameHeader::Len\"")
	}
	tmp180 = tmp61[*tmp61Offset : *tmp61Offset+int(4)]
	binary.BigEndian.PutUint32(tmp180[:], uint32(f.Len))
	*tmp61Offset += int(4)
	return nil
}
func (s *FrameHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *FrameHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (f *FrameHeader) Append(tmp61 []byte) ([]byte, error) {
	tmp181 := [1]uint8{}
	tmp181[0] = uint8(f.Type)
	tmp61 = append(tmp61, tmp181[:1]...)
	tmp180 := [4]uint8{}
	binary.BigEndian.PutUint32(tmp180[:], uint32(f.Len))
	tmp61 = append(tmp61, tmp180[:4]...)
	return tmp61, nil
}
func (s *FrameHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (f *FrameHeader) Read(tmp64 io.Reader) error {
	tmp187 := uint8(0)
	tmp184 := [1]uint8{}
	if _, err := io.ReadFull(tmp64, tmp184[0:0+1]); err != nil {
		return err
	}
	tmp187 = tmp184[0]
	f.Type = FrameType(tmp187)
	tmp183 := [4]uint8{}
	if _, err := io.ReadFull(tmp64, tmp183[0:0+4]); err != nil {
		return err
	}
	f.Len = binary.BigEndian.Uint32(tmp183[:])
	return nil
}
func (s *FrameHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *FrameHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (f *FrameHeader) DecodeSlice(tmp64 []byte, tmp64Offset *int) error {
	tmp187 := uint8(0)
	tmp184 := []uint8{}
	if len(tmp64)-*tmp64Offset < 1 {
		return errors.New("not enough data to read for field \"FrameHeader::Type\"")
	}
	tmp184 = tmp64[*tmp64Offset : *tmp64Offset+1]
	*tmp64Offset += int(1)
	tmp187 = tmp184[0]
	f.Type = FrameType(tmp187)
	tmp183 := []uint8{}
	if len(tmp64)-*tmp64Offset < 4 {
		return errors.New("not enough data to read for field \"FrameHeader::Len\"")
	}
	tmp183 = tmp64[*tmp64Offset : *tmp64Offset+4]
	*tmp64Offset += int(4)
	f.Len = binary.BigEndian.Uint32(tmp183[:])
	return nil
}
func (s *FrameHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *FrameHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type tmp229 struct {
	Control Control
}

func (v *tmp229) isVariant90() {}

type tmp220 struct {
	Data []uint8
}

func (v *tmp220) isVariant90() {}

type Variant90 interface {
	isVariant90()
}

type Frame struct {
	Header FrameHeader
	tmp165 Variant90
}

func (f *Frame) Control() *Control {
	if f.Header.Type == FrameType_Control {
		tmp222, ok := f.tmp165.(*tmp229)
		if !ok {
			return nil
		}
		_ = tmp222 // to prevent unused warnings
		return &tmp222.Control
	}
	return nil
}
func (f *Frame) SetControl(tmp199 Control) bool {
	if f.Header.Type == FrameType_Control {
		tmp222, ok := f.tmp165.(*tmp229)
		if !ok {
			tmp222 = &tmp229{}
			f.tmp165 = tmp222
		}
		_ = tmp222 // to prevent unused warnings
		tmp222.Control = tmp199
		return true
	}
	return false
}

func (f *Frame) Data() *[]uint8 {
	if f.Header.Type == FrameType_Control {
		return nil
	} else {
		tmp219, ok := f.tmp165.(*tmp220)
		if !ok {
			return nil
		}
		_ = tmp219 // to prevent unused warnings
		return &tmp219.Data
	}
	return nil
}
func (f *Frame) SetData(tmp196 []uint8) bool {
	if f.Header.Type == FrameType_Control {
		return false
	} else {
		tmp219, ok := f.tmp165.(*tmp220)
		if !ok {
			tmp219 = &tmp220{}
			f.tmp165 = tmp219
		}
		_ = tmp219 // to prevent unused warnings
		if len(tmp196) > int(4294967295) {
			return false
		}
		f.Header.Len = uint32(len(tmp196))
		tmp219.Data = tmp196
		return true
	}
	return false
}

func (f *Frame) Write(tmp91 io.Writer) error {
	tmp226 := f.Header.Write(tmp91)
	if tmp226 != nil {
		return tmp226
	}
	if f.Header.Type == FrameType_Control {
		tmp222, ok := f.tmp165.(*tmp229)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp222 // to prevent unused warnings
		tmp167 := &bytes.Buffer{}
		tmp213 := tmp222.Control.Write(tmp167)
		if tmp213 != nil {
			return tmp213
		}
		if tmp167.Len() != int(f.Header.Len) {
			return fmt.Errorf("subrange length mismatch: expected %d, got %d", int(f.Header.Len), tmp167.Len())
		}
		if _, err := tmp91.Write(tmp167.Bytes()); err != nil {
			return err
		}
	} else {
		tmp219, ok := f.tmp165.(*tmp220)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp219 // to prevent unused warnings
		if len(tmp219.Data) != int(f.Header.Len) {
			return fmt.Errorf("size mismatch when writing field \"Frame::tmp165::Data\": expected %d, got %d", int(f.Header.Len), len(tmp219.Data))
		}
		if _, err := tmp91.Write(tmp219.Data); err != nil {
			return err
		}
	}
	return nil
}
func (s *Frame) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Frame) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (f *Frame) EncodeSlice(tmp91 []byte, tmp91Offset *int) error {
	tmp226 := f.Header.EncodeSlice(tmp91, tmp91Offset)
	if tmp226 != nil {
		return tmp226
	}
	if f.Header.Type == FrameType_Control {
		tmp222, ok := f.tmp165.(*tmp229)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp222 // to prevent unused warnings
		if len(tmp91)-*tmp91Offset < int(f.Header.Len) {
			return errors.New("not enough space for subrange")
		}
		tmp167 := tmp91[*tmp91Offset : *tmp91Offset+int(f.Header.Len)]
		tmp167OffsetBase := 0
		tmp167Offset := &tmp167OffsetBase
		tmp213 := tmp222.Control.EncodeSlice(tmp167, tmp167Offset)
		if tmp213 != nil {
			return tmp213
		}
		if *tmp167Offset != int(f.Header.Len) {
			return fmt.Errorf("subrange length mismatch: expected %d, got %d", int(f.Header.Len), *tmp167Offset)
		}
		*tmp91Offset += int(f.Header.Len)
	} else {
		tmp219, ok := f.tmp165.(*tmp220)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp219 // to prevent unused warnings
		if len(tmp219.Data) != int(f.Header.Len) {
			return fmt.Errorf("size mismatch when writing field \"Frame::tmp165::Data\": expected %d, got %d", int(f.Header.Len), len(tmp219.Data))
		}
		if len(tmp91)-*tmp91Offset < int(0+f.Header.Len) {
			return errors.New("not enough space to write for field \"Frame::tmp165::Data\"")
		}
		copy(tmp91[*tmp91Offset:*tmp91Offset+int(f.Header.Len)], tmp219.Data)
		*tmp91Offset += int(f.Header.Len)
	}
	return nil
}
func (s *Frame) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Frame) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (f *Frame) Append(tmp91 []byte) ([]byte, error) {
	var tmp226 error
	tmp91, tmp226 = f.Header.Append(tmp91)

	if tmp226 != nil {
		return nil, tmp226
	}
	if f.Header.Type == FrameType_Control {
		tmp222, ok := f.tmp165.(*tmp229)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp222 // to prevent unused warnings
		tmp167 := tmp91
		var tmp213 error
		tmp167, tmp213 = tmp222.Control.Append(tmp167)

		if tmp213 != nil {
			return nil, tmp213
		}
		if len(tmp167)-len(tmp91) != int(f.Header.Len) {
			return nil, fmt.Errorf("subrange length mismatch: expected %d, got %d", int(f.Header.Len), len(tmp167)-len(tmp91))
		}
		tmp91 = tmp167
	} else {
		tmp219, ok := f.tmp165.(*tmp220)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp219 // to prevent unused warnings
		if len(tmp219.Data) != int(f.Header.Len) {
			return nil, fmt.Errorf("size mismatch when writing field \"Frame::tmp165::Data\": expected %d, got %d", int(f.Header.Len), len(tmp219.Data))
		}
		tmp91 = append(tmp91, tmp219.Data...)
	}
	return tmp91, nil
}
func (s *Frame) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (f *Frame) Read(tmp88 io.Reader) error {
	tmp209 := f.Header.Read(tmp88)
	if tmp209 != nil {
		return tmp209
	}
	if f.Header.Type == FrameType_Control {
		tmp222, ok := f.tmp165.(*tmp229)
		if !ok {
			tmp222 = &tmp229{}
			f.tmp165 = tmp222
		}
		_ = tmp222 // to prevent unused warnings
		tmp163 := io.LimitReader(tmp88, int64(f.Header.Len))
		tmp203 := tmp222.Control.Read(tmp163)
		if tmp203 != nil {
			return tmp203
		}
		if tmp163.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("subrange length mismatch: expected %d, but remains %d", int(f.Header.Len), tmp163.(*io.LimitedReader).N)
		}
	} else {
		tmp219, ok := f.tmp165.(*tmp220)
		if !ok {
			tmp219 = &tmp220{}
			f.tmp165 = tmp219
		}
		_ = tmp219 // to prevent unused warnings
		if seeker, ok := tmp88.(io.Seeker); ok {
			current, err := seeker.Seek(0, io.SeekCurrent)
			if err != nil {
				return err
			}
			endOffset, err := seeker.Seek(0, io.SeekEnd)
			if err != nil {
				return err
			}
			_, err = seeker.Seek(current, io.SeekStart)
			if err != nil {
				return err
			}
			if (endOffset - current) < int64(int(f.Header.Len)) {
				return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(f.Header.Len)))
			}
			tmp219.Data = make([]byte, int(f.Header.Len))
			if _, err := io.ReadFull(tmp88, tmp219.Data[0:0+int(f.Header.Len)]); err != nil {
				return err
			}
		} else {
			// To mitigate DoS attack, use incremental buffer allocation
			// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
			io_temp_383 := bytes.NewBuffer(nil)
			if _, err := io.CopyN(io_temp_383, tmp88, int64(int(f.Header.Len))); err != nil {
				return err
			}
			tmp219.Data = io_temp_383.Bytes()
		}
	}
	return nil
}
func (s *Frame) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Frame) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (f *Frame) DecodeSlice(tmp88 []byte, tmp88Offset *int) error {
	tmp209 := f.Header.DecodeSlice(tmp88, tmp88Offset)
	if tmp209 != nil {
		return tmp209
	}
	if f.Header.Type == FrameType_Control {
		tmp222, ok := f.tmp165.(*tmp229)
		if !ok {
			tmp222 = &tmp229{}
			f.tmp165 = tmp222
		}
		_ = tmp222 // to prevent unused warnings
		if len(tmp88)-*tmp88Offset < int(f.Header.Len) {
			return errors.New("not enough data for subrange")
		}
		tmp163 := tmp88[*tmp88Offset : *tmp88Offset+int(f.Header.Len)]
		tmp163OffsetBase := 0
		tmp163Offset := &tmp163OffsetBase
		*tmp88Offset += int(f.Header.Len)
		tmp203 := tmp222.Control.DecodeSlice(tmp163, tmp163Offset)
		if tmp203 != nil {
			return tmp203
		}
	} else {
		tmp219, ok := f.tmp165.(*tmp220)
		if !ok {
			tmp219 = &tmp220{}
			f.tmp165 = tmp219
		}
		_ = tmp219 // to prevent unused warnings
		if len(tmp88)-*tmp88Offset < int(f.Header.Len) {
			return errors.New("not enough data to read for field \"Frame::tmp165::Data\"")
		}
		tmp219.Data = tmp88[*tmp88Offset : *tmp88Offset+int(f.Header.Len)]
		*tmp88Offset += int(int(f.Header.Len))
	}
	return nil
}
func (s *Frame) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Frame) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type ControlType uint8

const (
	ControlType_TerminalWindowSize ControlType = 0
	ControlType_Signal             ControlType = 1
)

func (e ControlType) String() string {
	switch e {
	case ControlType_TerminalWindowSize:
		return "TerminalWindowSize"
	case ControlType_Signal:
		return "Signal"
	default:
		return fmt.Sprintf("ControlType(%d)", e)
	}
}

type tmp276 struct {
	TerminalWindowSize TerminalWindowSize
}

func (v *tmp276) isVariant70() {}

type tmp274 struct {
	Signal Signal
}

func (v *tmp274) isVariant70() {}

type tmp589 struct {
}

func (v *tmp589) isVariant70() {}

type Variant70 interface {
	isVariant70()
}

type Control struct {
	Type   ControlType
	tmp179 Variant70
}

func (c *Control) Signal() *Signal {
	if c.Type == ControlType_TerminalWindowSize {
		return nil
	} else if c.Type == ControlType_Signal {
		tmp273, ok := c.tmp179.(*tmp274)
		if !ok {
			return nil
		}
		_ = tmp273 // to prevent unused warnings
		return &tmp273.Signal
	}
	return nil
}
func (c *Control) SetSignal(tmp316 Signal) bool {
	if c.Type == ControlType_TerminalWindowSize {
		return false
	} else if c.Type == ControlType_Signal {
		tmp273, ok := c.tmp179.(*tmp274)
		if !ok {
			tmp273 = &tmp274{}
			c.tmp179 = tmp273
		}
		_ = tmp273 // to prevent unused warnings
		tmp273.Signal = tmp316
		return true
	}
	return false
}

func (c *Control) TerminalWindowSize() *TerminalWindowSize {
	if c.Type == ControlType_TerminalWindowSize {
		tmp275, ok := c.tmp179.(*tmp276)
		if !ok {
			return nil
		}
		_ = tmp275 // to prevent unused warnings
		return &tmp275.TerminalWindowSize
	}
	return nil
}
func (c *Control) SetTerminalWindowSize(tmp303 TerminalWindowSize) bool {
	if c.Type == ControlType_TerminalWindowSize {
		tmp275, ok := c.tmp179.(*tmp276)
		if !ok {
			tmp275 = &tmp276{}
			c.tmp179 = tmp275
		}
		_ = tmp275 // to prevent unused warnings
		tmp275.TerminalWindowSize = tmp303
		return true
	}
	return false
}

func (c *Control) Write(tmp50 io.Writer) error {
	tmp50ByteIO, _ := tmp50.(io.ByteWriter)
	_ = tmp50ByteIO
	if tmp50ByteIO != nil {
		if err := tmp50ByteIO.WriteByte(uint8(c.Type)); err != nil {
			return err
		}
	} else {
		if _, err := tmp50.Write([]byte{uint8(c.Type)}); err != nil {
			return err
		}
	}
	if c.Type == ControlType_TerminalWindowSize {
		tmp275, ok := c.tmp179.(*tmp276)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp275 // to prevent unused warnings
		tmp240 := tmp275.TerminalWindowSize.Write(tmp50)
		if tmp240 != nil {
			return tmp240
		}
	} else if c.Type == ControlType_Signal {
		tmp273, ok := c.tmp179.(*tmp274)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp273 // to prevent unused warnings
		tmp235 := tmp273.Signal.Write(tmp50)
		if tmp235 != nil {
			return tmp235
		}
	} else {
		tmp272, ok := c.tmp179.(*tmp589)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp272 // to prevent unused warnings
		return errors.New("Unexpected error")
	}
	return nil
}
func (s *Control) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Control) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *Control) EncodeSlice(tmp50 []byte, tmp50Offset *int) error {
	tmp246 := []uint8{}
	if len(tmp50)-*tmp50Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"Control::Type\"")
	}
	tmp246 = tmp50[*tmp50Offset : *tmp50Offset+int(1)]
	tmp246[0] = uint8(c.Type)
	*tmp50Offset += int(1)
	if c.Type == ControlType_TerminalWindowSize {
		tmp275, ok := c.tmp179.(*tmp276)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp275 // to prevent unused warnings
		tmp240 := tmp275.TerminalWindowSize.EncodeSlice(tmp50, tmp50Offset)
		if tmp240 != nil {
			return tmp240
		}
	} else if c.Type == ControlType_Signal {
		tmp273, ok := c.tmp179.(*tmp274)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp273 // to prevent unused warnings
		tmp235 := tmp273.Signal.EncodeSlice(tmp50, tmp50Offset)
		if tmp235 != nil {
			return tmp235
		}
	} else {
		tmp272, ok := c.tmp179.(*tmp589)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp272 // to prevent unused warnings
		return errors.New("Unexpected error")
	}
	return nil
}
func (s *Control) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Control) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *Control) Append(tmp50 []byte) ([]byte, error) {
	tmp246 := [1]uint8{}
	tmp246[0] = uint8(c.Type)
	tmp50 = append(tmp50, tmp246[:1]...)
	if c.Type == ControlType_TerminalWindowSize {
		tmp275, ok := c.tmp179.(*tmp276)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp275 // to prevent unused warnings
		var tmp240 error
		tmp50, tmp240 = tmp275.TerminalWindowSize.Append(tmp50)

		if tmp240 != nil {
			return nil, tmp240
		}
	} else if c.Type == ControlType_Signal {
		tmp273, ok := c.tmp179.(*tmp274)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp273 // to prevent unused warnings
		var tmp235 error
		tmp50, tmp235 = tmp273.Signal.Append(tmp50)

		if tmp235 != nil {
			return nil, tmp235
		}
	} else {
		tmp272, ok := c.tmp179.(*tmp589)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp272 // to prevent unused warnings
		return nil, errors.New("Unexpected error")
	}
	return tmp50, nil
}
func (s *Control) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (c *Control) Read(tmp51 io.Reader) error {
	tmp51ByteIO, _ := tmp51.(io.ByteReader)
	_ = tmp51ByteIO
	tmp267 := uint8(0)
	if tmp51ByteIO != nil {
		var err error
		tmp267, err = tmp51ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp51, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"Control::Type\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp267 = buf[0]
	}
	c.Type = ControlType(tmp267)
	if c.Type == ControlType_TerminalWindowSize {
		tmp275, ok := c.tmp179.(*tmp276)
		if !ok {
			tmp275 = &tmp276{}
			c.tmp179 = tmp275
		}
		_ = tmp275 // to prevent unused warnings
		tmp260 := tmp275.TerminalWindowSize.Read(tmp51)
		if tmp260 != nil {
			return tmp260
		}
	} else if c.Type == ControlType_Signal {
		tmp273, ok := c.tmp179.(*tmp274)
		if !ok {
			tmp273 = &tmp274{}
			c.tmp179 = tmp273
		}
		_ = tmp273 // to prevent unused warnings
		tmp254 := tmp273.Signal.Read(tmp51)
		if tmp254 != nil {
			return tmp254
		}
	} else {
		tmp272, ok := c.tmp179.(*tmp589)
		if !ok {
			tmp272 = &tmp589{}
			c.tmp179 = tmp272
		}
		_ = tmp272 // to prevent unused warnings
		return errors.New("Unexpected error")
	}
	return nil
}
func (s *Control) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Control) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (c *Control) DecodeSlice(tmp51 []byte, tmp51Offset *int) error {
	tmp267 := uint8(0)
	tmp266 := []uint8{}
	if len(tmp51)-*tmp51Offset < 1 {
		return errors.New("not enough data to read for field \"Control::Type\"")
	}
	tmp266 = tmp51[*tmp51Offset : *tmp51Offset+1]
	*tmp51Offset += int(1)
	tmp267 = tmp266[0]
	c.Type = ControlType(tmp267)
	if c.Type == ControlType_TerminalWindowSize {
		tmp275, ok := c.tmp179.(*tmp276)
		if !ok {
			tmp275 = &tmp276{}
			c.tmp179 = tmp275
		}
		_ = tmp275 // to prevent unused warnings
		tmp260 := tmp275.TerminalWindowSize.DecodeSlice(tmp51, tmp51Offset)
		if tmp260 != nil {
			return tmp260
		}
	} else if c.Type == ControlType_Signal {
		tmp273, ok := c.tmp179.(*tmp274)
		if !ok {
			tmp273 = &tmp274{}
			c.tmp179 = tmp273
		}
		_ = tmp273 // to prevent unused warnings
		tmp254 := tmp273.Signal.DecodeSlice(tmp51, tmp51Offset)
		if tmp254 != nil {
			return tmp254
		}
	} else {
		tmp272, ok := c.tmp179.(*tmp589)
		if !ok {
			tmp272 = &tmp589{}
			c.tmp179 = tmp272
		}
		_ = tmp272 // to prevent unused warnings
		return errors.New("Unexpected error")
	}
	return nil
}
func (s *Control) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Control) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type TerminalWindowSize struct {
	Columns uint16
	Rows    uint16
	Width   uint16
	Height  uint16
}

func (t *TerminalWindowSize) Write(tmp26 io.Writer) error {
	tmp93 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp93[:], uint16(t.Columns))
	if _, err := tmp26.Write(tmp93[:2]); err != nil {
		return err
	}
	tmp282 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp282[:], uint16(t.Rows))
	if _, err := tmp26.Write(tmp282[:2]); err != nil {
		return err
	}
	tmp280 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp280[:], uint16(t.Width))
	if _, err := tmp26.Write(tmp280[:2]); err != nil {
		return err
	}
	tmp278 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp278[:], uint16(t.Height))
	if _, err := tmp26.Write(tmp278[:2]); err != nil {
		return err
	}
	return nil
}
func (s *TerminalWindowSize) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *TerminalWindowSize) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *TerminalWindowSize) EncodeSlice(tmp26 []byte, tmp26Offset *int) error {
	tmp93 := []uint8{}
	if len(tmp26)-*tmp26Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"TerminalWindowSize::Columns\"")
	}
	tmp93 = tmp26[*tmp26Offset : *tmp26Offset+int(2)]
	binary.BigEndian.PutUint16(tmp93[:], uint16(t.Columns))
	*tmp26Offset += int(2)
	tmp282 := []uint8{}
	if len(tmp26)-*tmp26Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"TerminalWindowSize::Rows\"")
	}
	tmp282 = tmp26[*tmp26Offset : *tmp26Offset+int(2)]
	binary.BigEndian.PutUint16(tmp282[:], uint16(t.Rows))
	*tmp26Offset += int(2)
	tmp280 := []uint8{}
	if len(tmp26)-*tmp26Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"TerminalWindowSize::Width\"")
	}
	tmp280 = tmp26[*tmp26Offset : *tmp26Offset+int(2)]
	binary.BigEndian.PutUint16(tmp280[:], uint16(t.Width))
	*tmp26Offset += int(2)
	tmp278 := []uint8{}
	if len(tmp26)-*tmp26Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"TerminalWindowSize::Height\"")
	}
	tmp278 = tmp26[*tmp26Offset : *tmp26Offset+int(2)]
	binary.BigEndian.PutUint16(tmp278[:], uint16(t.Height))
	*tmp26Offset += int(2)
	return nil
}
func (s *TerminalWindowSize) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *TerminalWindowSize) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *TerminalWindowSize) Append(tmp26 []byte) ([]byte, error) {
	tmp93 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp93[:], uint16(t.Columns))
	tmp26 = append(tmp26, tmp93[:2]...)
	tmp282 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp282[:], uint16(t.Rows))
	tmp26 = append(tmp26, tmp282[:2]...)
	tmp280 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp280[:], uint16(t.Width))
	tmp26 = append(tmp26, tmp280[:2]...)
	tmp278 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp278[:], uint16(t.Height))
	tmp26 = append(tmp26, tmp278[:2]...)
	return tmp26, nil
}
func (s *TerminalWindowSize) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (t *TerminalWindowSize) Read(tmp27 io.Reader) error {
	tmp99 := [2]uint8{}
	if _, err := io.ReadFull(tmp27, tmp99[0:0+2]); err != nil {
		return err
	}
	t.Columns = binary.BigEndian.Uint16(tmp99[:])
	tmp287 := [2]uint8{}
	if _, err := io.ReadFull(tmp27, tmp287[0:0+2]); err != nil {
		return err
	}
	t.Rows = binary.BigEndian.Uint16(tmp287[:])
	tmp286 := [2]uint8{}
	if _, err := io.ReadFull(tmp27, tmp286[0:0+2]); err != nil {
		return err
	}
	t.Width = binary.BigEndian.Uint16(tmp286[:])
	tmp285 := [2]uint8{}
	if _, err := io.ReadFull(tmp27, tmp285[0:0+2]); err != nil {
		return err
	}
	t.Height = binary.BigEndian.Uint16(tmp285[:])
	return nil
}
func (s *TerminalWindowSize) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *TerminalWindowSize) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (t *TerminalWindowSize) DecodeSlice(tmp27 []byte, tmp27Offset *int) error {
	tmp99 := []uint8{}
	if len(tmp27)-*tmp27Offset < 2 {
		return errors.New("not enough data to read for field \"TerminalWindowSize::Columns\"")
	}
	tmp99 = tmp27[*tmp27Offset : *tmp27Offset+2]
	*tmp27Offset += int(2)
	t.Columns = binary.BigEndian.Uint16(tmp99[:])
	tmp287 := []uint8{}
	if len(tmp27)-*tmp27Offset < 2 {
		return errors.New("not enough data to read for field \"TerminalWindowSize::Rows\"")
	}
	tmp287 = tmp27[*tmp27Offset : *tmp27Offset+2]
	*tmp27Offset += int(2)
	t.Rows = binary.BigEndian.Uint16(tmp287[:])
	tmp286 := []uint8{}
	if len(tmp27)-*tmp27Offset < 2 {
		return errors.New("not enough data to read for field \"TerminalWindowSize::Width\"")
	}
	tmp286 = tmp27[*tmp27Offset : *tmp27Offset+2]
	*tmp27Offset += int(2)
	t.Width = binary.BigEndian.Uint16(tmp286[:])
	tmp285 := []uint8{}
	if len(tmp27)-*tmp27Offset < 2 {
		return errors.New("not enough data to read for field \"TerminalWindowSize::Height\"")
	}
	tmp285 = tmp27[*tmp27Offset : *tmp27Offset+2]
	*tmp27Offset += int(2)
	t.Height = binary.BigEndian.Uint16(tmp285[:])
	return nil
}
func (s *TerminalWindowSize) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *TerminalWindowSize) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Signal struct {
	Signal int32
}

func (s *Signal) Write(tmp185 io.Writer) error {
	tmp299 := [4]uint8{}
	binary.BigEndian.PutUint32(tmp299[:], uint32(uint32(s.Signal)))
	if _, err := tmp185.Write(tmp299[:4]); err != nil {
		return err
	}
	return nil
}
func (s *Signal) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Signal) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *Signal) EncodeSlice(tmp185 []byte, tmp185Offset *int) error {
	tmp299 := []uint8{}
	if len(tmp185)-*tmp185Offset < int(4) {
		return errors.New("not enough space to reserve data for field \"Signal::Signal\"")
	}
	tmp299 = tmp185[*tmp185Offset : *tmp185Offset+int(4)]
	binary.BigEndian.PutUint32(tmp299[:], uint32(uint32(s.Signal)))
	*tmp185Offset += int(4)
	return nil
}
func (s *Signal) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Signal) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *Signal) Append(tmp185 []byte) ([]byte, error) {
	tmp299 := [4]uint8{}
	binary.BigEndian.PutUint32(tmp299[:], uint32(uint32(s.Signal)))
	tmp185 = append(tmp185, tmp299[:4]...)
	return tmp185, nil
}
func (s *Signal) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *Signal) Read(tmp188 io.Reader) error {
	tmp288 := [4]uint8{}
	if _, err := io.ReadFull(tmp188, tmp288[0:0+4]); err != nil {
		return err
	}
	s.Signal = int32(binary.BigEndian.Uint32(tmp288[:]))
	return nil
}
func (s *Signal) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Signal) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *Signal) DecodeSlice(tmp188 []byte, tmp188Offset *int) error {
	tmp288 := []uint8{}
	if len(tmp188)-*tmp188Offset < 4 {
		return errors.New("not enough data to read for field \"Signal::Signal\"")
	}
	tmp288 = tmp188[*tmp188Offset : *tmp188Offset+4]
	*tmp188Offset += int(4)
	s.Signal = int32(binary.BigEndian.Uint32(tmp288[:]))
	return nil
}
func (s *Signal) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Signal) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
