// Code generated by ebm2go at https://github.com/on-keyday/brgen, DO NOT EDIT.
package frame

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("frame")*/
type FrameType uint8

const (
	FrameType_Stdin   FrameType = 0
	FrameType_Stdout  FrameType = 1
	FrameType_Stderr  FrameType = 2
	FrameType_Control FrameType = 3
	FrameType_Synth   FrameType = 4
)

func (e FrameType) String() string {
	switch e {
	case FrameType_Stdin:
		return "Stdin"
	case FrameType_Stdout:
		return "Stdout"
	case FrameType_Stderr:
		return "Stderr"
	case FrameType_Control:
		return "Control"
	case FrameType_Synth:
		return "Synth"
	default:
		return fmt.Sprintf("FrameType(%d)", e)
	}
}

type FrameHeader struct {
	Type FrameType
	Len  uint32
}

func (f *FrameHeader) Write(tmp49 io.Writer) error {
	tmp183 := [1]uint8{}
	tmp183[0] = uint8(f.Type)
	if _, err := tmp49.Write(tmp183[:1]); err != nil {
		return err
	}
	tmp182 := [4]uint8{}
	binary.BigEndian.PutUint32(tmp182[:], uint32(f.Len))
	if _, err := tmp49.Write(tmp182[:4]); err != nil {
		return err
	}
	return nil
}
func (s *FrameHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *FrameHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (f *FrameHeader) EncodeSlice(tmp49 []byte, tmp49Offset *int) error {
	tmp183 := []uint8{}
	if len(tmp49)-*tmp49Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"FrameHeader::Type\"")
	}
	tmp183 = tmp49[*tmp49Offset : *tmp49Offset+int(1)]
	tmp183[0] = uint8(f.Type)
	*tmp49Offset += int(1)
	tmp182 := []uint8{}
	if len(tmp49)-*tmp49Offset < int(4) {
		return errors.New("not enough space to reserve data for field \"FrameHeader::Len\"")
	}
	tmp182 = tmp49[*tmp49Offset : *tmp49Offset+int(4)]
	binary.BigEndian.PutUint32(tmp182[:], uint32(f.Len))
	*tmp49Offset += int(4)
	return nil
}
func (s *FrameHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *FrameHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (f *FrameHeader) Append(tmp49 []byte) ([]byte, error) {
	tmp183 := [1]uint8{}
	tmp183[0] = uint8(f.Type)
	tmp49 = append(tmp49, tmp183[:1]...)
	tmp182 := [4]uint8{}
	binary.BigEndian.PutUint32(tmp182[:], uint32(f.Len))
	tmp49 = append(tmp49, tmp182[:4]...)
	return tmp49, nil
}
func (s *FrameHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (f *FrameHeader) Read(tmp50 io.Reader) error {
	tmp188 := uint8(0)
	tmp187 := [1]uint8{}
	if _, err := io.ReadFull(tmp50, tmp187[0:0+1]); err != nil {
		return err
	}
	tmp188 = tmp187[0]
	f.Type = FrameType(tmp188)
	tmp185 := [4]uint8{}
	if _, err := io.ReadFull(tmp50, tmp185[0:0+4]); err != nil {
		return err
	}
	f.Len = binary.BigEndian.Uint32(tmp185[:])
	return nil
}
func (s *FrameHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *FrameHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (f *FrameHeader) DecodeSlice(tmp50 []byte, tmp50Offset *int) error {
	tmp188 := uint8(0)
	tmp187 := []uint8{}
	if len(tmp50)-*tmp50Offset < 1 {
		return errors.New("not enough data to read for field \"FrameHeader::Type\"")
	}
	tmp187 = tmp50[*tmp50Offset : *tmp50Offset+1]
	*tmp50Offset += int(1)
	tmp188 = tmp187[0]
	f.Type = FrameType(tmp188)
	tmp185 := []uint8{}
	if len(tmp50)-*tmp50Offset < 4 {
		return errors.New("not enough data to read for field \"FrameHeader::Len\"")
	}
	tmp185 = tmp50[*tmp50Offset : *tmp50Offset+4]
	*tmp50Offset += int(4)
	f.Len = binary.BigEndian.Uint32(tmp185[:])
	return nil
}
func (s *FrameHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *FrameHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type tmp230 struct {
	Control Control
}

func (v *tmp230) isVariant91() {}

type tmp221 struct {
	Data []uint8
}

func (v *tmp221) isVariant91() {}

type Variant91 interface {
	isVariant91()
}

type Frame struct {
	Header FrameHeader
	tmp167 Variant91
}

func (f *Frame) Control() *Control {
	if f.Header.Type == FrameType_Control {
		tmp223, ok := f.tmp167.(*tmp230)
		if !ok {
			return nil
		}
		_ = tmp223 // to prevent unused warnings
		return &tmp223.Control
	}
	return nil
}
func (f *Frame) SetControl(tmp199 Control) bool {
	if f.Header.Type == FrameType_Control {
		tmp223, ok := f.tmp167.(*tmp230)
		if !ok {
			tmp223 = &tmp230{}
			f.tmp167 = tmp223
		}
		_ = tmp223 // to prevent unused warnings
		tmp223.Control = tmp199
		return true
	}
	return false
}

func (f *Frame) Data() *[]uint8 {
	if f.Header.Type == FrameType_Control {
		return nil
	} else {
		tmp220, ok := f.tmp167.(*tmp221)
		if !ok {
			return nil
		}
		_ = tmp220 // to prevent unused warnings
		return &tmp220.Data
	}
	return nil
}
func (f *Frame) SetData(tmp196 []uint8) bool {
	if f.Header.Type == FrameType_Control {
		return false
	} else {
		tmp220, ok := f.tmp167.(*tmp221)
		if !ok {
			tmp220 = &tmp221{}
			f.tmp167 = tmp220
		}
		_ = tmp220 // to prevent unused warnings
		if len(tmp196) > int(4294967295) {
			return false
		}
		f.Header.Len = uint32(len(tmp196))
		tmp220.Data = tmp196
		return true
	}
	return false
}

func (f *Frame) Write(tmp92 io.Writer) error {
	tmp227 := f.Header.Write(tmp92)
	if tmp227 != nil {
		return tmp227
	}
	if f.Header.Type == FrameType_Control {
		tmp223, ok := f.tmp167.(*tmp230)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp223 // to prevent unused warnings
		tmp169 := &bytes.Buffer{}
		tmp213 := tmp223.Control.Write(tmp169)
		if tmp213 != nil {
			return tmp213
		}
		if tmp169.Len() != int(f.Header.Len) {
			return fmt.Errorf("subrange length mismatch: expected %d, got %d", int(f.Header.Len), tmp169.Len())
		}
		if _, err := tmp92.Write(tmp169.Bytes()); err != nil {
			return err
		}
	} else {
		tmp220, ok := f.tmp167.(*tmp221)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp220 // to prevent unused warnings
		if len(tmp220.Data) != int(int(f.Header.Len)) {
			return fmt.Errorf("size mismatch when writing field \"Frame::tmp167::Data\": expected %d, got %d", int(int(f.Header.Len)), len(tmp220.Data))
		}
		if _, err := tmp92.Write(tmp220.Data); err != nil {
			return err
		}
	}
	return nil
}
func (s *Frame) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Frame) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (f *Frame) EncodeSlice(tmp92 []byte, tmp92Offset *int) error {
	tmp227 := f.Header.EncodeSlice(tmp92, tmp92Offset)
	if tmp227 != nil {
		return tmp227
	}
	if f.Header.Type == FrameType_Control {
		tmp223, ok := f.tmp167.(*tmp230)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp223 // to prevent unused warnings
		if len(tmp92)-*tmp92Offset < int(f.Header.Len) {
			return errors.New("not enough space for subrange")
		}
		tmp169 := tmp92[*tmp92Offset : *tmp92Offset+int(f.Header.Len)]
		tmp169OffsetBase := 0
		tmp169Offset := &tmp169OffsetBase
		tmp213 := tmp223.Control.EncodeSlice(tmp169, tmp169Offset)
		if tmp213 != nil {
			return tmp213
		}
		if *tmp169Offset != int(f.Header.Len) {
			return fmt.Errorf("subrange length mismatch: expected %d, got %d", int(f.Header.Len), *tmp169Offset)
		}
		*tmp92Offset += int(f.Header.Len)
	} else {
		tmp220, ok := f.tmp167.(*tmp221)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp220 // to prevent unused warnings
		if len(tmp220.Data) != int(int(f.Header.Len)) {
			return fmt.Errorf("size mismatch when writing field \"Frame::tmp167::Data\": expected %d, got %d", int(int(f.Header.Len)), len(tmp220.Data))
		}
		if len(tmp92)-*tmp92Offset < int(0+int(f.Header.Len)) {
			return errors.New("not enough space to write for field \"Frame::tmp167::Data\"")
		}
		copy(tmp92[*tmp92Offset:*tmp92Offset+int(int(f.Header.Len))], tmp220.Data)
		*tmp92Offset += int(int(f.Header.Len))
	}
	return nil
}
func (s *Frame) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Frame) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (f *Frame) Append(tmp92 []byte) ([]byte, error) {
	var tmp227 error
	tmp92, tmp227 = f.Header.Append(tmp92)

	if tmp227 != nil {
		return nil, tmp227
	}
	if f.Header.Type == FrameType_Control {
		tmp223, ok := f.tmp167.(*tmp230)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp223 // to prevent unused warnings
		tmp169 := tmp92
		var tmp213 error
		tmp169, tmp213 = tmp223.Control.Append(tmp169)

		if tmp213 != nil {
			return nil, tmp213
		}
		if len(tmp169)-len(tmp92) != int(f.Header.Len) {
			return nil, fmt.Errorf("subrange length mismatch: expected %d, got %d", int(f.Header.Len), len(tmp169)-len(tmp92))
		}
		tmp92 = tmp169
	} else {
		tmp220, ok := f.tmp167.(*tmp221)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp220 // to prevent unused warnings
		if len(tmp220.Data) != int(int(f.Header.Len)) {
			return nil, fmt.Errorf("size mismatch when writing field \"Frame::tmp167::Data\": expected %d, got %d", int(int(f.Header.Len)), len(tmp220.Data))
		}
		tmp92 = append(tmp92, tmp220.Data...)
	}
	return tmp92, nil
}
func (s *Frame) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (f *Frame) Read(tmp89 io.Reader) error {
	tmp209 := f.Header.Read(tmp89)
	if tmp209 != nil {
		return tmp209
	}
	if f.Header.Type == FrameType_Control {
		tmp223, ok := f.tmp167.(*tmp230)
		if !ok {
			tmp223 = &tmp230{}
			f.tmp167 = tmp223
		}
		_ = tmp223 // to prevent unused warnings
		tmp164 := io.LimitReader(tmp89, int64(f.Header.Len))
		tmp203 := tmp223.Control.Read(tmp164)
		if tmp203 != nil {
			return tmp203
		}
		if tmp164.(*io.LimitedReader).N != 0 {
			return fmt.Errorf("subrange length mismatch: expected %d, but remains %d", int(f.Header.Len), tmp164.(*io.LimitedReader).N)
		}
	} else {
		tmp220, ok := f.tmp167.(*tmp221)
		if !ok {
			tmp220 = &tmp221{}
			f.tmp167 = tmp220
		}
		_ = tmp220 // to prevent unused warnings
		if seeker, ok := tmp89.(io.Seeker); ok {
			current, err := seeker.Seek(0, io.SeekCurrent)
			if err != nil {
				return err
			}
			endOffset, err := seeker.Seek(0, io.SeekEnd)
			if err != nil {
				return err
			}
			_, err = seeker.Seek(current, io.SeekStart)
			if err != nil {
				return err
			}
			if (endOffset - current) < int64(int(f.Header.Len)) {
				return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(f.Header.Len)))
			}
			tmp220.Data = make([]byte, int(f.Header.Len))
			if _, err := io.ReadFull(tmp89, tmp220.Data[0:0+int(f.Header.Len)]); err != nil {
				return err
			}
		} else {
			// To mitigate DoS attack, use incremental buffer allocation
			// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
			io_temp_392 := bytes.NewBuffer(nil)
			if _, err := io.CopyN(io_temp_392, tmp89, int64(int(f.Header.Len))); err != nil {
				return err
			}
			tmp220.Data = io_temp_392.Bytes()
		}
	}
	return nil
}
func (s *Frame) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Frame) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (f *Frame) DecodeSlice(tmp89 []byte, tmp89Offset *int) error {
	tmp209 := f.Header.DecodeSlice(tmp89, tmp89Offset)
	if tmp209 != nil {
		return tmp209
	}
	if f.Header.Type == FrameType_Control {
		tmp223, ok := f.tmp167.(*tmp230)
		if !ok {
			tmp223 = &tmp230{}
			f.tmp167 = tmp223
		}
		_ = tmp223 // to prevent unused warnings
		if len(tmp89)-*tmp89Offset < int(f.Header.Len) {
			return errors.New("not enough data for subrange")
		}
		tmp164 := tmp89[*tmp89Offset : *tmp89Offset+int(f.Header.Len)]
		tmp164OffsetBase := 0
		tmp164Offset := &tmp164OffsetBase
		*tmp89Offset += int(f.Header.Len)
		tmp203 := tmp223.Control.DecodeSlice(tmp164, tmp164Offset)
		if tmp203 != nil {
			return tmp203
		}
	} else {
		tmp220, ok := f.tmp167.(*tmp221)
		if !ok {
			tmp220 = &tmp221{}
			f.tmp167 = tmp220
		}
		_ = tmp220 // to prevent unused warnings
		if len(tmp89)-*tmp89Offset < int(f.Header.Len) {
			return errors.New("not enough data to read for field \"Frame::tmp167::Data\"")
		}
		tmp220.Data = tmp89[*tmp89Offset : *tmp89Offset+int(f.Header.Len)]
		*tmp89Offset += int(int(f.Header.Len))
	}
	return nil
}
func (s *Frame) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Frame) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type ControlType uint8

const (
	ControlType_TerminalWindowSize ControlType = 0
	ControlType_Signal             ControlType = 1
)

func (e ControlType) String() string {
	switch e {
	case ControlType_TerminalWindowSize:
		return "TerminalWindowSize"
	case ControlType_Signal:
		return "Signal"
	default:
		return fmt.Sprintf("ControlType(%d)", e)
	}
}

type tmp280 struct {
	TerminalWindowSize TerminalWindowSize
}

func (v *tmp280) isVariant75() {}

type tmp277 struct {
	Signal Signal
}

func (v *tmp277) isVariant75() {}

type tmp598 struct {
}

func (v *tmp598) isVariant75() {}

type Variant75 interface {
	isVariant75()
}

type Control struct {
	Type   ControlType
	tmp181 Variant75
}

func (c *Control) Signal() *Signal {
	if c.Type == ControlType_TerminalWindowSize {
		return nil
	} else if c.Type == ControlType_Signal {
		tmp276, ok := c.tmp181.(*tmp277)
		if !ok {
			return nil
		}
		_ = tmp276 // to prevent unused warnings
		return &tmp276.Signal
	}
	return nil
}
func (c *Control) SetSignal(tmp319 Signal) bool {
	if c.Type == ControlType_TerminalWindowSize {
		return false
	} else if c.Type == ControlType_Signal {
		tmp276, ok := c.tmp181.(*tmp277)
		if !ok {
			tmp276 = &tmp277{}
			c.tmp181 = tmp276
		}
		_ = tmp276 // to prevent unused warnings
		tmp276.Signal = tmp319
		return true
	}
	return false
}

func (c *Control) TerminalWindowSize() *TerminalWindowSize {
	if c.Type == ControlType_TerminalWindowSize {
		tmp325, ok := c.tmp181.(*tmp280)
		if !ok {
			return nil
		}
		_ = tmp325 // to prevent unused warnings
		return &tmp325.TerminalWindowSize
	}
	return nil
}
func (c *Control) SetTerminalWindowSize(tmp322 TerminalWindowSize) bool {
	if c.Type == ControlType_TerminalWindowSize {
		tmp325, ok := c.tmp181.(*tmp280)
		if !ok {
			tmp325 = &tmp280{}
			c.tmp181 = tmp325
		}
		_ = tmp325 // to prevent unused warnings
		tmp325.TerminalWindowSize = tmp322
		return true
	}
	return false
}

func (c *Control) Write(tmp37 io.Writer) error {
	tmp37ByteIO, _ := tmp37.(io.ByteWriter)
	_ = tmp37ByteIO
	if tmp37ByteIO != nil {
		if err := tmp37ByteIO.WriteByte(uint8(c.Type)); err != nil {
			return err
		}
	} else {
		if _, err := tmp37.Write([]byte{uint8(c.Type)}); err != nil {
			return err
		}
	}
	if c.Type == ControlType_TerminalWindowSize {
		tmp325, ok := c.tmp181.(*tmp280)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp325 // to prevent unused warnings
		tmp242 := tmp325.TerminalWindowSize.Write(tmp37)
		if tmp242 != nil {
			return tmp242
		}
	} else if c.Type == ControlType_Signal {
		tmp276, ok := c.tmp181.(*tmp277)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp276 // to prevent unused warnings
		tmp237 := tmp276.Signal.Write(tmp37)
		if tmp237 != nil {
			return tmp237
		}
	} else {
		tmp275, ok := c.tmp181.(*tmp598)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp275 // to prevent unused warnings
		return errors.New("Unexpected error")
	}
	return nil
}
func (s *Control) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Control) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *Control) EncodeSlice(tmp37 []byte, tmp37Offset *int) error {
	tmp248 := []uint8{}
	if len(tmp37)-*tmp37Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"Control::Type\"")
	}
	tmp248 = tmp37[*tmp37Offset : *tmp37Offset+int(1)]
	tmp248[0] = uint8(c.Type)
	*tmp37Offset += int(1)
	if c.Type == ControlType_TerminalWindowSize {
		tmp325, ok := c.tmp181.(*tmp280)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp325 // to prevent unused warnings
		tmp242 := tmp325.TerminalWindowSize.EncodeSlice(tmp37, tmp37Offset)
		if tmp242 != nil {
			return tmp242
		}
	} else if c.Type == ControlType_Signal {
		tmp276, ok := c.tmp181.(*tmp277)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp276 // to prevent unused warnings
		tmp237 := tmp276.Signal.EncodeSlice(tmp37, tmp37Offset)
		if tmp237 != nil {
			return tmp237
		}
	} else {
		tmp275, ok := c.tmp181.(*tmp598)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp275 // to prevent unused warnings
		return errors.New("Unexpected error")
	}
	return nil
}
func (s *Control) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Control) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *Control) Append(tmp37 []byte) ([]byte, error) {
	tmp248 := [1]uint8{}
	tmp248[0] = uint8(c.Type)
	tmp37 = append(tmp37, tmp248[:1]...)
	if c.Type == ControlType_TerminalWindowSize {
		tmp325, ok := c.tmp181.(*tmp280)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp325 // to prevent unused warnings
		var tmp242 error
		tmp37, tmp242 = tmp325.TerminalWindowSize.Append(tmp37)

		if tmp242 != nil {
			return nil, tmp242
		}
	} else if c.Type == ControlType_Signal {
		tmp276, ok := c.tmp181.(*tmp277)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp276 // to prevent unused warnings
		var tmp237 error
		tmp37, tmp237 = tmp276.Signal.Append(tmp37)

		if tmp237 != nil {
			return nil, tmp237
		}
	} else {
		tmp275, ok := c.tmp181.(*tmp598)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp275 // to prevent unused warnings
		return nil, errors.New("Unexpected error")
	}
	return tmp37, nil
}
func (s *Control) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (c *Control) Read(tmp40 io.Reader) error {
	tmp40ByteIO, _ := tmp40.(io.ByteReader)
	_ = tmp40ByteIO
	tmp270 := uint8(0)
	if tmp40ByteIO != nil {
		var err error
		tmp270, err = tmp40ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp40, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"Control::Type\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp270 = buf[0]
	}
	c.Type = ControlType(tmp270)
	if c.Type == ControlType_TerminalWindowSize {
		tmp325, ok := c.tmp181.(*tmp280)
		if !ok {
			tmp325 = &tmp280{}
			c.tmp181 = tmp325
		}
		_ = tmp325 // to prevent unused warnings
		tmp262 := tmp325.TerminalWindowSize.Read(tmp40)
		if tmp262 != nil {
			return tmp262
		}
	} else if c.Type == ControlType_Signal {
		tmp276, ok := c.tmp181.(*tmp277)
		if !ok {
			tmp276 = &tmp277{}
			c.tmp181 = tmp276
		}
		_ = tmp276 // to prevent unused warnings
		tmp256 := tmp276.Signal.Read(tmp40)
		if tmp256 != nil {
			return tmp256
		}
	} else {
		tmp275, ok := c.tmp181.(*tmp598)
		if !ok {
			tmp275 = &tmp598{}
			c.tmp181 = tmp275
		}
		_ = tmp275 // to prevent unused warnings
		return errors.New("Unexpected error")
	}
	return nil
}
func (s *Control) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Control) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (c *Control) DecodeSlice(tmp40 []byte, tmp40Offset *int) error {
	tmp270 := uint8(0)
	tmp269 := []uint8{}
	if len(tmp40)-*tmp40Offset < 1 {
		return errors.New("not enough data to read for field \"Control::Type\"")
	}
	tmp269 = tmp40[*tmp40Offset : *tmp40Offset+1]
	*tmp40Offset += int(1)
	tmp270 = tmp269[0]
	c.Type = ControlType(tmp270)
	if c.Type == ControlType_TerminalWindowSize {
		tmp325, ok := c.tmp181.(*tmp280)
		if !ok {
			tmp325 = &tmp280{}
			c.tmp181 = tmp325
		}
		_ = tmp325 // to prevent unused warnings
		tmp262 := tmp325.TerminalWindowSize.DecodeSlice(tmp40, tmp40Offset)
		if tmp262 != nil {
			return tmp262
		}
	} else if c.Type == ControlType_Signal {
		tmp276, ok := c.tmp181.(*tmp277)
		if !ok {
			tmp276 = &tmp277{}
			c.tmp181 = tmp276
		}
		_ = tmp276 // to prevent unused warnings
		tmp256 := tmp276.Signal.DecodeSlice(tmp40, tmp40Offset)
		if tmp256 != nil {
			return tmp256
		}
	} else {
		tmp275, ok := c.tmp181.(*tmp598)
		if !ok {
			tmp275 = &tmp598{}
			c.tmp181 = tmp275
		}
		_ = tmp275 // to prevent unused warnings
		return errors.New("Unexpected error")
	}
	return nil
}
func (s *Control) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Control) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type TerminalWindowSize struct {
	Columns uint16
	Rows    uint16
	Width   uint16
	Height  uint16
}

func (t *TerminalWindowSize) Write(tmp23 io.Writer) error {
	tmp97 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp97[:], uint16(t.Columns))
	if _, err := tmp23.Write(tmp97[:2]); err != nil {
		return err
	}
	tmp286 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp286[:], uint16(t.Rows))
	if _, err := tmp23.Write(tmp286[:2]); err != nil {
		return err
	}
	tmp284 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp284[:], uint16(t.Width))
	if _, err := tmp23.Write(tmp284[:2]); err != nil {
		return err
	}
	tmp282 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp282[:], uint16(t.Height))
	if _, err := tmp23.Write(tmp282[:2]); err != nil {
		return err
	}
	return nil
}
func (s *TerminalWindowSize) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *TerminalWindowSize) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *TerminalWindowSize) EncodeSlice(tmp23 []byte, tmp23Offset *int) error {
	tmp97 := []uint8{}
	if len(tmp23)-*tmp23Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"TerminalWindowSize::Columns\"")
	}
	tmp97 = tmp23[*tmp23Offset : *tmp23Offset+int(2)]
	binary.BigEndian.PutUint16(tmp97[:], uint16(t.Columns))
	*tmp23Offset += int(2)
	tmp286 := []uint8{}
	if len(tmp23)-*tmp23Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"TerminalWindowSize::Rows\"")
	}
	tmp286 = tmp23[*tmp23Offset : *tmp23Offset+int(2)]
	binary.BigEndian.PutUint16(tmp286[:], uint16(t.Rows))
	*tmp23Offset += int(2)
	tmp284 := []uint8{}
	if len(tmp23)-*tmp23Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"TerminalWindowSize::Width\"")
	}
	tmp284 = tmp23[*tmp23Offset : *tmp23Offset+int(2)]
	binary.BigEndian.PutUint16(tmp284[:], uint16(t.Width))
	*tmp23Offset += int(2)
	tmp282 := []uint8{}
	if len(tmp23)-*tmp23Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"TerminalWindowSize::Height\"")
	}
	tmp282 = tmp23[*tmp23Offset : *tmp23Offset+int(2)]
	binary.BigEndian.PutUint16(tmp282[:], uint16(t.Height))
	*tmp23Offset += int(2)
	return nil
}
func (s *TerminalWindowSize) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *TerminalWindowSize) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *TerminalWindowSize) Append(tmp23 []byte) ([]byte, error) {
	tmp97 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp97[:], uint16(t.Columns))
	tmp23 = append(tmp23, tmp97[:2]...)
	tmp286 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp286[:], uint16(t.Rows))
	tmp23 = append(tmp23, tmp286[:2]...)
	tmp284 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp284[:], uint16(t.Width))
	tmp23 = append(tmp23, tmp284[:2]...)
	tmp282 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp282[:], uint16(t.Height))
	tmp23 = append(tmp23, tmp282[:2]...)
	return tmp23, nil
}
func (s *TerminalWindowSize) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (t *TerminalWindowSize) Read(tmp24 io.Reader) error {
	tmp98 := [2]uint8{}
	if _, err := io.ReadFull(tmp24, tmp98[0:0+2]); err != nil {
		return err
	}
	t.Columns = binary.BigEndian.Uint16(tmp98[:])
	tmp294 := [2]uint8{}
	if _, err := io.ReadFull(tmp24, tmp294[0:0+2]); err != nil {
		return err
	}
	t.Rows = binary.BigEndian.Uint16(tmp294[:])
	tmp292 := [2]uint8{}
	if _, err := io.ReadFull(tmp24, tmp292[0:0+2]); err != nil {
		return err
	}
	t.Width = binary.BigEndian.Uint16(tmp292[:])
	tmp290 := [2]uint8{}
	if _, err := io.ReadFull(tmp24, tmp290[0:0+2]); err != nil {
		return err
	}
	t.Height = binary.BigEndian.Uint16(tmp290[:])
	return nil
}
func (s *TerminalWindowSize) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *TerminalWindowSize) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (t *TerminalWindowSize) DecodeSlice(tmp24 []byte, tmp24Offset *int) error {
	tmp98 := []uint8{}
	if len(tmp24)-*tmp24Offset < 2 {
		return errors.New("not enough data to read for field \"TerminalWindowSize::Columns\"")
	}
	tmp98 = tmp24[*tmp24Offset : *tmp24Offset+2]
	*tmp24Offset += int(2)
	t.Columns = binary.BigEndian.Uint16(tmp98[:])
	tmp294 := []uint8{}
	if len(tmp24)-*tmp24Offset < 2 {
		return errors.New("not enough data to read for field \"TerminalWindowSize::Rows\"")
	}
	tmp294 = tmp24[*tmp24Offset : *tmp24Offset+2]
	*tmp24Offset += int(2)
	t.Rows = binary.BigEndian.Uint16(tmp294[:])
	tmp292 := []uint8{}
	if len(tmp24)-*tmp24Offset < 2 {
		return errors.New("not enough data to read for field \"TerminalWindowSize::Width\"")
	}
	tmp292 = tmp24[*tmp24Offset : *tmp24Offset+2]
	*tmp24Offset += int(2)
	t.Width = binary.BigEndian.Uint16(tmp292[:])
	tmp290 := []uint8{}
	if len(tmp24)-*tmp24Offset < 2 {
		return errors.New("not enough data to read for field \"TerminalWindowSize::Height\"")
	}
	tmp290 = tmp24[*tmp24Offset : *tmp24Offset+2]
	*tmp24Offset += int(2)
	t.Height = binary.BigEndian.Uint16(tmp290[:])
	return nil
}
func (s *TerminalWindowSize) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *TerminalWindowSize) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Signal struct {
	Signal int32
}

func (s *Signal) Write(tmp122 io.Writer) error {
	tmp279 := [4]uint8{}
	binary.BigEndian.PutUint32(tmp279[:], uint32(uint32(s.Signal)))
	if _, err := tmp122.Write(tmp279[:4]); err != nil {
		return err
	}
	return nil
}
func (s *Signal) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Signal) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *Signal) EncodeSlice(tmp122 []byte, tmp122Offset *int) error {
	tmp279 := []uint8{}
	if len(tmp122)-*tmp122Offset < int(4) {
		return errors.New("not enough space to reserve data for field \"Signal::Signal\"")
	}
	tmp279 = tmp122[*tmp122Offset : *tmp122Offset+int(4)]
	binary.BigEndian.PutUint32(tmp279[:], uint32(uint32(s.Signal)))
	*tmp122Offset += int(4)
	return nil
}
func (s *Signal) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Signal) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *Signal) Append(tmp122 []byte) ([]byte, error) {
	tmp279 := [4]uint8{}
	binary.BigEndian.PutUint32(tmp279[:], uint32(uint32(s.Signal)))
	tmp122 = append(tmp122, tmp279[:4]...)
	return tmp122, nil
}
func (s *Signal) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *Signal) Read(tmp147 io.Reader) error {
	tmp301 := [4]uint8{}
	if _, err := io.ReadFull(tmp147, tmp301[0:0+4]); err != nil {
		return err
	}
	s.Signal = int32(binary.BigEndian.Uint32(tmp301[:]))
	return nil
}
func (s *Signal) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Signal) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *Signal) DecodeSlice(tmp147 []byte, tmp147Offset *int) error {
	tmp301 := []uint8{}
	if len(tmp147)-*tmp147Offset < 4 {
		return errors.New("not enough data to read for field \"Signal::Signal\"")
	}
	tmp301 = tmp147[*tmp147Offset : *tmp147Offset+4]
	*tmp147Offset += int(4)
	s.Signal = int32(binary.BigEndian.Uint32(tmp301[:]))
	return nil
}
func (s *Signal) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Signal) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
