// Code generated by ebm2go at https://github.com/on-keyday/brgen, DO NOT EDIT.
package wire

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("wire")*/
func (v *Varint) Prefix() uint8 {
	return uint8(((v.tmp257 >> uint64(62)) & uint64(3)))
}

func (v *Varint) SetPrefix(tmp859 uint8) bool {
	v.tmp257 = (v.tmp257 & (^(uint64(3) << uint64(62)))) | ((uint64(tmp859) & uint64(3)) << uint64(62))
	return true
}

func (v *Varint) tmp848() uint64 {
	return uint64(((v.tmp257 >> uint64(0)) & uint64(4611686018427387903)))
}

func (v *Varint) settmp440(tmp840 uint64) bool {
	v.tmp257 = (v.tmp257 & (^(uint64(4611686018427387903) << uint64(0)))) | ((uint64(tmp840) & uint64(4611686018427387903)) << uint64(0))
	return true
}

type Varint struct {
	tmp257 uint64
}

func (v *Varint) Value() uint64 {
	if v.Prefix() == uint8(0) {
		return uint64(uint8(v.tmp848()))
	} else if v.Prefix() == uint8(1) {
		return uint64(uint16(v.tmp848()))
	} else if v.Prefix() == 2 {
		return uint64(uint32(v.tmp848()))
	} else if v.Prefix() == 3 {
		return uint64(uint64(v.tmp848()))
	}
	return uint64(0)
}
func (v *Varint) SetValue(tmp736 uint64) bool {
	if v.Prefix() == uint8(0) {
		v.settmp440(uint64(uint8(tmp736)))
		return true
	} else if v.Prefix() == uint8(1) {
		v.settmp440(uint64(uint16(tmp736)))
		return true
	} else if v.Prefix() == 2 {
		v.settmp440(uint64(uint32(tmp736)))
		return true
	} else if v.Prefix() == 3 {
		v.settmp440(uint64(uint64(tmp736)))
		return true
	}
	return false
}

func (v *Varint) Write(tmp43 io.Writer) error {
	tmp754 := [8]uint8{}
	tmp754[0] = uint8((v.Prefix() & 3)) << uint8(6)
	if v.Prefix() == uint8(0) {
		tmp754[0] = tmp754[0] | uint8((uint8(v.tmp848()) & 63))
		if _, err := tmp43.Write(tmp754[:1]); err != nil {
			return err
		}
	} else if v.Prefix() == uint8(1) {
		tmp754[0] = tmp754[0] | uint8(((uint16(v.tmp848()) >> uint16(8)) & uint16(63)))
		tmp754[1] = uint8((uint16(v.tmp848()) & uint16(255)))
		if _, err := tmp43.Write(tmp754[:2]); err != nil {
			return err
		}
	} else if v.Prefix() == 2 {
		tmp754[0] = tmp754[0] | uint8(((uint32(v.tmp848()) >> uint32(24)) & uint32(63)))
		tmp754[1] = uint8(((uint32(v.tmp848()) >> uint32(16)) & uint32(255)))
		tmp754[2] = uint8(((uint32(v.tmp848()) >> uint32(8)) & uint32(255)))
		tmp754[3] = uint8((uint32(v.tmp848()) & uint32(255)))
		if _, err := tmp43.Write(tmp754[:4]); err != nil {
			return err
		}
	} else if v.Prefix() == 3 {
		tmp754[0] = tmp754[0] | uint8(((uint64(v.tmp848()) >> uint64(56)) & uint64(63)))
		tmp754[1] = uint8(((uint64(v.tmp848()) >> uint64(48)) & uint64(255)))
		tmp754[2] = uint8(((uint64(v.tmp848()) >> uint64(40)) & uint64(255)))
		tmp754[3] = uint8(((uint64(v.tmp848()) >> uint64(32)) & uint64(255)))
		tmp754[4] = uint8(((uint64(v.tmp848()) >> uint64(24)) & uint64(255)))
		tmp754[5] = uint8(((uint64(v.tmp848()) >> uint64(16)) & uint64(255)))
		tmp754[6] = uint8(((uint64(v.tmp848()) >> uint64(8)) & uint64(255)))
		tmp754[7] = uint8((uint64(v.tmp848()) & uint64(255)))
		if _, err := tmp43.Write(tmp754[:8]); err != nil {
			return err
		}
	}
	return nil
}
func (s *Varint) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Varint) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (v *Varint) EncodeSlice(tmp43 []byte, tmp43Offset *int) error {
	tmp754 := []uint8{}
	if len(tmp43)-*tmp43Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"Varint::tmp447::Value\"")
	}
	tmp754 = tmp43[*tmp43Offset : *tmp43Offset+int(1)]
	tmp754[0] = uint8((v.Prefix() & 3)) << uint8(6)
	if v.Prefix() == uint8(0) {
		if len(tmp43)-*tmp43Offset < int(1) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp447::Value\"")
		}
		tmp754 = tmp43[*tmp43Offset : *tmp43Offset+int(1)]
		tmp754[0] = tmp754[0] | uint8((uint8(v.tmp848()) & 63))
		*tmp43Offset += int(1)
	} else if v.Prefix() == uint8(1) {
		if len(tmp43)-*tmp43Offset < int(2) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp447::Value\"")
		}
		tmp754 = tmp43[*tmp43Offset : *tmp43Offset+int(2)]
		tmp754[0] = tmp754[0] | uint8(((uint16(v.tmp848()) >> uint16(8)) & uint16(63)))
		tmp754[1] = uint8((uint16(v.tmp848()) & uint16(255)))
		*tmp43Offset += int(2)
	} else if v.Prefix() == 2 {
		if len(tmp43)-*tmp43Offset < int(4) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp447::Value\"")
		}
		tmp754 = tmp43[*tmp43Offset : *tmp43Offset+int(4)]
		tmp754[0] = tmp754[0] | uint8(((uint32(v.tmp848()) >> uint32(24)) & uint32(63)))
		tmp754[1] = uint8(((uint32(v.tmp848()) >> uint32(16)) & uint32(255)))
		tmp754[2] = uint8(((uint32(v.tmp848()) >> uint32(8)) & uint32(255)))
		tmp754[3] = uint8((uint32(v.tmp848()) & uint32(255)))
		*tmp43Offset += int(4)
	} else if v.Prefix() == 3 {
		if len(tmp43)-*tmp43Offset < int(8) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp447::Value\"")
		}
		tmp754 = tmp43[*tmp43Offset : *tmp43Offset+int(8)]
		tmp754[0] = tmp754[0] | uint8(((uint64(v.tmp848()) >> uint64(56)) & uint64(63)))
		tmp754[1] = uint8(((uint64(v.tmp848()) >> uint64(48)) & uint64(255)))
		tmp754[2] = uint8(((uint64(v.tmp848()) >> uint64(40)) & uint64(255)))
		tmp754[3] = uint8(((uint64(v.tmp848()) >> uint64(32)) & uint64(255)))
		tmp754[4] = uint8(((uint64(v.tmp848()) >> uint64(24)) & uint64(255)))
		tmp754[5] = uint8(((uint64(v.tmp848()) >> uint64(16)) & uint64(255)))
		tmp754[6] = uint8(((uint64(v.tmp848()) >> uint64(8)) & uint64(255)))
		tmp754[7] = uint8((uint64(v.tmp848()) & uint64(255)))
		*tmp43Offset += int(8)
	}
	return nil
}
func (s *Varint) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Varint) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (v *Varint) Append(tmp43 []byte) ([]byte, error) {
	tmp754 := [8]uint8{}
	tmp754[0] = uint8((v.Prefix() & 3)) << uint8(6)
	if v.Prefix() == uint8(0) {
		tmp754[0] = tmp754[0] | uint8((uint8(v.tmp848()) & 63))
		tmp43 = append(tmp43, tmp754[:1]...)
	} else if v.Prefix() == uint8(1) {
		tmp754[0] = tmp754[0] | uint8(((uint16(v.tmp848()) >> uint16(8)) & uint16(63)))
		tmp754[1] = uint8((uint16(v.tmp848()) & uint16(255)))
		tmp43 = append(tmp43, tmp754[:2]...)
	} else if v.Prefix() == 2 {
		tmp754[0] = tmp754[0] | uint8(((uint32(v.tmp848()) >> uint32(24)) & uint32(63)))
		tmp754[1] = uint8(((uint32(v.tmp848()) >> uint32(16)) & uint32(255)))
		tmp754[2] = uint8(((uint32(v.tmp848()) >> uint32(8)) & uint32(255)))
		tmp754[3] = uint8((uint32(v.tmp848()) & uint32(255)))
		tmp43 = append(tmp43, tmp754[:4]...)
	} else if v.Prefix() == 3 {
		tmp754[0] = tmp754[0] | uint8(((uint64(v.tmp848()) >> uint64(56)) & uint64(63)))
		tmp754[1] = uint8(((uint64(v.tmp848()) >> uint64(48)) & uint64(255)))
		tmp754[2] = uint8(((uint64(v.tmp848()) >> uint64(40)) & uint64(255)))
		tmp754[3] = uint8(((uint64(v.tmp848()) >> uint64(32)) & uint64(255)))
		tmp754[4] = uint8(((uint64(v.tmp848()) >> uint64(24)) & uint64(255)))
		tmp754[5] = uint8(((uint64(v.tmp848()) >> uint64(16)) & uint64(255)))
		tmp754[6] = uint8(((uint64(v.tmp848()) >> uint64(8)) & uint64(255)))
		tmp754[7] = uint8((uint64(v.tmp848()) & uint64(255)))
		tmp43 = append(tmp43, tmp754[:8]...)
	}
	return tmp43, nil
}
func (s *Varint) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (v *Varint) Read(tmp13 io.Reader) error {
	tmp850 := [8]uint8{}
	tmp844 := uint8(0)
	if _, err := io.ReadFull(tmp13, tmp850[0:0+1]); err != nil {
		return err
	}
	tmp844 = uint8(((tmp850[0] & 192) >> uint8(6)))
	v.SetPrefix(tmp844)
	if v.Prefix() == uint8(0) {
		tmp834 := uint8(0)
		tmp834 = uint8((tmp850[0] & uint8(63)))
		v.settmp440(uint64(tmp834))
	} else if v.Prefix() == uint8(1) {
		tmp830 := uint16(0)
		if _, err := io.ReadFull(tmp13, tmp850[1:1+1]); err != nil {
			return err
		}
		tmp830 = (uint16((tmp850[0] & uint8(63))) << uint16(8)) | uint16(tmp850[1])
		v.settmp440(uint64(tmp830))
	} else if v.Prefix() == 2 {
		tmp809 := uint32(0)
		if _, err := io.ReadFull(tmp13, tmp850[1:1+3]); err != nil {
			return err
		}
		tmp809 = (((uint32((tmp850[0] & uint8(63))) << uint32(24)) | (uint32(tmp850[1]) << uint32(16))) | (uint32(tmp850[2]) << uint32(8))) | uint32(tmp850[3])
		v.settmp440(uint64(tmp809))
	} else if v.Prefix() == 3 {
		tmp768 := uint64(0)
		if _, err := io.ReadFull(tmp13, tmp850[1:1+7]); err != nil {
			return err
		}
		tmp768 = (((((((uint64((tmp850[0] & uint8(63))) << uint64(56)) | (uint64(tmp850[1]) << uint64(48))) | (uint64(tmp850[2]) << uint64(40))) | (uint64(tmp850[3]) << uint64(32))) | (uint64(tmp850[4]) << uint64(24))) | (uint64(tmp850[5]) << uint64(16))) | (uint64(tmp850[6]) << uint64(8))) | uint64(tmp850[7])
		v.settmp440(uint64(tmp768))
	}
	return nil
}
func (s *Varint) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Varint) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (v *Varint) DecodeSlice(tmp13 []byte, tmp13Offset *int) error {
	tmp850 := []uint8{}
	tmp844 := uint8(0)
	if len(tmp13)-*tmp13Offset < 1 {
		return errors.New("not enough data to read for field \"Varint::Prefix\"")
	}
	tmp850 = tmp13[*tmp13Offset : *tmp13Offset+1]
	*tmp13Offset += int(1)
	tmp844 = uint8(((tmp850[0] & 192) >> uint8(6)))
	v.SetPrefix(tmp844)
	if v.Prefix() == uint8(0) {
		tmp834 := uint8(0)
		tmp834 = uint8((tmp850[0] & uint8(63)))
		v.settmp440(uint64(tmp834))
	} else if v.Prefix() == uint8(1) {
		tmp830 := uint16(0)
		if len(tmp13)-*tmp13Offset < 1 {
			return errors.New("not enough data to read for field \"Varint::tmp447::Value\"")
		}
		tmp850 = tmp850[:1+1]
		*tmp13Offset += int(1)
		tmp830 = (uint16((tmp850[0] & uint8(63))) << uint16(8)) | uint16(tmp850[1])
		v.settmp440(uint64(tmp830))
	} else if v.Prefix() == 2 {
		tmp809 := uint32(0)
		if len(tmp13)-*tmp13Offset < 3 {
			return errors.New("not enough data to read for field \"Varint::tmp447::Value\"")
		}
		tmp850 = tmp850[:1+3]
		*tmp13Offset += int(3)
		tmp809 = (((uint32((tmp850[0] & uint8(63))) << uint32(24)) | (uint32(tmp850[1]) << uint32(16))) | (uint32(tmp850[2]) << uint32(8))) | uint32(tmp850[3])
		v.settmp440(uint64(tmp809))
	} else if v.Prefix() == 3 {
		tmp768 := uint64(0)
		if len(tmp13)-*tmp13Offset < 7 {
			return errors.New("not enough data to read for field \"Varint::tmp447::Value\"")
		}
		tmp850 = tmp850[:1+7]
		*tmp13Offset += int(7)
		tmp768 = (((((((uint64((tmp850[0] & uint8(63))) << uint64(56)) | (uint64(tmp850[1]) << uint64(48))) | (uint64(tmp850[2]) << uint64(40))) | (uint64(tmp850[3]) << uint64(32))) | (uint64(tmp850[4]) << uint64(24))) | (uint64(tmp850[5]) << uint64(16))) | (uint64(tmp850[6]) << uint64(8))) | uint64(tmp850[7])
		v.settmp440(uint64(tmp768))
	}
	return nil
}
func (s *Varint) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Varint) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func VarintLen(Value uint64) uint8 {
	tmp99 := uint8(0)
	if (uint64(0) <= Value) && (Value <= 63) {
		tmp99 = 1
	} else if (uint64(64) <= Value) && (Value <= 16383) {
		tmp99 = 2
	} else if (uint64(16384) <= Value) && (Value <= 1073741823) {
		tmp99 = 4
	} else if (1073741824 <= Value) && (Value <= 4611686018427387903) {
		tmp99 = 8
	} else {
		tmp99 = 0
	}
	return tmp99
}
func VarintPrefix(Value uint64) uint8 {
	Len := VarintLen(Value)
	tmp206 := uint8(0)
	if Len == uint8(1) {
		tmp206 = 0
	} else if Len == uint8(2) {
		tmp206 = 1
	} else if Len == uint8(4) {
		tmp206 = 2
	} else if Len == uint8(8) {
		tmp206 = 3
	} else {
		tmp206 = 255
	}
	return tmp206
}
func (v *StreamPacket) HasId() bool {
	intVal := v.hasId()
	return intVal != 0
}
func (s *StreamPacket) hasId() uint8 {
	return uint8(((s.tmp53 >> uint8(7)) & uint8(1)))
}

func (s *StreamPacket) SetHasId(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setHasId(intVal)
}
func (s *StreamPacket) setHasId(tmp669 uint8) bool {
	s.tmp53 = (s.tmp53 & (^(uint8(1) << uint8(7)))) | ((uint8(tmp669) & uint8(1)) << uint8(7))
	return true
}

func (s *StreamPacket) HasOffset() bool {
	intVal := s.hasOffset()
	return intVal != 0
}
func (s *StreamPacket) hasOffset() uint8 {
	return uint8(((s.tmp53 >> uint8(6)) & uint8(1)))
}

func (s *StreamPacket) SetHasOffset(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setHasOffset(intVal)
}
func (s *StreamPacket) setHasOffset(tmp663 uint8) bool {
	s.tmp53 = (s.tmp53 & (^(uint8(1) << uint8(6)))) | ((uint8(tmp663) & uint8(1)) << uint8(6))
	return true
}

func (s *StreamPacket) IsEof() bool {
	intVal := s.isEof()
	return intVal != 0
}
func (s *StreamPacket) isEof() uint8 {
	return uint8(((s.tmp53 >> uint8(5)) & uint8(1)))
}

func (s *StreamPacket) SetIsEof(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setIsEof(intVal)
}
func (s *StreamPacket) setIsEof(tmp659 uint8) bool {
	s.tmp53 = (s.tmp53 & (^(uint8(1) << uint8(5)))) | ((uint8(tmp659) & uint8(1)) << uint8(5))
	return true
}

func (s *StreamPacket) IsProbe() bool {
	intVal := s.isProbe()
	return intVal != 0
}
func (s *StreamPacket) isProbe() uint8 {
	return uint8(((s.tmp53 >> uint8(4)) & uint8(1)))
}

func (s *StreamPacket) SetIsProbe(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setIsProbe(intVal)
}
func (s *StreamPacket) setIsProbe(tmp656 uint8) bool {
	s.tmp53 = (s.tmp53 & (^(uint8(1) << uint8(4)))) | ((uint8(tmp656) & uint8(1)) << uint8(4))
	return true
}

func (s *StreamPacket) Reserved() uint8 {
	return uint8(((s.tmp53 >> uint8(0)) & uint8(15)))
}

func (s *StreamPacket) SetReserved(tmp651 uint8) bool {
	s.tmp53 = (s.tmp53 & (^(uint8(15) << uint8(0)))) | ((uint8(tmp651) & uint8(15)) << uint8(0))
	return true
}

type tmp750 struct {
	Id Varint
}

type Variant318 struct {
	tmp750 tmp750
}

type tmp747 struct {
	Offset Varint
}

type Variant317 struct {
	tmp747 tmp747
}

type StreamPacket struct {
	tmp53  uint8
	tmp420 Variant318
	tmp417 Variant317
	Data   []uint8
}

func (s *StreamPacket) Id() *Varint {
	if s.hasId() == 1 {
		return &s.tmp420.tmp750.Id
	}
	return nil
}
func (s *StreamPacket) SetId(tmp634 Varint) bool {
	if s.hasId() == 1 {
		s.tmp420.tmp750.Id = tmp634
		return true
	}
	return false
}

func (s *StreamPacket) Offset() *Varint {
	if s.hasOffset() == 1 {
		return &s.tmp417.tmp747.Offset
	}
	return nil
}
func (s *StreamPacket) SetOffset(tmp628 Varint) bool {
	if s.hasOffset() == 1 {
		s.tmp417.tmp747.Offset = tmp628
		return true
	}
	return false
}

func (s *StreamPacket) Write(tmp51 io.Writer) error {
	tmp51ByteIO, _ := tmp51.(io.ByteWriter)
	_ = tmp51ByteIO
	/* config.go.union("noheap")*/
	tmp638 := [1]uint8{}
	tmp638[0] = uint8((s.hasId() & 1)) << uint8(7)
	tmp638[0] = tmp638[0] | (uint8((s.hasOffset() & 1)) << uint8(6))
	tmp638[0] = tmp638[0] | (uint8((s.isEof() & 1)) << uint8(5))
	tmp638[0] = tmp638[0] | (uint8((s.isProbe() & 1)) << uint8(4))
	tmp638[0] = tmp638[0] | uint8((s.Reserved() & 15))
	if tmp51ByteIO != nil {
		if err := tmp51ByteIO.WriteByte(tmp638[0]); err != nil {
			return err
		}
	} else {
		if _, err := tmp51.Write([]byte{tmp638[0]}); err != nil {
			return err
		}
	}
	if s.hasId() == 1 {
		tmp740 := s.tmp420.tmp750.Id.Write(tmp51)
		if tmp740 != nil {
			return tmp740
		}
	}
	if s.hasOffset() == 1 {
		tmp738 := s.tmp417.tmp747.Offset.Write(tmp51)
		if tmp738 != nil {
			return tmp738
		}
	}
	if _, err := tmp51.Write(s.Data); err != nil {
		return err
	}
	return nil
}
func (s *StreamPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *StreamPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamPacket) EncodeSlice(tmp51 []byte, tmp51Offset *int) error {
	/* config.go.union("noheap")*/
	tmp638 := []uint8{}
	if len(tmp51)-*tmp51Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"StreamPacket::Reserved\"")
	}
	tmp638 = tmp51[*tmp51Offset : *tmp51Offset+int(1)]
	tmp638[0] = uint8((s.hasId() & 1)) << uint8(7)
	tmp638[0] = tmp638[0] | (uint8((s.hasOffset() & 1)) << uint8(6))
	tmp638[0] = tmp638[0] | (uint8((s.isEof() & 1)) << uint8(5))
	tmp638[0] = tmp638[0] | (uint8((s.isProbe() & 1)) << uint8(4))
	tmp638[0] = tmp638[0] | uint8((s.Reserved() & 15))
	*tmp51Offset += int(1)
	if s.hasId() == 1 {
		tmp740 := s.tmp420.tmp750.Id.EncodeSlice(tmp51, tmp51Offset)
		if tmp740 != nil {
			return tmp740
		}
	}
	if s.hasOffset() == 1 {
		tmp738 := s.tmp417.tmp747.Offset.EncodeSlice(tmp51, tmp51Offset)
		if tmp738 != nil {
			return tmp738
		}
	}
	if len(tmp51)-*tmp51Offset < int(0+len(s.Data)) {
		return errors.New("not enough space to write for field \"StreamPacket::Data\"")
	}
	copy(tmp51[*tmp51Offset:*tmp51Offset+int(len(s.Data))], s.Data)
	*tmp51Offset += int(len(s.Data))
	return nil
}
func (s *StreamPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *StreamPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamPacket) Append(tmp51 []byte) ([]byte, error) {
	/* config.go.union("noheap")*/
	tmp638 := [1]uint8{}
	tmp638[0] = uint8((s.hasId() & 1)) << uint8(7)
	tmp638[0] = tmp638[0] | (uint8((s.hasOffset() & 1)) << uint8(6))
	tmp638[0] = tmp638[0] | (uint8((s.isEof() & 1)) << uint8(5))
	tmp638[0] = tmp638[0] | (uint8((s.isProbe() & 1)) << uint8(4))
	tmp638[0] = tmp638[0] | uint8((s.Reserved() & 15))
	tmp51 = append(tmp51, tmp638[:1]...)
	if s.hasId() == 1 {
		var tmp740 error
		tmp51, tmp740 = s.tmp420.tmp750.Id.Append(tmp51)

		if tmp740 != nil {
			return nil, tmp740
		}
	}
	if s.hasOffset() == 1 {
		var tmp738 error
		tmp51, tmp738 = s.tmp417.tmp747.Offset.Append(tmp51)

		if tmp738 != nil {
			return nil, tmp738
		}
	}
	tmp51 = append(tmp51, s.Data...)
	return tmp51, nil
}
func (s *StreamPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *StreamPacket) Read(tmp39 io.Reader) error {
	tmp39ByteIO, _ := tmp39.(io.ByteReader)
	_ = tmp39ByteIO
	/* config.go.union("noheap")*/
	tmp756 := [1]uint8{}
	if tmp39ByteIO != nil {
		var err error
		tmp756[0], err = tmp39ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp39, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"tmp295\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp756[0] = buf[0]
	}
	tmp238 := uint8(0)
	tmp238 = uint8(((tmp756[0] & 128) >> uint8(7)))
	s.setHasId(tmp238)
	tmp682 := uint8(0)
	tmp682 = uint8(((tmp756[0] & uint8(64)) >> uint8(6)))
	s.setHasOffset(tmp682)
	tmp678 := uint8(0)
	tmp678 = uint8(((tmp756[0] & uint8(32)) >> uint8(5)))
	s.setIsEof(tmp678)
	tmp673 := uint8(0)
	tmp673 = uint8(((tmp756[0] & uint8(16)) >> uint8(4)))
	s.setIsProbe(tmp673)
	tmp646 := uint8(0)
	tmp646 = uint8((tmp756[0] & uint8(15)))
	s.SetReserved(tmp646)
	if s.hasId() == 1 {
		tmp641 := s.tmp420.tmp750.Id.Read(tmp39)
		if tmp641 != nil {
			return tmp641
		}
	}
	if s.hasOffset() == 1 {
		tmp861 := s.tmp417.tmp747.Offset.Read(tmp39)
		if tmp861 != nil {
			return tmp861
		}
	}
	{
		var readErr error
		s.Data, readErr = io.ReadAll(tmp39)
		if readErr != nil {
			return readErr
		}
	}
	return nil
}
func (s *StreamPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *StreamPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *StreamPacket) DecodeSlice(tmp39 []byte, tmp39Offset *int) error {
	/* config.go.union("noheap")*/
	tmp756 := []uint8{}
	if len(tmp39)-*tmp39Offset < 1 {
		return errors.New("not enough data to read for field \"tmp295\"")
	}
	tmp756 = tmp39[*tmp39Offset : *tmp39Offset+1]
	*tmp39Offset += int(1)
	tmp238 := uint8(0)
	tmp238 = uint8(((tmp756[0] & 128) >> uint8(7)))
	s.setHasId(tmp238)
	tmp682 := uint8(0)
	tmp682 = uint8(((tmp756[0] & uint8(64)) >> uint8(6)))
	s.setHasOffset(tmp682)
	tmp678 := uint8(0)
	tmp678 = uint8(((tmp756[0] & uint8(32)) >> uint8(5)))
	s.setIsEof(tmp678)
	tmp673 := uint8(0)
	tmp673 = uint8(((tmp756[0] & uint8(16)) >> uint8(4)))
	s.setIsProbe(tmp673)
	tmp646 := uint8(0)
	tmp646 = uint8((tmp756[0] & uint8(15)))
	s.SetReserved(tmp646)
	if s.hasId() == 1 {
		tmp641 := s.tmp420.tmp750.Id.DecodeSlice(tmp39, tmp39Offset)
		if tmp641 != nil {
			return tmp641
		}
	}
	if s.hasOffset() == 1 {
		tmp861 := s.tmp417.tmp747.Offset.DecodeSlice(tmp39, tmp39Offset)
		if tmp861 != nil {
			return tmp861
		}
	}
	s.Data = tmp39[*tmp39Offset:]
	*tmp39Offset += len(s.Data)
	return nil
}
func (s *StreamPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *StreamPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type ACKRange struct {
	Offset Varint
	Delta  Varint
}

func (a *ACKRange) Write(tmp260 io.Writer) error {
	tmp838 := a.Offset.Write(tmp260)
	if tmp838 != nil {
		return tmp838
	}
	tmp670 := a.Delta.Write(tmp260)
	if tmp670 != nil {
		return tmp670
	}
	return nil
}
func (s *ACKRange) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *ACKRange) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (a *ACKRange) EncodeSlice(tmp260 []byte, tmp260Offset *int) error {
	tmp838 := a.Offset.EncodeSlice(tmp260, tmp260Offset)
	if tmp838 != nil {
		return tmp838
	}
	tmp670 := a.Delta.EncodeSlice(tmp260, tmp260Offset)
	if tmp670 != nil {
		return tmp670
	}
	return nil
}
func (s *ACKRange) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *ACKRange) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (a *ACKRange) Append(tmp260 []byte) ([]byte, error) {
	var tmp838 error
	tmp260, tmp838 = a.Offset.Append(tmp260)

	if tmp838 != nil {
		return nil, tmp838
	}
	var tmp670 error
	tmp260, tmp670 = a.Delta.Append(tmp260)

	if tmp670 != nil {
		return nil, tmp670
	}
	return tmp260, nil
}
func (s *ACKRange) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (a *ACKRange) Read(tmp259 io.Reader) error {
	tmp667 := a.Offset.Read(tmp259)
	if tmp667 != nil {
		return tmp667
	}
	tmp664 := a.Delta.Read(tmp259)
	if tmp664 != nil {
		return tmp664
	}
	return nil
}
func (s *ACKRange) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *ACKRange) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (a *ACKRange) DecodeSlice(tmp259 []byte, tmp259Offset *int) error {
	tmp667 := a.Offset.DecodeSlice(tmp259, tmp259Offset)
	if tmp667 != nil {
		return tmp667
	}
	tmp664 := a.Delta.DecodeSlice(tmp259, tmp259Offset)
	if tmp664 != nil {
		return tmp664
	}
	return nil
}
func (s *ACKRange) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *ACKRange) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type StreamACKPacket struct {
	LargestAck Varint
	AckDelay   Varint
	FirstDelta Varint
	Len        Varint
	Ranges     []ACKRange
}

func (s *StreamACKPacket) Write(tmp95 io.Writer) error {
	tmp655 := s.LargestAck.Write(tmp95)
	if tmp655 != nil {
		return tmp655
	}
	tmp649 := s.AckDelay.Write(tmp95)
	if tmp649 != nil {
		return tmp649
	}
	tmp650 := s.FirstDelta.Write(tmp95)
	if tmp650 != nil {
		return tmp650
	}
	tmp644 := s.Len.Write(tmp95)
	if tmp644 != nil {
		return tmp644
	}
	if len(s.Ranges) != int(int(s.Len.Value())) {
		return fmt.Errorf("size mismatch when writing field \"StreamACKPacket::Ranges\": expected %d, got %d", int(int(s.Len.Value())), len(s.Ranges))
	}
	tmp307 := int(0)
	for tmp307 < int(s.Len.Value()) {
		tmp711 := s.Ranges[tmp307].Write(tmp95)
		if tmp711 != nil {
			return tmp711
		}
		tmp307 = tmp307 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *StreamACKPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamACKPacket) EncodeSlice(tmp95 []byte, tmp95Offset *int) error {
	tmp655 := s.LargestAck.EncodeSlice(tmp95, tmp95Offset)
	if tmp655 != nil {
		return tmp655
	}
	tmp649 := s.AckDelay.EncodeSlice(tmp95, tmp95Offset)
	if tmp649 != nil {
		return tmp649
	}
	tmp650 := s.FirstDelta.EncodeSlice(tmp95, tmp95Offset)
	if tmp650 != nil {
		return tmp650
	}
	tmp644 := s.Len.EncodeSlice(tmp95, tmp95Offset)
	if tmp644 != nil {
		return tmp644
	}
	if len(s.Ranges) != int(int(s.Len.Value())) {
		return fmt.Errorf("size mismatch when writing field \"StreamACKPacket::Ranges\": expected %d, got %d", int(int(s.Len.Value())), len(s.Ranges))
	}
	tmp307 := int(0)
	for tmp307 < int(s.Len.Value()) {
		tmp711 := s.Ranges[tmp307].EncodeSlice(tmp95, tmp95Offset)
		if tmp711 != nil {
			return tmp711
		}
		tmp307 = tmp307 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *StreamACKPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamACKPacket) Append(tmp95 []byte) ([]byte, error) {
	var tmp655 error
	tmp95, tmp655 = s.LargestAck.Append(tmp95)

	if tmp655 != nil {
		return nil, tmp655
	}
	var tmp649 error
	tmp95, tmp649 = s.AckDelay.Append(tmp95)

	if tmp649 != nil {
		return nil, tmp649
	}
	var tmp650 error
	tmp95, tmp650 = s.FirstDelta.Append(tmp95)

	if tmp650 != nil {
		return nil, tmp650
	}
	var tmp644 error
	tmp95, tmp644 = s.Len.Append(tmp95)

	if tmp644 != nil {
		return nil, tmp644
	}
	if len(s.Ranges) != int(int(s.Len.Value())) {
		return nil, fmt.Errorf("size mismatch when writing field \"StreamACKPacket::Ranges\": expected %d, got %d", int(int(s.Len.Value())), len(s.Ranges))
	}
	tmp307 := int(0)
	for tmp307 < int(s.Len.Value()) {
		var tmp711 error
		tmp95, tmp711 = s.Ranges[tmp307].Append(tmp95)

		if tmp711 != nil {
			return nil, tmp711
		}
		tmp307 = tmp307 + int(1)
	}
	return tmp95, nil
}
func (s *StreamACKPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *StreamACKPacket) Read(tmp94 io.Reader) error {
	tmp704 := s.LargestAck.Read(tmp94)
	if tmp704 != nil {
		return tmp704
	}
	tmp708 := s.AckDelay.Read(tmp94)
	if tmp708 != nil {
		return tmp708
	}
	tmp705 := s.FirstDelta.Read(tmp94)
	if tmp705 != nil {
		return tmp705
	}
	tmp694 := s.Len.Read(tmp94)
	if tmp694 != nil {
		return tmp694
	}
	tmp399 := int(0)
	for tmp399 < int(s.Len.Value()) {
		tmp700 := ACKRange{}
		tmp697 := tmp700.Read(tmp94)
		if tmp697 != nil {
			return tmp697
		}
		s.Ranges = append(s.Ranges, tmp700)
		tmp399 = tmp399 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *StreamACKPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *StreamACKPacket) DecodeSlice(tmp94 []byte, tmp94Offset *int) error {
	tmp704 := s.LargestAck.DecodeSlice(tmp94, tmp94Offset)
	if tmp704 != nil {
		return tmp704
	}
	tmp708 := s.AckDelay.DecodeSlice(tmp94, tmp94Offset)
	if tmp708 != nil {
		return tmp708
	}
	tmp705 := s.FirstDelta.DecodeSlice(tmp94, tmp94Offset)
	if tmp705 != nil {
		return tmp705
	}
	tmp694 := s.Len.DecodeSlice(tmp94, tmp94Offset)
	if tmp694 != nil {
		return tmp694
	}
	tmp399 := int(0)
	for tmp399 < int(s.Len.Value()) {
		tmp700 := ACKRange{}
		tmp697 := tmp700.DecodeSlice(tmp94, tmp94Offset)
		if tmp697 != nil {
			return tmp697
		}
		s.Ranges = append(s.Ranges, tmp700)
		tmp399 = tmp399 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *StreamACKPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type UpdateWindow struct {
	Id        Varint
	WindowMax Varint
}

func (u *UpdateWindow) Write(tmp242 io.Writer) error {
	tmp726 := u.Id.Write(tmp242)
	if tmp726 != nil {
		return tmp726
	}
	tmp723 := u.WindowMax.Write(tmp242)
	if tmp723 != nil {
		return tmp723
	}
	return nil
}
func (s *UpdateWindow) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *UpdateWindow) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (u *UpdateWindow) EncodeSlice(tmp242 []byte, tmp242Offset *int) error {
	tmp726 := u.Id.EncodeSlice(tmp242, tmp242Offset)
	if tmp726 != nil {
		return tmp726
	}
	tmp723 := u.WindowMax.EncodeSlice(tmp242, tmp242Offset)
	if tmp723 != nil {
		return tmp723
	}
	return nil
}
func (s *UpdateWindow) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *UpdateWindow) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (u *UpdateWindow) Append(tmp242 []byte) ([]byte, error) {
	var tmp726 error
	tmp242, tmp726 = u.Id.Append(tmp242)

	if tmp726 != nil {
		return nil, tmp726
	}
	var tmp723 error
	tmp242, tmp723 = u.WindowMax.Append(tmp242)

	if tmp723 != nil {
		return nil, tmp723
	}
	return tmp242, nil
}
func (s *UpdateWindow) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (u *UpdateWindow) Read(tmp241 io.Reader) error {
	tmp718 := u.Id.Read(tmp241)
	if tmp718 != nil {
		return tmp718
	}
	tmp734 := u.WindowMax.Read(tmp241)
	if tmp734 != nil {
		return tmp734
	}
	return nil
}
func (s *UpdateWindow) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *UpdateWindow) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (u *UpdateWindow) DecodeSlice(tmp241 []byte, tmp241Offset *int) error {
	tmp718 := u.Id.DecodeSlice(tmp241, tmp241Offset)
	if tmp718 != nil {
		return tmp718
	}
	tmp734 := u.WindowMax.DecodeSlice(tmp241, tmp241Offset)
	if tmp734 != nil {
		return tmp734
	}
	return nil
}
func (s *UpdateWindow) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *UpdateWindow) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type CancelStreamPacket struct {
	Id Varint
}

func (c *CancelStreamPacket) Write(tmp292 io.Writer) error {
	tmp629 := c.Id.Write(tmp292)
	if tmp629 != nil {
		return tmp629
	}
	return nil
}
func (s *CancelStreamPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *CancelStreamPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *CancelStreamPacket) EncodeSlice(tmp292 []byte, tmp292Offset *int) error {
	tmp629 := c.Id.EncodeSlice(tmp292, tmp292Offset)
	if tmp629 != nil {
		return tmp629
	}
	return nil
}
func (s *CancelStreamPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *CancelStreamPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *CancelStreamPacket) Append(tmp292 []byte) ([]byte, error) {
	var tmp629 error
	tmp292, tmp629 = c.Id.Append(tmp292)

	if tmp629 != nil {
		return nil, tmp629
	}
	return tmp292, nil
}
func (s *CancelStreamPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (c *CancelStreamPacket) Read(tmp291 io.Reader) error {
	tmp624 := c.Id.Read(tmp291)
	if tmp624 != nil {
		return tmp624
	}
	return nil
}
func (s *CancelStreamPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *CancelStreamPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (c *CancelStreamPacket) DecodeSlice(tmp291 []byte, tmp291Offset *int) error {
	tmp624 := c.Id.DecodeSlice(tmp291, tmp291Offset)
	if tmp624 != nil {
		return tmp624
	}
	return nil
}
func (s *CancelStreamPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *CancelStreamPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type CloseStatus uint8

const (
	CloseStatus_Ok     CloseStatus = 0
	CloseStatus_Failed CloseStatus = 1
)

func (e CloseStatus) String() string {
	switch e {
	case CloseStatus_Ok:
		return "Ok"
	case CloseStatus_Failed:
		return "Failed"
	default:
		return fmt.Sprintf("CloseStatus(%d)", e)
	}
}

type PingBody struct {
	Nanos uint64
}

func (p *PingBody) Write(tmp378 io.Writer) error {
	tmp443 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp443[:], uint64(p.Nanos))
	if _, err := tmp378.Write(tmp443[:8]); err != nil {
		return err
	}
	return nil
}
func (s *PingBody) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PingBody) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PingBody) EncodeSlice(tmp378 []byte, tmp378Offset *int) error {
	tmp443 := []uint8{}
	if len(tmp378)-*tmp378Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"PingBody::Nanos\"")
	}
	tmp443 = tmp378[*tmp378Offset : *tmp378Offset+int(8)]
	binary.BigEndian.PutUint64(tmp443[:], uint64(p.Nanos))
	*tmp378Offset += int(8)
	return nil
}
func (s *PingBody) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PingBody) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PingBody) Append(tmp378 []byte) ([]byte, error) {
	tmp443 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp443[:], uint64(p.Nanos))
	tmp378 = append(tmp378, tmp443[:8]...)
	return tmp378, nil
}
func (s *PingBody) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PingBody) Read(tmp380 io.Reader) error {
	tmp432 := [8]uint8{}
	if _, err := io.ReadFull(tmp380, tmp432[0:0+8]); err != nil {
		return err
	}
	p.Nanos = binary.BigEndian.Uint64(tmp432[:])
	return nil
}
func (s *PingBody) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PingBody) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PingBody) DecodeSlice(tmp380 []byte, tmp380Offset *int) error {
	tmp432 := []uint8{}
	if len(tmp380)-*tmp380Offset < 8 {
		return errors.New("not enough data to read for field \"PingBody::Nanos\"")
	}
	tmp432 = tmp380[*tmp380Offset : *tmp380Offset+8]
	*tmp380Offset += int(8)
	p.Nanos = binary.BigEndian.Uint64(tmp432[:])
	return nil
}
func (s *PingBody) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PingBody) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type CloseBody struct {
	Status     CloseStatus
	MessageLen uint16
	Message    []uint8
}

func (c *CloseBody) SetMessage(tmp597 []uint8) bool {
	if len(tmp597) > int(65535) {
		return false
	}
	c.MessageLen = uint16(len(tmp597))
	c.Message = tmp597
	return true
}

func (c *CloseBody) Write(tmp117 io.Writer) error {
	tmp293 := [1]uint8{}
	tmp293[0] = uint8(c.Status)
	if _, err := tmp117.Write(tmp293[:1]); err != nil {
		return err
	}
	tmp602 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp602[:], uint16(c.MessageLen))
	if _, err := tmp117.Write(tmp602[:2]); err != nil {
		return err
	}
	if len(c.Message) != int(int(c.MessageLen)) {
		return fmt.Errorf("size mismatch when writing field \"CloseBody::Message\": expected %d, got %d", int(int(c.MessageLen)), len(c.Message))
	}
	if _, err := tmp117.Write(c.Message); err != nil {
		return err
	}
	return nil
}
func (s *CloseBody) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *CloseBody) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *CloseBody) EncodeSlice(tmp117 []byte, tmp117Offset *int) error {
	tmp293 := []uint8{}
	if len(tmp117)-*tmp117Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"CloseBody::Status\"")
	}
	tmp293 = tmp117[*tmp117Offset : *tmp117Offset+int(1)]
	tmp293[0] = uint8(c.Status)
	*tmp117Offset += int(1)
	tmp602 := []uint8{}
	if len(tmp117)-*tmp117Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"CloseBody::MessageLen\"")
	}
	tmp602 = tmp117[*tmp117Offset : *tmp117Offset+int(2)]
	binary.BigEndian.PutUint16(tmp602[:], uint16(c.MessageLen))
	*tmp117Offset += int(2)
	if len(c.Message) != int(int(c.MessageLen)) {
		return fmt.Errorf("size mismatch when writing field \"CloseBody::Message\": expected %d, got %d", int(int(c.MessageLen)), len(c.Message))
	}
	if len(tmp117)-*tmp117Offset < int(0+int(c.MessageLen)) {
		return errors.New("not enough space to write for field \"CloseBody::Message\"")
	}
	copy(tmp117[*tmp117Offset:*tmp117Offset+int(int(c.MessageLen))], c.Message)
	*tmp117Offset += int(int(c.MessageLen))
	return nil
}
func (s *CloseBody) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *CloseBody) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *CloseBody) Append(tmp117 []byte) ([]byte, error) {
	tmp293 := [1]uint8{}
	tmp293[0] = uint8(c.Status)
	tmp117 = append(tmp117, tmp293[:1]...)
	tmp602 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp602[:], uint16(c.MessageLen))
	tmp117 = append(tmp117, tmp602[:2]...)
	if len(c.Message) != int(int(c.MessageLen)) {
		return nil, fmt.Errorf("size mismatch when writing field \"CloseBody::Message\": expected %d, got %d", int(int(c.MessageLen)), len(c.Message))
	}
	tmp117 = append(tmp117, c.Message...)
	return tmp117, nil
}
func (s *CloseBody) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (c *CloseBody) Read(tmp118 io.Reader) error {
	tmp612 := uint8(0)
	tmp38 := [1]uint8{}
	if _, err := io.ReadFull(tmp118, tmp38[0:0+1]); err != nil {
		return err
	}
	tmp612 = tmp38[0]
	c.Status = CloseStatus(tmp612)
	tmp609 := [2]uint8{}
	if _, err := io.ReadFull(tmp118, tmp609[0:0+2]); err != nil {
		return err
	}
	c.MessageLen = binary.BigEndian.Uint16(tmp609[:])
	if seeker, ok := tmp118.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(c.MessageLen)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(c.MessageLen)))
		}
		c.Message = make([]byte, int(c.MessageLen))
		if _, err := io.ReadFull(tmp118, c.Message[0:0+int(c.MessageLen)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_1402 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_1402, tmp118, int64(int(c.MessageLen))); err != nil {
			return err
		}
		c.Message = io_temp_1402.Bytes()
	}
	return nil
}
func (s *CloseBody) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *CloseBody) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (c *CloseBody) DecodeSlice(tmp118 []byte, tmp118Offset *int) error {
	tmp612 := uint8(0)
	tmp38 := []uint8{}
	if len(tmp118)-*tmp118Offset < 1 {
		return errors.New("not enough data to read for field \"CloseBody::Status\"")
	}
	tmp38 = tmp118[*tmp118Offset : *tmp118Offset+1]
	*tmp118Offset += int(1)
	tmp612 = tmp38[0]
	c.Status = CloseStatus(tmp612)
	tmp609 := []uint8{}
	if len(tmp118)-*tmp118Offset < 2 {
		return errors.New("not enough data to read for field \"CloseBody::MessageLen\"")
	}
	tmp609 = tmp118[*tmp118Offset : *tmp118Offset+2]
	*tmp118Offset += int(2)
	c.MessageLen = binary.BigEndian.Uint16(tmp609[:])
	if len(tmp118)-*tmp118Offset < int(c.MessageLen) {
		return errors.New("not enough data to read for field \"CloseBody::Message\"")
	}
	c.Message = tmp118[*tmp118Offset : *tmp118Offset+int(c.MessageLen)]
	*tmp118Offset += int(int(c.MessageLen))
	return nil
}
func (s *CloseBody) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *CloseBody) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

const USER_DEFINED_START = uint8(64)

type ApplicationPayloadKind uint8

const (
	ApplicationPayloadKind_Ping               ApplicationPayloadKind = 0
	ApplicationPayloadKind_Pong               ApplicationPayloadKind = 1
	ApplicationPayloadKind_Close              ApplicationPayloadKind = 2
	ApplicationPayloadKind_StreamData         ApplicationPayloadKind = 3
	ApplicationPayloadKind_StreamCancel       ApplicationPayloadKind = 4
	ApplicationPayloadKind_StreamAck          ApplicationPayloadKind = 5
	ApplicationPayloadKind_StreamWindowUpdate ApplicationPayloadKind = 6
	ApplicationPayloadKind_Datagram           ApplicationPayloadKind = 7
)

func (e ApplicationPayloadKind) String() string {
	switch e {
	case ApplicationPayloadKind_Ping:
		return "Ping"
	case ApplicationPayloadKind_Pong:
		return "Pong"
	case ApplicationPayloadKind_Close:
		return "Close"
	case ApplicationPayloadKind_StreamData:
		return "StreamData"
	case ApplicationPayloadKind_StreamCancel:
		return "StreamCancel"
	case ApplicationPayloadKind_StreamAck:
		return "StreamAck"
	case ApplicationPayloadKind_StreamWindowUpdate:
		return "StreamWindowUpdate"
	case ApplicationPayloadKind_Datagram:
		return "Datagram"
	default:
		return fmt.Sprintf("ApplicationPayloadKind(%d)", e)
	}
}

type DatagramPacket struct {
	Data []uint8
}

func (d *DatagramPacket) Write(tmp372 io.Writer) error {
	if _, err := tmp372.Write(d.Data); err != nil {
		return err
	}
	return nil
}
func (s *DatagramPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *DatagramPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (d *DatagramPacket) EncodeSlice(tmp372 []byte, tmp372Offset *int) error {
	if len(tmp372)-*tmp372Offset < int(0+len(d.Data)) {
		return errors.New("not enough space to write for field \"DatagramPacket::Data\"")
	}
	copy(tmp372[*tmp372Offset:*tmp372Offset+int(len(d.Data))], d.Data)
	*tmp372Offset += int(len(d.Data))
	return nil
}
func (s *DatagramPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *DatagramPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (d *DatagramPacket) Append(tmp372 []byte) ([]byte, error) {
	tmp372 = append(tmp372, d.Data...)
	return tmp372, nil
}
func (s *DatagramPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (d *DatagramPacket) Read(tmp278 io.Reader) error {
	{
		var readErr error
		d.Data, readErr = io.ReadAll(tmp278)
		if readErr != nil {
			return readErr
		}
	}
	return nil
}
func (s *DatagramPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *DatagramPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (d *DatagramPacket) DecodeSlice(tmp278 []byte, tmp278Offset *int) error {
	d.Data = tmp278[*tmp278Offset:]
	*tmp278Offset += len(d.Data)
	return nil
}
func (s *DatagramPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *DatagramPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type PacketHeader struct {
	Kind ApplicationPayloadKind
}

func (p *PacketHeader) Write(tmp215 io.Writer) error {
	tmp215ByteIO, _ := tmp215.(io.ByteWriter)
	_ = tmp215ByteIO
	if tmp215ByteIO != nil {
		if err := tmp215ByteIO.WriteByte(uint8(p.Kind)); err != nil {
			return err
		}
	} else {
		if _, err := tmp215.Write([]byte{uint8(p.Kind)}); err != nil {
			return err
		}
	}
	return nil
}
func (s *PacketHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PacketHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) EncodeSlice(tmp215 []byte, tmp215Offset *int) error {
	tmp584 := []uint8{}
	if len(tmp215)-*tmp215Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::Kind\"")
	}
	tmp584 = tmp215[*tmp215Offset : *tmp215Offset+int(1)]
	tmp584[0] = uint8(p.Kind)
	*tmp215Offset += int(1)
	return nil
}
func (s *PacketHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PacketHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) Append(tmp215 []byte) ([]byte, error) {
	tmp584 := [1]uint8{}
	tmp584[0] = uint8(p.Kind)
	tmp215 = append(tmp215, tmp584[:1]...)
	return tmp215, nil
}
func (s *PacketHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PacketHeader) Read(tmp217 io.Reader) error {
	tmp217ByteIO, _ := tmp217.(io.ByteReader)
	_ = tmp217ByteIO
	tmp590 := uint8(0)
	if tmp217ByteIO != nil {
		var err error
		tmp590, err = tmp217ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp217, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"PacketHeader::Kind\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp590 = buf[0]
	}
	p.Kind = ApplicationPayloadKind(tmp590)
	return nil
}
func (s *PacketHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PacketHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PacketHeader) DecodeSlice(tmp217 []byte, tmp217Offset *int) error {
	tmp590 := uint8(0)
	tmp589 := []uint8{}
	if len(tmp217)-*tmp217Offset < 1 {
		return errors.New("not enough data to read for field \"PacketHeader::Kind\"")
	}
	tmp589 = tmp217[*tmp217Offset : *tmp217Offset+1]
	*tmp217Offset += int(1)
	tmp590 = tmp589[0]
	p.Kind = ApplicationPayloadKind(tmp590)
	return nil
}
func (s *PacketHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PacketHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func IsStreamRelated(Kind ApplicationPayloadKind) bool {
	tmp369 := false
	if ((((ApplicationPayloadKind_StreamData == Kind) || (ApplicationPayloadKind_StreamCancel == Kind)) || (ApplicationPayloadKind_StreamAck == Kind)) || (ApplicationPayloadKind_StreamWindowUpdate == Kind)) || (ApplicationPayloadKind_Datagram == Kind) {
		tmp369 = true
	} else {
		tmp369 = false
	}
	return tmp369
}

type tmp572 struct {
	StreamData StreamPacket
}

type tmp570 struct {
	StreamCancel CancelStreamPacket
}

type tmp568 struct {
	StreamAck StreamACKPacket
}

type tmp566 struct {
	WindowUpdate UpdateWindow
}

type tmp564 struct {
	Datagram DatagramPacket
}

type tmp1278 struct {
}

type Variant90 struct {
	tmp572  tmp572
	tmp570  tmp570
	tmp568  tmp568
	tmp566  tmp566
	tmp564  tmp564
	tmp1278 tmp1278
}

type StreamAppPacket struct {
	Header PacketHeader
	tmp368 Variant90
}

func (s *StreamAppPacket) Datagram() *DatagramPacket {
	if (((ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind)) || (ApplicationPayloadKind_StreamAck == s.Header.Kind)) || (ApplicationPayloadKind_StreamWindowUpdate == s.Header.Kind) {
		return nil
	} else if s.Header.Kind == ApplicationPayloadKind_Datagram {
		return &s.tmp368.tmp564.Datagram
	}
	return nil
}
func (s *StreamAppPacket) SetDatagram(tmp478 DatagramPacket) bool {
	if (((ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind)) || (ApplicationPayloadKind_StreamAck == s.Header.Kind)) || (ApplicationPayloadKind_StreamWindowUpdate == s.Header.Kind) {
		return false
	} else if s.Header.Kind == ApplicationPayloadKind_Datagram {
		s.tmp368.tmp564.Datagram = tmp478
		return true
	}
	return false
}

func (s *StreamAppPacket) StreamAck() *StreamACKPacket {
	if (ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind) {
		return nil
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		return &s.tmp368.tmp568.StreamAck
	}
	return nil
}
func (s *StreamAppPacket) SetStreamAck(tmp469 StreamACKPacket) bool {
	if (ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind) {
		return false
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		s.tmp368.tmp568.StreamAck = tmp469
		return true
	}
	return false
}

func (s *StreamAppPacket) StreamCancel() *CancelStreamPacket {
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		return nil
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		return &s.tmp368.tmp570.StreamCancel
	}
	return nil
}
func (s *StreamAppPacket) SetStreamCancel(tmp466 CancelStreamPacket) bool {
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		return false
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		s.tmp368.tmp570.StreamCancel = tmp466
		return true
	}
	return false
}

func (s *StreamAppPacket) StreamData() *StreamPacket {
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		return &s.tmp368.tmp572.StreamData
	}
	return nil
}
func (s *StreamAppPacket) SetStreamData(tmp463 StreamPacket) bool {
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		s.tmp368.tmp572.StreamData = tmp463
		return true
	}
	return false
}

func (s *StreamAppPacket) WindowUpdate() *UpdateWindow {
	if ((ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind)) || (ApplicationPayloadKind_StreamAck == s.Header.Kind) {
		return nil
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		return &s.tmp368.tmp566.WindowUpdate
	}
	return nil
}
func (s *StreamAppPacket) SetWindowUpdate(tmp452 UpdateWindow) bool {
	if ((ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind)) || (ApplicationPayloadKind_StreamAck == s.Header.Kind) {
		return false
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		s.tmp368.tmp566.WindowUpdate = tmp452
		return true
	}
	return false
}

func (s *StreamAppPacket) Write(tmp107 io.Writer) error {
	tmp107ByteIO, _ := tmp107.(io.ByteWriter)
	_ = tmp107ByteIO
	/* config.go.union("noheap")*/
	tmp516 := s.Header.Write(tmp107)
	if tmp516 != nil {
		return tmp516
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp512 := s.tmp368.tmp572.StreamData.Write(tmp107)
		if tmp512 != nil {
			return tmp512
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp507 := s.tmp368.tmp570.StreamCancel.Write(tmp107)
		if tmp507 != nil {
			return tmp507
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp502 := s.tmp368.tmp568.StreamAck.Write(tmp107)
		if tmp502 != nil {
			return tmp502
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp497 := s.tmp368.tmp566.WindowUpdate.Write(tmp107)
		if tmp497 != nil {
			return tmp497
		}
	} else if s.Header.Kind == ApplicationPayloadKind_Datagram {
		tmp492 := s.tmp368.tmp564.Datagram.Write(tmp107)
		if tmp492 != nil {
			return tmp492
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *StreamAppPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *StreamAppPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamAppPacket) EncodeSlice(tmp107 []byte, tmp107Offset *int) error {
	/* config.go.union("noheap")*/
	tmp516 := s.Header.EncodeSlice(tmp107, tmp107Offset)
	if tmp516 != nil {
		return tmp516
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp512 := s.tmp368.tmp572.StreamData.EncodeSlice(tmp107, tmp107Offset)
		if tmp512 != nil {
			return tmp512
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp507 := s.tmp368.tmp570.StreamCancel.EncodeSlice(tmp107, tmp107Offset)
		if tmp507 != nil {
			return tmp507
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp502 := s.tmp368.tmp568.StreamAck.EncodeSlice(tmp107, tmp107Offset)
		if tmp502 != nil {
			return tmp502
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp497 := s.tmp368.tmp566.WindowUpdate.EncodeSlice(tmp107, tmp107Offset)
		if tmp497 != nil {
			return tmp497
		}
	} else if s.Header.Kind == ApplicationPayloadKind_Datagram {
		tmp492 := s.tmp368.tmp564.Datagram.EncodeSlice(tmp107, tmp107Offset)
		if tmp492 != nil {
			return tmp492
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *StreamAppPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *StreamAppPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamAppPacket) Append(tmp107 []byte) ([]byte, error) {
	/* config.go.union("noheap")*/
	var tmp516 error
	tmp107, tmp516 = s.Header.Append(tmp107)

	if tmp516 != nil {
		return nil, tmp516
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		var tmp512 error
		tmp107, tmp512 = s.tmp368.tmp572.StreamData.Append(tmp107)

		if tmp512 != nil {
			return nil, tmp512
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		var tmp507 error
		tmp107, tmp507 = s.tmp368.tmp570.StreamCancel.Append(tmp107)

		if tmp507 != nil {
			return nil, tmp507
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		var tmp502 error
		tmp107, tmp502 = s.tmp368.tmp568.StreamAck.Append(tmp107)

		if tmp502 != nil {
			return nil, tmp502
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		var tmp497 error
		tmp107, tmp497 = s.tmp368.tmp566.WindowUpdate.Append(tmp107)

		if tmp497 != nil {
			return nil, tmp497
		}
	} else if s.Header.Kind == ApplicationPayloadKind_Datagram {
		var tmp492 error
		tmp107, tmp492 = s.tmp368.tmp564.Datagram.Append(tmp107)

		if tmp492 != nil {
			return nil, tmp492
		}
	} else {
		return nil, errors.New("Unexpected packet")
	}
	return tmp107, nil
}
func (s *StreamAppPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *StreamAppPacket) Read(tmp114 io.Reader) error {
	tmp114ByteIO, _ := tmp114.(io.ByteReader)
	_ = tmp114ByteIO
	/* config.go.union("noheap")*/
	tmp553 := s.Header.Read(tmp114)
	if tmp553 != nil {
		return tmp553
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp548 := s.tmp368.tmp572.StreamData.Read(tmp114)
		if tmp548 != nil {
			return tmp548
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp542 := s.tmp368.tmp570.StreamCancel.Read(tmp114)
		if tmp542 != nil {
			return tmp542
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp536 := s.tmp368.tmp568.StreamAck.Read(tmp114)
		if tmp536 != nil {
			return tmp536
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp530 := s.tmp368.tmp566.WindowUpdate.Read(tmp114)
		if tmp530 != nil {
			return tmp530
		}
	} else if s.Header.Kind == ApplicationPayloadKind_Datagram {
		tmp524 := s.tmp368.tmp564.Datagram.Read(tmp114)
		if tmp524 != nil {
			return tmp524
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *StreamAppPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *StreamAppPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *StreamAppPacket) DecodeSlice(tmp114 []byte, tmp114Offset *int) error {
	/* config.go.union("noheap")*/
	tmp553 := s.Header.DecodeSlice(tmp114, tmp114Offset)
	if tmp553 != nil {
		return tmp553
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp548 := s.tmp368.tmp572.StreamData.DecodeSlice(tmp114, tmp114Offset)
		if tmp548 != nil {
			return tmp548
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp542 := s.tmp368.tmp570.StreamCancel.DecodeSlice(tmp114, tmp114Offset)
		if tmp542 != nil {
			return tmp542
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp536 := s.tmp368.tmp568.StreamAck.DecodeSlice(tmp114, tmp114Offset)
		if tmp536 != nil {
			return tmp536
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp530 := s.tmp368.tmp566.WindowUpdate.DecodeSlice(tmp114, tmp114Offset)
		if tmp530 != nil {
			return tmp530
		}
	} else if s.Header.Kind == ApplicationPayloadKind_Datagram {
		tmp524 := s.tmp368.tmp564.Datagram.DecodeSlice(tmp114, tmp114Offset)
		if tmp524 != nil {
			return tmp524
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *StreamAppPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *StreamAppPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
