// Code generated by ebm2go at https://github.com/on-keyday/brgen, DO NOT EDIT.
package wire

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("wire")*/
func (v *Varint) Prefix() uint8 {
	return uint8(((v.tmp235 >> uint64(62)) & uint64(3)))
}

func (v *Varint) SetPrefix(tmp786 uint8) bool {
	v.tmp235 = (v.tmp235 & (^(uint64(3) << uint64(62)))) | ((uint64(tmp786) & uint64(3)) << uint64(62))
	return true
}

func (v *Varint) tmp775() uint64 {
	return uint64(((v.tmp235 >> uint64(0)) & uint64(4611686018427387903)))
}

func (v *Varint) settmp414(tmp779 uint64) bool {
	v.tmp235 = (v.tmp235 & (^(uint64(4611686018427387903) << uint64(0)))) | ((uint64(tmp779) & uint64(4611686018427387903)) << uint64(0))
	return true
}

type Varint struct {
	tmp235 uint64
}

func (v *Varint) Value() uint64 {
	if v.Prefix() == uint8(0) {
		return uint64(uint8(v.tmp775()))
	} else if v.Prefix() == uint8(1) {
		return uint64(uint16(v.tmp775()))
	} else if v.Prefix() == 2 {
		return uint64(uint32(v.tmp775()))
	} else if v.Prefix() == 3 {
		return uint64(uint64(v.tmp775()))
	}
	return uint64(0)
}
func (v *Varint) SetValue(tmp674 uint64) bool {
	if v.Prefix() == uint8(0) {
		v.settmp414(uint64(uint8(tmp674)))
		return true
	} else if v.Prefix() == uint8(1) {
		v.settmp414(uint64(uint16(tmp674)))
		return true
	} else if v.Prefix() == 2 {
		v.settmp414(uint64(uint32(tmp674)))
		return true
	} else if v.Prefix() == 3 {
		v.settmp414(uint64(uint64(tmp674)))
		return true
	}
	return false
}

func (v *Varint) Write(tmp77 io.Writer) error {
	tmp716 := [8]uint8{}
	tmp716[0] = uint8((v.Prefix() & 3)) << uint8(6)
	if v.Prefix() == uint8(0) {
		tmp716[0] = tmp716[0] | uint8((uint8(v.tmp775()) & 63))
		if _, err := tmp77.Write(tmp716[:1]); err != nil {
			return err
		}
	} else if v.Prefix() == uint8(1) {
		tmp716[0] = tmp716[0] | uint8(((uint16(v.tmp775()) >> uint16(8)) & uint16(63)))
		tmp716[1] = uint8((uint16(v.tmp775()) & uint16(255)))
		if _, err := tmp77.Write(tmp716[:2]); err != nil {
			return err
		}
	} else if v.Prefix() == 2 {
		tmp716[0] = tmp716[0] | uint8(((uint32(v.tmp775()) >> uint32(24)) & uint32(63)))
		tmp716[1] = uint8(((uint32(v.tmp775()) >> uint32(16)) & uint32(255)))
		tmp716[2] = uint8(((uint32(v.tmp775()) >> uint32(8)) & uint32(255)))
		tmp716[3] = uint8((uint32(v.tmp775()) & uint32(255)))
		if _, err := tmp77.Write(tmp716[:4]); err != nil {
			return err
		}
	} else if v.Prefix() == 3 {
		tmp716[0] = tmp716[0] | uint8(((uint64(v.tmp775()) >> uint64(56)) & uint64(63)))
		tmp716[1] = uint8(((uint64(v.tmp775()) >> uint64(48)) & uint64(255)))
		tmp716[2] = uint8(((uint64(v.tmp775()) >> uint64(40)) & uint64(255)))
		tmp716[3] = uint8(((uint64(v.tmp775()) >> uint64(32)) & uint64(255)))
		tmp716[4] = uint8(((uint64(v.tmp775()) >> uint64(24)) & uint64(255)))
		tmp716[5] = uint8(((uint64(v.tmp775()) >> uint64(16)) & uint64(255)))
		tmp716[6] = uint8(((uint64(v.tmp775()) >> uint64(8)) & uint64(255)))
		tmp716[7] = uint8((uint64(v.tmp775()) & uint64(255)))
		if _, err := tmp77.Write(tmp716[:8]); err != nil {
			return err
		}
	}
	return nil
}
func (s *Varint) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Varint) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (v *Varint) EncodeSlice(tmp77 []byte, tmp77Offset *int) error {
	tmp716 := []uint8{}
	if len(tmp77)-*tmp77Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"Varint::tmp404::Value\"")
	}
	tmp716 = tmp77[*tmp77Offset : *tmp77Offset+int(1)]
	tmp716[0] = uint8((v.Prefix() & 3)) << uint8(6)
	if v.Prefix() == uint8(0) {
		if len(tmp77)-*tmp77Offset < int(1) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp404::Value\"")
		}
		tmp716 = tmp77[*tmp77Offset : *tmp77Offset+int(1)]
		tmp716[0] = tmp716[0] | uint8((uint8(v.tmp775()) & 63))
		*tmp77Offset += int(1)
	} else if v.Prefix() == uint8(1) {
		if len(tmp77)-*tmp77Offset < int(2) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp404::Value\"")
		}
		tmp716 = tmp77[*tmp77Offset : *tmp77Offset+int(2)]
		tmp716[0] = tmp716[0] | uint8(((uint16(v.tmp775()) >> uint16(8)) & uint16(63)))
		tmp716[1] = uint8((uint16(v.tmp775()) & uint16(255)))
		*tmp77Offset += int(2)
	} else if v.Prefix() == 2 {
		if len(tmp77)-*tmp77Offset < int(4) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp404::Value\"")
		}
		tmp716 = tmp77[*tmp77Offset : *tmp77Offset+int(4)]
		tmp716[0] = tmp716[0] | uint8(((uint32(v.tmp775()) >> uint32(24)) & uint32(63)))
		tmp716[1] = uint8(((uint32(v.tmp775()) >> uint32(16)) & uint32(255)))
		tmp716[2] = uint8(((uint32(v.tmp775()) >> uint32(8)) & uint32(255)))
		tmp716[3] = uint8((uint32(v.tmp775()) & uint32(255)))
		*tmp77Offset += int(4)
	} else if v.Prefix() == 3 {
		if len(tmp77)-*tmp77Offset < int(8) {
			return errors.New("not enough space to reserve data for field \"Varint::tmp404::Value\"")
		}
		tmp716 = tmp77[*tmp77Offset : *tmp77Offset+int(8)]
		tmp716[0] = tmp716[0] | uint8(((uint64(v.tmp775()) >> uint64(56)) & uint64(63)))
		tmp716[1] = uint8(((uint64(v.tmp775()) >> uint64(48)) & uint64(255)))
		tmp716[2] = uint8(((uint64(v.tmp775()) >> uint64(40)) & uint64(255)))
		tmp716[3] = uint8(((uint64(v.tmp775()) >> uint64(32)) & uint64(255)))
		tmp716[4] = uint8(((uint64(v.tmp775()) >> uint64(24)) & uint64(255)))
		tmp716[5] = uint8(((uint64(v.tmp775()) >> uint64(16)) & uint64(255)))
		tmp716[6] = uint8(((uint64(v.tmp775()) >> uint64(8)) & uint64(255)))
		tmp716[7] = uint8((uint64(v.tmp775()) & uint64(255)))
		*tmp77Offset += int(8)
	}
	return nil
}
func (s *Varint) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Varint) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (v *Varint) Append(tmp77 []byte) ([]byte, error) {
	tmp716 := [8]uint8{}
	tmp716[0] = uint8((v.Prefix() & 3)) << uint8(6)
	if v.Prefix() == uint8(0) {
		tmp716[0] = tmp716[0] | uint8((uint8(v.tmp775()) & 63))
		tmp77 = append(tmp77, tmp716[:1]...)
	} else if v.Prefix() == uint8(1) {
		tmp716[0] = tmp716[0] | uint8(((uint16(v.tmp775()) >> uint16(8)) & uint16(63)))
		tmp716[1] = uint8((uint16(v.tmp775()) & uint16(255)))
		tmp77 = append(tmp77, tmp716[:2]...)
	} else if v.Prefix() == 2 {
		tmp716[0] = tmp716[0] | uint8(((uint32(v.tmp775()) >> uint32(24)) & uint32(63)))
		tmp716[1] = uint8(((uint32(v.tmp775()) >> uint32(16)) & uint32(255)))
		tmp716[2] = uint8(((uint32(v.tmp775()) >> uint32(8)) & uint32(255)))
		tmp716[3] = uint8((uint32(v.tmp775()) & uint32(255)))
		tmp77 = append(tmp77, tmp716[:4]...)
	} else if v.Prefix() == 3 {
		tmp716[0] = tmp716[0] | uint8(((uint64(v.tmp775()) >> uint64(56)) & uint64(63)))
		tmp716[1] = uint8(((uint64(v.tmp775()) >> uint64(48)) & uint64(255)))
		tmp716[2] = uint8(((uint64(v.tmp775()) >> uint64(40)) & uint64(255)))
		tmp716[3] = uint8(((uint64(v.tmp775()) >> uint64(32)) & uint64(255)))
		tmp716[4] = uint8(((uint64(v.tmp775()) >> uint64(24)) & uint64(255)))
		tmp716[5] = uint8(((uint64(v.tmp775()) >> uint64(16)) & uint64(255)))
		tmp716[6] = uint8(((uint64(v.tmp775()) >> uint64(8)) & uint64(255)))
		tmp716[7] = uint8((uint64(v.tmp775()) & uint64(255)))
		tmp77 = append(tmp77, tmp716[:8]...)
	}
	return tmp77, nil
}
func (s *Varint) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (v *Varint) Read(tmp15 io.Reader) error {
	tmp792 := [8]uint8{}
	tmp768 := uint8(0)
	if _, err := io.ReadFull(tmp15, tmp792[0:0+1]); err != nil {
		return err
	}
	tmp768 = uint8(((tmp792[0] & 192) >> uint8(6)))
	v.SetPrefix(tmp768)
	if v.Prefix() == uint8(0) {
		tmp765 := uint8(0)
		tmp765 = uint8((tmp792[0] & uint8(63)))
		v.settmp414(uint64(tmp765))
	} else if v.Prefix() == uint8(1) {
		tmp751 := uint16(0)
		if _, err := io.ReadFull(tmp15, tmp792[1:1+1]); err != nil {
			return err
		}
		tmp751 = (uint16((tmp792[0] & uint8(63))) << uint16(8)) | uint16(tmp792[1])
		v.settmp414(uint64(tmp751))
	} else if v.Prefix() == 2 {
		tmp744 := uint32(0)
		if _, err := io.ReadFull(tmp15, tmp792[1:1+3]); err != nil {
			return err
		}
		tmp744 = (((uint32((tmp792[0] & uint8(63))) << uint32(24)) | (uint32(tmp792[1]) << uint32(16))) | (uint32(tmp792[2]) << uint32(8))) | uint32(tmp792[3])
		v.settmp414(uint64(tmp744))
	} else if v.Prefix() == 3 {
		tmp747 := uint64(0)
		if _, err := io.ReadFull(tmp15, tmp792[1:1+7]); err != nil {
			return err
		}
		tmp747 = (((((((uint64((tmp792[0] & uint8(63))) << uint64(56)) | (uint64(tmp792[1]) << uint64(48))) | (uint64(tmp792[2]) << uint64(40))) | (uint64(tmp792[3]) << uint64(32))) | (uint64(tmp792[4]) << uint64(24))) | (uint64(tmp792[5]) << uint64(16))) | (uint64(tmp792[6]) << uint64(8))) | uint64(tmp792[7])
		v.settmp414(uint64(tmp747))
	}
	return nil
}
func (s *Varint) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Varint) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (v *Varint) DecodeSlice(tmp15 []byte, tmp15Offset *int) error {
	tmp792 := []uint8{}
	tmp768 := uint8(0)
	if len(tmp15)-*tmp15Offset < 1 {
		return errors.New("not enough data to read for field \"Varint::Prefix\"")
	}
	tmp792 = tmp15[*tmp15Offset : *tmp15Offset+1]
	*tmp15Offset += int(1)
	tmp768 = uint8(((tmp792[0] & 192) >> uint8(6)))
	v.SetPrefix(tmp768)
	if v.Prefix() == uint8(0) {
		tmp765 := uint8(0)
		tmp765 = uint8((tmp792[0] & uint8(63)))
		v.settmp414(uint64(tmp765))
	} else if v.Prefix() == uint8(1) {
		tmp751 := uint16(0)
		if len(tmp15)-*tmp15Offset < 1 {
			return errors.New("not enough data to read for field \"Varint::tmp404::Value\"")
		}
		tmp792 = tmp792[:1+1]
		*tmp15Offset += int(1)
		tmp751 = (uint16((tmp792[0] & uint8(63))) << uint16(8)) | uint16(tmp792[1])
		v.settmp414(uint64(tmp751))
	} else if v.Prefix() == 2 {
		tmp744 := uint32(0)
		if len(tmp15)-*tmp15Offset < 3 {
			return errors.New("not enough data to read for field \"Varint::tmp404::Value\"")
		}
		tmp792 = tmp792[:1+3]
		*tmp15Offset += int(3)
		tmp744 = (((uint32((tmp792[0] & uint8(63))) << uint32(24)) | (uint32(tmp792[1]) << uint32(16))) | (uint32(tmp792[2]) << uint32(8))) | uint32(tmp792[3])
		v.settmp414(uint64(tmp744))
	} else if v.Prefix() == 3 {
		tmp747 := uint64(0)
		if len(tmp15)-*tmp15Offset < 7 {
			return errors.New("not enough data to read for field \"Varint::tmp404::Value\"")
		}
		tmp792 = tmp792[:1+7]
		*tmp15Offset += int(7)
		tmp747 = (((((((uint64((tmp792[0] & uint8(63))) << uint64(56)) | (uint64(tmp792[1]) << uint64(48))) | (uint64(tmp792[2]) << uint64(40))) | (uint64(tmp792[3]) << uint64(32))) | (uint64(tmp792[4]) << uint64(24))) | (uint64(tmp792[5]) << uint64(16))) | (uint64(tmp792[6]) << uint64(8))) | uint64(tmp792[7])
		v.settmp414(uint64(tmp747))
	}
	return nil
}
func (s *Varint) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Varint) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func VarintLen(Value uint64) uint8 {
	tmp89 := uint8(0)
	if (uint64(0) <= Value) && (Value <= 63) {
		tmp89 = 1
	} else if (uint64(64) <= Value) && (Value <= 16383) {
		tmp89 = 2
	} else if (uint64(16384) <= Value) && (Value <= 1073741823) {
		tmp89 = 4
	} else if (1073741824 <= Value) && (Value <= 4611686018427387903) {
		tmp89 = 8
	} else {
		tmp89 = 0
	}
	return tmp89
}
func VarintPrefix(Value uint64) uint8 {
	Len := VarintLen(Value)
	tmp174 := uint8(0)
	if Len == uint8(1) {
		tmp174 = 0
	} else if Len == uint8(2) {
		tmp174 = 1
	} else if Len == uint8(4) {
		tmp174 = 2
	} else if Len == uint8(8) {
		tmp174 = 3
	} else {
		tmp174 = 255
	}
	return tmp174
}
func (v *StreamPacket) HasId() bool {
	intVal := v.hasId()
	return intVal != 0
}
func (s *StreamPacket) hasId() uint8 {
	return uint8(((s.tmp47 >> uint8(7)) & uint8(1)))
}

func (s *StreamPacket) SetHasId(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setHasId(intVal)
}
func (s *StreamPacket) setHasId(tmp614 uint8) bool {
	s.tmp47 = (s.tmp47 & (^(uint8(1) << uint8(7)))) | ((uint8(tmp614) & uint8(1)) << uint8(7))
	return true
}

func (s *StreamPacket) HasOffset() bool {
	intVal := s.hasOffset()
	return intVal != 0
}
func (s *StreamPacket) hasOffset() uint8 {
	return uint8(((s.tmp47 >> uint8(6)) & uint8(1)))
}

func (s *StreamPacket) SetHasOffset(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setHasOffset(intVal)
}
func (s *StreamPacket) setHasOffset(tmp611 uint8) bool {
	s.tmp47 = (s.tmp47 & (^(uint8(1) << uint8(6)))) | ((uint8(tmp611) & uint8(1)) << uint8(6))
	return true
}

func (s *StreamPacket) IsEof() bool {
	intVal := s.isEof()
	return intVal != 0
}
func (s *StreamPacket) isEof() uint8 {
	return uint8(((s.tmp47 >> uint8(5)) & uint8(1)))
}

func (s *StreamPacket) SetIsEof(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setIsEof(intVal)
}
func (s *StreamPacket) setIsEof(tmp608 uint8) bool {
	s.tmp47 = (s.tmp47 & (^(uint8(1) << uint8(5)))) | ((uint8(tmp608) & uint8(1)) << uint8(5))
	return true
}

func (s *StreamPacket) IsProbe() bool {
	intVal := s.isProbe()
	return intVal != 0
}
func (s *StreamPacket) isProbe() uint8 {
	return uint8(((s.tmp47 >> uint8(4)) & uint8(1)))
}

func (s *StreamPacket) SetIsProbe(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return s.setIsProbe(intVal)
}
func (s *StreamPacket) setIsProbe(tmp604 uint8) bool {
	s.tmp47 = (s.tmp47 & (^(uint8(1) << uint8(4)))) | ((uint8(tmp604) & uint8(1)) << uint8(4))
	return true
}

func (s *StreamPacket) Reserved() uint8 {
	return uint8(((s.tmp47 >> uint8(0)) & uint8(15)))
}

func (s *StreamPacket) SetReserved(tmp597 uint8) bool {
	s.tmp47 = (s.tmp47 & (^(uint8(15) << uint8(0)))) | ((uint8(tmp597) & uint8(15)) << uint8(0))
	return true
}

type tmp766 struct {
	Id Varint
}

type Variant301 struct {
	tmp766 tmp766
}

type tmp615 struct {
	Offset Varint
}

type Variant278 struct {
	tmp615 tmp615
}

type StreamPacket struct {
	tmp47  uint8
	tmp407 Variant301
	tmp376 Variant278
	Data   []uint8
}

func (s *StreamPacket) Id() *Varint {
	if s.hasId() == 1 {
		return &s.tmp407.tmp766.Id
	}
	return nil
}
func (s *StreamPacket) SetId(tmp592 Varint) bool {
	if s.hasId() == 1 {
		s.tmp407.tmp766.Id = tmp592
		return true
	}
	return false
}

func (s *StreamPacket) Offset() *Varint {
	if s.hasOffset() == 1 {
		return &s.tmp376.tmp615.Offset
	}
	return nil
}
func (s *StreamPacket) SetOffset(tmp584 Varint) bool {
	if s.hasOffset() == 1 {
		s.tmp376.tmp615.Offset = tmp584
		return true
	}
	return false
}

func (s *StreamPacket) Write(tmp56 io.Writer) error {
	tmp56ByteIO, _ := tmp56.(io.ByteWriter)
	_ = tmp56ByteIO
	/* config.go.union("noheap")*/
	tmp682 := [1]uint8{}
	tmp682[0] = uint8((s.hasId() & 1)) << uint8(7)
	tmp682[0] = tmp682[0] | (uint8((s.hasOffset() & 1)) << uint8(6))
	tmp682[0] = tmp682[0] | (uint8((s.isEof() & 1)) << uint8(5))
	tmp682[0] = tmp682[0] | (uint8((s.isProbe() & 1)) << uint8(4))
	tmp682[0] = tmp682[0] | uint8((s.Reserved() & 15))
	if tmp56ByteIO != nil {
		if err := tmp56ByteIO.WriteByte(tmp682[0]); err != nil {
			return err
		}
	} else {
		if _, err := tmp56.Write([]byte{tmp682[0]}); err != nil {
			return err
		}
	}
	if s.hasId() == 1 {
		tmp607 := s.tmp407.tmp766.Id.Write(tmp56)
		if tmp607 != nil {
			return tmp607
		}
	}
	if s.hasOffset() == 1 {
		tmp603 := s.tmp376.tmp615.Offset.Write(tmp56)
		if tmp603 != nil {
			return tmp603
		}
	}
	if _, err := tmp56.Write(s.Data); err != nil {
		return err
	}
	return nil
}
func (s *StreamPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *StreamPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamPacket) EncodeSlice(tmp56 []byte, tmp56Offset *int) error {
	/* config.go.union("noheap")*/
	tmp682 := []uint8{}
	if len(tmp56)-*tmp56Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"StreamPacket::Reserved\"")
	}
	tmp682 = tmp56[*tmp56Offset : *tmp56Offset+int(1)]
	tmp682[0] = uint8((s.hasId() & 1)) << uint8(7)
	tmp682[0] = tmp682[0] | (uint8((s.hasOffset() & 1)) << uint8(6))
	tmp682[0] = tmp682[0] | (uint8((s.isEof() & 1)) << uint8(5))
	tmp682[0] = tmp682[0] | (uint8((s.isProbe() & 1)) << uint8(4))
	tmp682[0] = tmp682[0] | uint8((s.Reserved() & 15))
	*tmp56Offset += int(1)
	if s.hasId() == 1 {
		tmp607 := s.tmp407.tmp766.Id.EncodeSlice(tmp56, tmp56Offset)
		if tmp607 != nil {
			return tmp607
		}
	}
	if s.hasOffset() == 1 {
		tmp603 := s.tmp376.tmp615.Offset.EncodeSlice(tmp56, tmp56Offset)
		if tmp603 != nil {
			return tmp603
		}
	}
	if len(tmp56)-*tmp56Offset < int(0+len(s.Data)) {
		return errors.New("not enough space to write for field \"StreamPacket::Data\"")
	}
	copy(tmp56[*tmp56Offset:*tmp56Offset+int(len(s.Data))], s.Data)
	*tmp56Offset += int(len(s.Data))
	return nil
}
func (s *StreamPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *StreamPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamPacket) Append(tmp56 []byte) ([]byte, error) {
	/* config.go.union("noheap")*/
	tmp682 := [1]uint8{}
	tmp682[0] = uint8((s.hasId() & 1)) << uint8(7)
	tmp682[0] = tmp682[0] | (uint8((s.hasOffset() & 1)) << uint8(6))
	tmp682[0] = tmp682[0] | (uint8((s.isEof() & 1)) << uint8(5))
	tmp682[0] = tmp682[0] | (uint8((s.isProbe() & 1)) << uint8(4))
	tmp682[0] = tmp682[0] | uint8((s.Reserved() & 15))
	tmp56 = append(tmp56, tmp682[:1]...)
	if s.hasId() == 1 {
		var tmp607 error
		tmp56, tmp607 = s.tmp407.tmp766.Id.Append(tmp56)

		if tmp607 != nil {
			return nil, tmp607
		}
	}
	if s.hasOffset() == 1 {
		var tmp603 error
		tmp56, tmp603 = s.tmp376.tmp615.Offset.Append(tmp56)

		if tmp603 != nil {
			return nil, tmp603
		}
	}
	tmp56 = append(tmp56, s.Data...)
	return tmp56, nil
}
func (s *StreamPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *StreamPacket) Read(tmp41 io.Reader) error {
	tmp41ByteIO, _ := tmp41.(io.ByteReader)
	_ = tmp41ByteIO
	/* config.go.union("noheap")*/
	tmp721 := [1]uint8{}
	if tmp41ByteIO != nil {
		var err error
		tmp721[0], err = tmp41ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp41, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"tmp273\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp721[0] = buf[0]
	}
	tmp219 := uint8(0)
	tmp219 = uint8(((tmp721[0] & 128) >> uint8(7)))
	s.setHasId(tmp219)
	tmp787 := uint8(0)
	tmp787 = uint8(((tmp721[0] & uint8(64)) >> uint8(6)))
	s.setHasOffset(tmp787)
	tmp690 := uint8(0)
	tmp690 = uint8(((tmp721[0] & uint8(32)) >> uint8(5)))
	s.setIsEof(tmp690)
	tmp678 := uint8(0)
	tmp678 = uint8(((tmp721[0] & uint8(16)) >> uint8(4)))
	s.setIsProbe(tmp678)
	tmp715 := uint8(0)
	tmp715 = uint8((tmp721[0] & uint8(15)))
	s.SetReserved(tmp715)
	if s.hasId() == 1 {
		tmp599 := s.tmp407.tmp766.Id.Read(tmp41)
		if tmp599 != nil {
			return tmp599
		}
	}
	if s.hasOffset() == 1 {
		tmp788 := s.tmp376.tmp615.Offset.Read(tmp41)
		if tmp788 != nil {
			return tmp788
		}
	}
	{
		var readErr error
		s.Data, readErr = io.ReadAll(tmp41)
		if readErr != nil {
			return readErr
		}
	}
	return nil
}
func (s *StreamPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *StreamPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *StreamPacket) DecodeSlice(tmp41 []byte, tmp41Offset *int) error {
	/* config.go.union("noheap")*/
	tmp721 := []uint8{}
	if len(tmp41)-*tmp41Offset < 1 {
		return errors.New("not enough data to read for field \"tmp273\"")
	}
	tmp721 = tmp41[*tmp41Offset : *tmp41Offset+1]
	*tmp41Offset += int(1)
	tmp219 := uint8(0)
	tmp219 = uint8(((tmp721[0] & 128) >> uint8(7)))
	s.setHasId(tmp219)
	tmp787 := uint8(0)
	tmp787 = uint8(((tmp721[0] & uint8(64)) >> uint8(6)))
	s.setHasOffset(tmp787)
	tmp690 := uint8(0)
	tmp690 = uint8(((tmp721[0] & uint8(32)) >> uint8(5)))
	s.setIsEof(tmp690)
	tmp678 := uint8(0)
	tmp678 = uint8(((tmp721[0] & uint8(16)) >> uint8(4)))
	s.setIsProbe(tmp678)
	tmp715 := uint8(0)
	tmp715 = uint8((tmp721[0] & uint8(15)))
	s.SetReserved(tmp715)
	if s.hasId() == 1 {
		tmp599 := s.tmp407.tmp766.Id.DecodeSlice(tmp41, tmp41Offset)
		if tmp599 != nil {
			return tmp599
		}
	}
	if s.hasOffset() == 1 {
		tmp788 := s.tmp376.tmp615.Offset.DecodeSlice(tmp41, tmp41Offset)
		if tmp788 != nil {
			return tmp788
		}
	}
	s.Data = tmp41[*tmp41Offset:]
	*tmp41Offset += len(s.Data)
	return nil
}
func (s *StreamPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *StreamPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type ACKRange struct {
	Offset Varint
	Delta  Varint
}

func (a *ACKRange) Write(tmp290 io.Writer) error {
	tmp650 := a.Offset.Write(tmp290)
	if tmp650 != nil {
		return tmp650
	}
	tmp642 := a.Delta.Write(tmp290)
	if tmp642 != nil {
		return tmp642
	}
	return nil
}
func (s *ACKRange) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *ACKRange) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (a *ACKRange) EncodeSlice(tmp290 []byte, tmp290Offset *int) error {
	tmp650 := a.Offset.EncodeSlice(tmp290, tmp290Offset)
	if tmp650 != nil {
		return tmp650
	}
	tmp642 := a.Delta.EncodeSlice(tmp290, tmp290Offset)
	if tmp642 != nil {
		return tmp642
	}
	return nil
}
func (s *ACKRange) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *ACKRange) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (a *ACKRange) Append(tmp290 []byte) ([]byte, error) {
	var tmp650 error
	tmp290, tmp650 = a.Offset.Append(tmp290)

	if tmp650 != nil {
		return nil, tmp650
	}
	var tmp642 error
	tmp290, tmp642 = a.Delta.Append(tmp290)

	if tmp642 != nil {
		return nil, tmp642
	}
	return tmp290, nil
}
func (s *ACKRange) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (a *ACKRange) Read(tmp288 io.Reader) error {
	tmp645 := a.Offset.Read(tmp288)
	if tmp645 != nil {
		return tmp645
	}
	tmp637 := a.Delta.Read(tmp288)
	if tmp637 != nil {
		return tmp637
	}
	return nil
}
func (s *ACKRange) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *ACKRange) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (a *ACKRange) DecodeSlice(tmp288 []byte, tmp288Offset *int) error {
	tmp645 := a.Offset.DecodeSlice(tmp288, tmp288Offset)
	if tmp645 != nil {
		return tmp645
	}
	tmp637 := a.Delta.DecodeSlice(tmp288, tmp288Offset)
	if tmp637 != nil {
		return tmp637
	}
	return nil
}
func (s *ACKRange) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *ACKRange) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type StreamACKPacket struct {
	LargestAck Varint
	FirstDelta Varint
	Len        Varint
	Ranges     []ACKRange
}

func (s *StreamACKPacket) Write(tmp133 io.Writer) error {
	tmp624 := s.LargestAck.Write(tmp133)
	if tmp624 != nil {
		return tmp624
	}
	tmp627 := s.FirstDelta.Write(tmp133)
	if tmp627 != nil {
		return tmp627
	}
	tmp664 := s.Len.Write(tmp133)
	if tmp664 != nil {
		return tmp664
	}
	if len(s.Ranges) != int(int(s.Len.Value())) {
		return fmt.Errorf("size mismatch when writing field \"StreamACKPacket::Ranges\": expected %d, got %d", int(int(s.Len.Value())), len(s.Ranges))
	}
	tmp291 := int(0)
	for tmp291 < int(s.Len.Value()) {
		tmp655 := s.Ranges[tmp291].Write(tmp133)
		if tmp655 != nil {
			return tmp655
		}
		tmp291 = tmp291 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *StreamACKPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamACKPacket) EncodeSlice(tmp133 []byte, tmp133Offset *int) error {
	tmp624 := s.LargestAck.EncodeSlice(tmp133, tmp133Offset)
	if tmp624 != nil {
		return tmp624
	}
	tmp627 := s.FirstDelta.EncodeSlice(tmp133, tmp133Offset)
	if tmp627 != nil {
		return tmp627
	}
	tmp664 := s.Len.EncodeSlice(tmp133, tmp133Offset)
	if tmp664 != nil {
		return tmp664
	}
	if len(s.Ranges) != int(int(s.Len.Value())) {
		return fmt.Errorf("size mismatch when writing field \"StreamACKPacket::Ranges\": expected %d, got %d", int(int(s.Len.Value())), len(s.Ranges))
	}
	tmp291 := int(0)
	for tmp291 < int(s.Len.Value()) {
		tmp655 := s.Ranges[tmp291].EncodeSlice(tmp133, tmp133Offset)
		if tmp655 != nil {
			return tmp655
		}
		tmp291 = tmp291 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *StreamACKPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamACKPacket) Append(tmp133 []byte) ([]byte, error) {
	var tmp624 error
	tmp133, tmp624 = s.LargestAck.Append(tmp133)

	if tmp624 != nil {
		return nil, tmp624
	}
	var tmp627 error
	tmp133, tmp627 = s.FirstDelta.Append(tmp133)

	if tmp627 != nil {
		return nil, tmp627
	}
	var tmp664 error
	tmp133, tmp664 = s.Len.Append(tmp133)

	if tmp664 != nil {
		return nil, tmp664
	}
	if len(s.Ranges) != int(int(s.Len.Value())) {
		return nil, fmt.Errorf("size mismatch when writing field \"StreamACKPacket::Ranges\": expected %d, got %d", int(int(s.Len.Value())), len(s.Ranges))
	}
	tmp291 := int(0)
	for tmp291 < int(s.Len.Value()) {
		var tmp655 error
		tmp133, tmp655 = s.Ranges[tmp291].Append(tmp133)

		if tmp655 != nil {
			return nil, tmp655
		}
		tmp291 = tmp291 + int(1)
	}
	return tmp133, nil
}
func (s *StreamACKPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *StreamACKPacket) Read(tmp132 io.Reader) error {
	tmp667 := s.LargestAck.Read(tmp132)
	if tmp667 != nil {
		return tmp667
	}
	tmp593 := s.FirstDelta.Read(tmp132)
	if tmp593 != nil {
		return tmp593
	}
	tmp587 := s.Len.Read(tmp132)
	if tmp587 != nil {
		return tmp587
	}
	tmp357 := int(0)
	for tmp357 < int(s.Len.Value()) {
		tmp590 := ACKRange{}
		tmp579 := tmp590.Read(tmp132)
		if tmp579 != nil {
			return tmp579
		}
		s.Ranges = append(s.Ranges, tmp590)
		tmp357 = tmp357 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *StreamACKPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *StreamACKPacket) DecodeSlice(tmp132 []byte, tmp132Offset *int) error {
	tmp667 := s.LargestAck.DecodeSlice(tmp132, tmp132Offset)
	if tmp667 != nil {
		return tmp667
	}
	tmp593 := s.FirstDelta.DecodeSlice(tmp132, tmp132Offset)
	if tmp593 != nil {
		return tmp593
	}
	tmp587 := s.Len.DecodeSlice(tmp132, tmp132Offset)
	if tmp587 != nil {
		return tmp587
	}
	tmp357 := int(0)
	for tmp357 < int(s.Len.Value()) {
		tmp590 := ACKRange{}
		tmp579 := tmp590.DecodeSlice(tmp132, tmp132Offset)
		if tmp579 != nil {
			return tmp579
		}
		s.Ranges = append(s.Ranges, tmp590)
		tmp357 = tmp357 + int(1)
	}
	return nil
}
func (s *StreamACKPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *StreamACKPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type UpdateWindow struct {
	Id        Varint
	WindowMax Varint
}

func (u *UpdateWindow) Write(tmp263 io.Writer) error {
	tmp569 := u.Id.Write(tmp263)
	if tmp569 != nil {
		return tmp569
	}
	tmp567 := u.WindowMax.Write(tmp263)
	if tmp567 != nil {
		return tmp567
	}
	return nil
}
func (s *UpdateWindow) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *UpdateWindow) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (u *UpdateWindow) EncodeSlice(tmp263 []byte, tmp263Offset *int) error {
	tmp569 := u.Id.EncodeSlice(tmp263, tmp263Offset)
	if tmp569 != nil {
		return tmp569
	}
	tmp567 := u.WindowMax.EncodeSlice(tmp263, tmp263Offset)
	if tmp567 != nil {
		return tmp567
	}
	return nil
}
func (s *UpdateWindow) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *UpdateWindow) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (u *UpdateWindow) Append(tmp263 []byte) ([]byte, error) {
	var tmp569 error
	tmp263, tmp569 = u.Id.Append(tmp263)

	if tmp569 != nil {
		return nil, tmp569
	}
	var tmp567 error
	tmp263, tmp567 = u.WindowMax.Append(tmp263)

	if tmp567 != nil {
		return nil, tmp567
	}
	return tmp263, nil
}
func (s *UpdateWindow) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (u *UpdateWindow) Read(tmp265 io.Reader) error {
	tmp574 := u.Id.Read(tmp265)
	if tmp574 != nil {
		return tmp574
	}
	tmp572 := u.WindowMax.Read(tmp265)
	if tmp572 != nil {
		return tmp572
	}
	return nil
}
func (s *UpdateWindow) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *UpdateWindow) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (u *UpdateWindow) DecodeSlice(tmp265 []byte, tmp265Offset *int) error {
	tmp574 := u.Id.DecodeSlice(tmp265, tmp265Offset)
	if tmp574 != nil {
		return tmp574
	}
	tmp572 := u.WindowMax.DecodeSlice(tmp265, tmp265Offset)
	if tmp572 != nil {
		return tmp572
	}
	return nil
}
func (s *UpdateWindow) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *UpdateWindow) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type CancelStreamPacket struct {
	Id Varint
}

func (c *CancelStreamPacket) Write(tmp354 io.Writer) error {
	tmp563 := c.Id.Write(tmp354)
	if tmp563 != nil {
		return tmp563
	}
	return nil
}
func (s *CancelStreamPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *CancelStreamPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *CancelStreamPacket) EncodeSlice(tmp354 []byte, tmp354Offset *int) error {
	tmp563 := c.Id.EncodeSlice(tmp354, tmp354Offset)
	if tmp563 != nil {
		return tmp563
	}
	return nil
}
func (s *CancelStreamPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *CancelStreamPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *CancelStreamPacket) Append(tmp354 []byte) ([]byte, error) {
	var tmp563 error
	tmp354, tmp563 = c.Id.Append(tmp354)

	if tmp563 != nil {
		return nil, tmp563
	}
	return tmp354, nil
}
func (s *CancelStreamPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (c *CancelStreamPacket) Read(tmp355 io.Reader) error {
	tmp565 := c.Id.Read(tmp355)
	if tmp565 != nil {
		return tmp565
	}
	return nil
}
func (s *CancelStreamPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *CancelStreamPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (c *CancelStreamPacket) DecodeSlice(tmp355 []byte, tmp355Offset *int) error {
	tmp565 := c.Id.DecodeSlice(tmp355, tmp355Offset)
	if tmp565 != nil {
		return tmp565
	}
	return nil
}
func (s *CancelStreamPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *CancelStreamPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type CloseStatus uint8

const (
	CloseStatus_Ok     CloseStatus = 0
	CloseStatus_Failed CloseStatus = 1
)

func (e CloseStatus) String() string {
	switch e {
	case CloseStatus_Ok:
		return "Ok"
	case CloseStatus_Failed:
		return "Failed"
	default:
		return fmt.Sprintf("CloseStatus(%d)", e)
	}
}

type PingBody struct {
	Nanos uint64
}

func (p *PingBody) Write(tmp350 io.Writer) error {
	tmp400 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp400[:], uint64(p.Nanos))
	if _, err := tmp350.Write(tmp400[:8]); err != nil {
		return err
	}
	return nil
}
func (s *PingBody) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PingBody) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PingBody) EncodeSlice(tmp350 []byte, tmp350Offset *int) error {
	tmp400 := []uint8{}
	if len(tmp350)-*tmp350Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"PingBody::Nanos\"")
	}
	tmp400 = tmp350[*tmp350Offset : *tmp350Offset+int(8)]
	binary.BigEndian.PutUint64(tmp400[:], uint64(p.Nanos))
	*tmp350Offset += int(8)
	return nil
}
func (s *PingBody) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PingBody) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PingBody) Append(tmp350 []byte) ([]byte, error) {
	tmp400 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp400[:], uint64(p.Nanos))
	tmp350 = append(tmp350, tmp400[:8]...)
	return tmp350, nil
}
func (s *PingBody) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PingBody) Read(tmp352 io.Reader) error {
	tmp419 := [8]uint8{}
	if _, err := io.ReadFull(tmp352, tmp419[0:0+8]); err != nil {
		return err
	}
	p.Nanos = binary.BigEndian.Uint64(tmp419[:])
	return nil
}
func (s *PingBody) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PingBody) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PingBody) DecodeSlice(tmp352 []byte, tmp352Offset *int) error {
	tmp419 := []uint8{}
	if len(tmp352)-*tmp352Offset < 8 {
		return errors.New("not enough data to read for field \"PingBody::Nanos\"")
	}
	tmp419 = tmp352[*tmp352Offset : *tmp352Offset+8]
	*tmp352Offset += int(8)
	p.Nanos = binary.BigEndian.Uint64(tmp419[:])
	return nil
}
func (s *PingBody) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PingBody) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type CloseBody struct {
	Status     CloseStatus
	MessageLen uint16
	Message    []uint8
}

func (c *CloseBody) SetMessage(tmp539 []uint8) bool {
	if len(tmp539) > int(65535) {
		return false
	}
	c.MessageLen = uint16(len(tmp539))
	c.Message = tmp539
	return true
}

func (c *CloseBody) Write(tmp104 io.Writer) error {
	tmp272 := [1]uint8{}
	tmp272[0] = uint8(c.Status)
	if _, err := tmp104.Write(tmp272[:1]); err != nil {
		return err
	}
	tmp544 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp544[:], uint16(c.MessageLen))
	if _, err := tmp104.Write(tmp544[:2]); err != nil {
		return err
	}
	if len(c.Message) != int(int(c.MessageLen)) {
		return fmt.Errorf("size mismatch when writing field \"CloseBody::Message\": expected %d, got %d", int(int(c.MessageLen)), len(c.Message))
	}
	if _, err := tmp104.Write(c.Message); err != nil {
		return err
	}
	return nil
}
func (s *CloseBody) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *CloseBody) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *CloseBody) EncodeSlice(tmp104 []byte, tmp104Offset *int) error {
	tmp272 := []uint8{}
	if len(tmp104)-*tmp104Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"CloseBody::Status\"")
	}
	tmp272 = tmp104[*tmp104Offset : *tmp104Offset+int(1)]
	tmp272[0] = uint8(c.Status)
	*tmp104Offset += int(1)
	tmp544 := []uint8{}
	if len(tmp104)-*tmp104Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"CloseBody::MessageLen\"")
	}
	tmp544 = tmp104[*tmp104Offset : *tmp104Offset+int(2)]
	binary.BigEndian.PutUint16(tmp544[:], uint16(c.MessageLen))
	*tmp104Offset += int(2)
	if len(c.Message) != int(int(c.MessageLen)) {
		return fmt.Errorf("size mismatch when writing field \"CloseBody::Message\": expected %d, got %d", int(int(c.MessageLen)), len(c.Message))
	}
	if len(tmp104)-*tmp104Offset < int(0+int(c.MessageLen)) {
		return errors.New("not enough space to write for field \"CloseBody::Message\"")
	}
	copy(tmp104[*tmp104Offset:*tmp104Offset+int(int(c.MessageLen))], c.Message)
	*tmp104Offset += int(int(c.MessageLen))
	return nil
}
func (s *CloseBody) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *CloseBody) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (c *CloseBody) Append(tmp104 []byte) ([]byte, error) {
	tmp272 := [1]uint8{}
	tmp272[0] = uint8(c.Status)
	tmp104 = append(tmp104, tmp272[:1]...)
	tmp544 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp544[:], uint16(c.MessageLen))
	tmp104 = append(tmp104, tmp544[:2]...)
	if len(c.Message) != int(int(c.MessageLen)) {
		return nil, fmt.Errorf("size mismatch when writing field \"CloseBody::Message\": expected %d, got %d", int(int(c.MessageLen)), len(c.Message))
	}
	tmp104 = append(tmp104, c.Message...)
	return tmp104, nil
}
func (s *CloseBody) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (c *CloseBody) Read(tmp105 io.Reader) error {
	tmp552 := uint8(0)
	tmp38 := [1]uint8{}
	if _, err := io.ReadFull(tmp105, tmp38[0:0+1]); err != nil {
		return err
	}
	tmp552 = tmp38[0]
	c.Status = CloseStatus(tmp552)
	tmp550 := [2]uint8{}
	if _, err := io.ReadFull(tmp105, tmp550[0:0+2]); err != nil {
		return err
	}
	c.MessageLen = binary.BigEndian.Uint16(tmp550[:])
	if seeker, ok := tmp105.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(c.MessageLen)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(c.MessageLen)))
		}
		c.Message = make([]byte, int(c.MessageLen))
		if _, err := io.ReadFull(tmp105, c.Message[0:0+int(c.MessageLen)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_1223 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_1223, tmp105, int64(int(c.MessageLen))); err != nil {
			return err
		}
		c.Message = io_temp_1223.Bytes()
	}
	return nil
}
func (s *CloseBody) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *CloseBody) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (c *CloseBody) DecodeSlice(tmp105 []byte, tmp105Offset *int) error {
	tmp552 := uint8(0)
	tmp38 := []uint8{}
	if len(tmp105)-*tmp105Offset < 1 {
		return errors.New("not enough data to read for field \"CloseBody::Status\"")
	}
	tmp38 = tmp105[*tmp105Offset : *tmp105Offset+1]
	*tmp105Offset += int(1)
	tmp552 = tmp38[0]
	c.Status = CloseStatus(tmp552)
	tmp550 := []uint8{}
	if len(tmp105)-*tmp105Offset < 2 {
		return errors.New("not enough data to read for field \"CloseBody::MessageLen\"")
	}
	tmp550 = tmp105[*tmp105Offset : *tmp105Offset+2]
	*tmp105Offset += int(2)
	c.MessageLen = binary.BigEndian.Uint16(tmp550[:])
	if len(tmp105)-*tmp105Offset < int(c.MessageLen) {
		return errors.New("not enough data to read for field \"CloseBody::Message\"")
	}
	c.Message = tmp105[*tmp105Offset : *tmp105Offset+int(c.MessageLen)]
	*tmp105Offset += int(int(c.MessageLen))
	return nil
}
func (s *CloseBody) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *CloseBody) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

const USER_DEFINED_START = uint8(64)

type ApplicationPayloadKind uint8

const (
	ApplicationPayloadKind_Ping               ApplicationPayloadKind = 0
	ApplicationPayloadKind_Pong               ApplicationPayloadKind = 1
	ApplicationPayloadKind_Close              ApplicationPayloadKind = 2
	ApplicationPayloadKind_StreamData         ApplicationPayloadKind = 3
	ApplicationPayloadKind_StreamCancel       ApplicationPayloadKind = 4
	ApplicationPayloadKind_StreamAck          ApplicationPayloadKind = 5
	ApplicationPayloadKind_StreamWindowUpdate ApplicationPayloadKind = 6
)

func (e ApplicationPayloadKind) String() string {
	switch e {
	case ApplicationPayloadKind_Ping:
		return "Ping"
	case ApplicationPayloadKind_Pong:
		return "Pong"
	case ApplicationPayloadKind_Close:
		return "Close"
	case ApplicationPayloadKind_StreamData:
		return "StreamData"
	case ApplicationPayloadKind_StreamCancel:
		return "StreamCancel"
	case ApplicationPayloadKind_StreamAck:
		return "StreamAck"
	case ApplicationPayloadKind_StreamWindowUpdate:
		return "StreamWindowUpdate"
	default:
		return fmt.Sprintf("ApplicationPayloadKind(%d)", e)
	}
}

type PacketHeader struct {
	Kind ApplicationPayloadKind
}

func (p *PacketHeader) Write(tmp247 io.Writer) error {
	tmp247ByteIO, _ := tmp247.(io.ByteWriter)
	_ = tmp247ByteIO
	if tmp247ByteIO != nil {
		if err := tmp247ByteIO.WriteByte(uint8(p.Kind)); err != nil {
			return err
		}
	} else {
		if _, err := tmp247.Write([]byte{uint8(p.Kind)}); err != nil {
			return err
		}
	}
	return nil
}
func (s *PacketHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PacketHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) EncodeSlice(tmp247 []byte, tmp247Offset *int) error {
	tmp529 := []uint8{}
	if len(tmp247)-*tmp247Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::Kind\"")
	}
	tmp529 = tmp247[*tmp247Offset : *tmp247Offset+int(1)]
	tmp529[0] = uint8(p.Kind)
	*tmp247Offset += int(1)
	return nil
}
func (s *PacketHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PacketHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) Append(tmp247 []byte) ([]byte, error) {
	tmp529 := [1]uint8{}
	tmp529[0] = uint8(p.Kind)
	tmp247 = append(tmp247, tmp529[:1]...)
	return tmp247, nil
}
func (s *PacketHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PacketHeader) Read(tmp250 io.Reader) error {
	tmp250ByteIO, _ := tmp250.(io.ByteReader)
	_ = tmp250ByteIO
	tmp534 := uint8(0)
	if tmp250ByteIO != nil {
		var err error
		tmp534, err = tmp250ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp250, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"PacketHeader::Kind\": expected to read 1 byte, but read %d bytes", n)
		}
		tmp534 = buf[0]
	}
	p.Kind = ApplicationPayloadKind(tmp534)
	return nil
}
func (s *PacketHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PacketHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PacketHeader) DecodeSlice(tmp250 []byte, tmp250Offset *int) error {
	tmp534 := uint8(0)
	tmp533 := []uint8{}
	if len(tmp250)-*tmp250Offset < 1 {
		return errors.New("not enough data to read for field \"PacketHeader::Kind\"")
	}
	tmp533 = tmp250[*tmp250Offset : *tmp250Offset+1]
	*tmp250Offset += int(1)
	tmp534 = tmp533[0]
	p.Kind = ApplicationPayloadKind(tmp534)
	return nil
}
func (s *PacketHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PacketHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func IsStreamRelated(Kind ApplicationPayloadKind) bool {
	tmp343 := false
	if (((ApplicationPayloadKind_StreamData == Kind) || (ApplicationPayloadKind_StreamCancel == Kind)) || (ApplicationPayloadKind_StreamAck == Kind)) || (ApplicationPayloadKind_StreamWindowUpdate == Kind) {
		tmp343 = true
	} else {
		tmp343 = false
	}
	return tmp343
}

type tmp518 struct {
	StreamData StreamPacket
}

type tmp516 struct {
	StreamCancel CancelStreamPacket
}

type tmp514 struct {
	StreamAck StreamACKPacket
}

type tmp512 struct {
	WindowUpdate UpdateWindow
}

type tmp1114 struct {
}

type Variant102 struct {
	tmp518  tmp518
	tmp516  tmp516
	tmp514  tmp514
	tmp512  tmp512
	tmp1114 tmp1114
}

type StreamAppPacket struct {
	Header PacketHeader
	tmp342 Variant102
}

func (s *StreamAppPacket) StreamAck() *StreamACKPacket {
	if (ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind) {
		return nil
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		return &s.tmp342.tmp514.StreamAck
	}
	return nil
}
func (s *StreamAppPacket) SetStreamAck(tmp442 StreamACKPacket) bool {
	if (ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind) {
		return false
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		s.tmp342.tmp514.StreamAck = tmp442
		return true
	}
	return false
}

func (s *StreamAppPacket) StreamCancel() *CancelStreamPacket {
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		return nil
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		return &s.tmp342.tmp516.StreamCancel
	}
	return nil
}
func (s *StreamAppPacket) SetStreamCancel(tmp439 CancelStreamPacket) bool {
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		return false
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		s.tmp342.tmp516.StreamCancel = tmp439
		return true
	}
	return false
}

func (s *StreamAppPacket) StreamData() *StreamPacket {
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		return &s.tmp342.tmp518.StreamData
	}
	return nil
}
func (s *StreamAppPacket) SetStreamData(tmp436 StreamPacket) bool {
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		s.tmp342.tmp518.StreamData = tmp436
		return true
	}
	return false
}

func (s *StreamAppPacket) WindowUpdate() *UpdateWindow {
	if ((ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind)) || (ApplicationPayloadKind_StreamAck == s.Header.Kind) {
		return nil
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		return &s.tmp342.tmp512.WindowUpdate
	}
	return nil
}
func (s *StreamAppPacket) SetWindowUpdate(tmp425 UpdateWindow) bool {
	if ((ApplicationPayloadKind_StreamData == s.Header.Kind) || (ApplicationPayloadKind_StreamCancel == s.Header.Kind)) || (ApplicationPayloadKind_StreamAck == s.Header.Kind) {
		return false
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		s.tmp342.tmp512.WindowUpdate = tmp425
		return true
	}
	return false
}

func (s *StreamAppPacket) Write(tmp120 io.Writer) error {
	tmp120ByteIO, _ := tmp120.(io.ByteWriter)
	_ = tmp120ByteIO
	/* config.go.union("noheap")*/
	tmp471 := s.Header.Write(tmp120)
	if tmp471 != nil {
		return tmp471
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp467 := s.tmp342.tmp518.StreamData.Write(tmp120)
		if tmp467 != nil {
			return tmp467
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp462 := s.tmp342.tmp516.StreamCancel.Write(tmp120)
		if tmp462 != nil {
			return tmp462
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp457 := s.tmp342.tmp514.StreamAck.Write(tmp120)
		if tmp457 != nil {
			return tmp457
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp452 := s.tmp342.tmp512.WindowUpdate.Write(tmp120)
		if tmp452 != nil {
			return tmp452
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *StreamAppPacket) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *StreamAppPacket) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamAppPacket) EncodeSlice(tmp120 []byte, tmp120Offset *int) error {
	/* config.go.union("noheap")*/
	tmp471 := s.Header.EncodeSlice(tmp120, tmp120Offset)
	if tmp471 != nil {
		return tmp471
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp467 := s.tmp342.tmp518.StreamData.EncodeSlice(tmp120, tmp120Offset)
		if tmp467 != nil {
			return tmp467
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp462 := s.tmp342.tmp516.StreamCancel.EncodeSlice(tmp120, tmp120Offset)
		if tmp462 != nil {
			return tmp462
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp457 := s.tmp342.tmp514.StreamAck.EncodeSlice(tmp120, tmp120Offset)
		if tmp457 != nil {
			return tmp457
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp452 := s.tmp342.tmp512.WindowUpdate.EncodeSlice(tmp120, tmp120Offset)
		if tmp452 != nil {
			return tmp452
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *StreamAppPacket) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *StreamAppPacket) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (s *StreamAppPacket) Append(tmp120 []byte) ([]byte, error) {
	/* config.go.union("noheap")*/
	var tmp471 error
	tmp120, tmp471 = s.Header.Append(tmp120)

	if tmp471 != nil {
		return nil, tmp471
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		var tmp467 error
		tmp120, tmp467 = s.tmp342.tmp518.StreamData.Append(tmp120)

		if tmp467 != nil {
			return nil, tmp467
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		var tmp462 error
		tmp120, tmp462 = s.tmp342.tmp516.StreamCancel.Append(tmp120)

		if tmp462 != nil {
			return nil, tmp462
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		var tmp457 error
		tmp120, tmp457 = s.tmp342.tmp514.StreamAck.Append(tmp120)

		if tmp457 != nil {
			return nil, tmp457
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		var tmp452 error
		tmp120, tmp452 = s.tmp342.tmp512.WindowUpdate.Append(tmp120)

		if tmp452 != nil {
			return nil, tmp452
		}
	} else {
		return nil, errors.New("Unexpected packet")
	}
	return tmp120, nil
}
func (s *StreamAppPacket) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (s *StreamAppPacket) Read(tmp121 io.Reader) error {
	tmp121ByteIO, _ := tmp121.(io.ByteReader)
	_ = tmp121ByteIO
	/* config.go.union("noheap")*/
	tmp502 := s.Header.Read(tmp121)
	if tmp502 != nil {
		return tmp502
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp497 := s.tmp342.tmp518.StreamData.Read(tmp121)
		if tmp497 != nil {
			return tmp497
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp491 := s.tmp342.tmp516.StreamCancel.Read(tmp121)
		if tmp491 != nil {
			return tmp491
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp485 := s.tmp342.tmp514.StreamAck.Read(tmp121)
		if tmp485 != nil {
			return tmp485
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp479 := s.tmp342.tmp512.WindowUpdate.Read(tmp121)
		if tmp479 != nil {
			return tmp479
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *StreamAppPacket) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *StreamAppPacket) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (s *StreamAppPacket) DecodeSlice(tmp121 []byte, tmp121Offset *int) error {
	/* config.go.union("noheap")*/
	tmp502 := s.Header.DecodeSlice(tmp121, tmp121Offset)
	if tmp502 != nil {
		return tmp502
	}
	if s.Header.Kind == ApplicationPayloadKind_StreamData {
		tmp497 := s.tmp342.tmp518.StreamData.DecodeSlice(tmp121, tmp121Offset)
		if tmp497 != nil {
			return tmp497
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamCancel {
		tmp491 := s.tmp342.tmp516.StreamCancel.DecodeSlice(tmp121, tmp121Offset)
		if tmp491 != nil {
			return tmp491
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamAck {
		tmp485 := s.tmp342.tmp514.StreamAck.DecodeSlice(tmp121, tmp121Offset)
		if tmp485 != nil {
			return tmp485
		}
	} else if s.Header.Kind == ApplicationPayloadKind_StreamWindowUpdate {
		tmp479 := s.tmp342.tmp512.WindowUpdate.DecodeSlice(tmp121, tmp121Offset)
		if tmp479 != nil {
			return tmp479
		}
	} else {
		return errors.New("Unexpected packet")
	}
	return nil
}
func (s *StreamAppPacket) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *StreamAppPacket) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
