// Code generated by ebm2go at https://github.com/on-keyday/brgen, DO NOT EDIT.
package packet

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("packet")*/
type IPAddress struct {
	Len     uint8
	Address []uint8
}

func (i *IPAddress) SetAddress(tmp377 []uint8) bool {
	if len(tmp377) > int(255) {
		return false
	}
	i.Len = uint8(len(tmp377))
	i.Address = tmp377
	return true
}

func (i *IPAddress) Write(tmp126 io.Writer) error {
	tmp126ByteIO, _ := tmp126.(io.ByteWriter)
	_ = tmp126ByteIO
	if tmp126ByteIO != nil {
		if err := tmp126ByteIO.WriteByte(i.Len); err != nil {
			return err
		}
	} else {
		if _, err := tmp126.Write([]byte{i.Len}); err != nil {
			return err
		}
	}
	if !((i.Len == 4) || (i.Len == 16)) {
		return errors.New("Assertion failed")
	}
	if len(i.Address) != int(int(i.Len)) {
		return fmt.Errorf("size mismatch when writing field \"IPAddress::Address\": expected %d, got %d", int(int(i.Len)), len(i.Address))
	}
	if _, err := tmp126.Write(i.Address); err != nil {
		return err
	}
	return nil
}
func (s *IPAddress) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *IPAddress) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (i *IPAddress) EncodeSlice(tmp126 []byte, tmp126Offset *int) error {
	tmp182 := []uint8{}
	if len(tmp126)-*tmp126Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"IPAddress::Len\"")
	}
	tmp182 = tmp126[*tmp126Offset : *tmp126Offset+int(1)]
	tmp182[0] = i.Len
	*tmp126Offset += int(1)
	if !((i.Len == 4) || (i.Len == 16)) {
		return errors.New("Assertion failed")
	}
	if len(i.Address) != int(int(i.Len)) {
		return fmt.Errorf("size mismatch when writing field \"IPAddress::Address\": expected %d, got %d", int(int(i.Len)), len(i.Address))
	}
	if len(tmp126)-*tmp126Offset < int(0+int(i.Len)) {
		return errors.New("not enough space to write for field \"IPAddress::Address\"")
	}
	copy(tmp126[*tmp126Offset:*tmp126Offset+int(int(i.Len))], i.Address)
	*tmp126Offset += int(int(i.Len))
	return nil
}
func (s *IPAddress) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *IPAddress) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (i *IPAddress) Append(tmp126 []byte) ([]byte, error) {
	tmp182 := [1]uint8{}
	tmp182[0] = i.Len
	tmp126 = append(tmp126, tmp182[:1]...)
	if !((i.Len == 4) || (i.Len == 16)) {
		return nil, errors.New("Assertion failed")
	}
	if len(i.Address) != int(int(i.Len)) {
		return nil, fmt.Errorf("size mismatch when writing field \"IPAddress::Address\": expected %d, got %d", int(int(i.Len)), len(i.Address))
	}
	tmp126 = append(tmp126, i.Address...)
	return tmp126, nil
}
func (s *IPAddress) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (i *IPAddress) Read(tmp130 io.Reader) error {
	tmp130ByteIO, _ := tmp130.(io.ByteReader)
	_ = tmp130ByteIO
	if tmp130ByteIO != nil {
		var err error
		i.Len, err = tmp130ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp130, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"IPAddress::Len\": expected to read 1 byte, but read %d bytes", n)
		}
		i.Len = buf[0]
	}
	if !((i.Len == 4) || (i.Len == 16)) {
		return errors.New("Assertion failed")
	}
	if seeker, ok := tmp130.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(i.Len)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(i.Len)))
		}
		i.Address = make([]byte, int(i.Len))
		if _, err := io.ReadFull(tmp130, i.Address[0:0+int(i.Len)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_1236 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_1236, tmp130, int64(int(i.Len))); err != nil {
			return err
		}
		i.Address = io_temp_1236.Bytes()
	}
	return nil
}
func (s *IPAddress) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *IPAddress) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (i *IPAddress) DecodeSlice(tmp130 []byte, tmp130Offset *int) error {
	tmp30 := []uint8{}
	if len(tmp130)-*tmp130Offset < 1 {
		return errors.New("not enough data to read for field \"IPAddress::Len\"")
	}
	tmp30 = tmp130[*tmp130Offset : *tmp130Offset+1]
	*tmp130Offset += int(1)
	i.Len = tmp30[0]
	if !((i.Len == 4) || (i.Len == 16)) {
		return errors.New("Assertion failed")
	}
	if len(tmp130)-*tmp130Offset < int(i.Len) {
		return errors.New("not enough data to read for field \"IPAddress::Address\"")
	}
	i.Address = tmp130[*tmp130Offset : *tmp130Offset+int(i.Len)]
	*tmp130Offset += int(int(i.Len))
	return nil
}
func (s *IPAddress) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *IPAddress) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type MacAddress struct {
	Address [6]uint8
}

func (m *MacAddress) Write(tmp241 io.Writer) error {
	if _, err := tmp241.Write(m.Address[:6]); err != nil {
		return err
	}
	return nil
}
func (s *MacAddress) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *MacAddress) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (m *MacAddress) EncodeSlice(tmp241 []byte, tmp241Offset *int) error {
	if len(tmp241)-*tmp241Offset < int(6) {
		return errors.New("not enough space to write for field \"MacAddress::Address\"")
	}
	copy(tmp241[*tmp241Offset:*tmp241Offset+int(6)], m.Address[:])
	*tmp241Offset += int(6)
	return nil
}
func (s *MacAddress) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *MacAddress) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (m *MacAddress) Append(tmp241 []byte) ([]byte, error) {
	tmp241 = append(tmp241, m.Address[:6]...)
	return tmp241, nil
}
func (s *MacAddress) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (m *MacAddress) Read(tmp242 io.Reader) error {
	if _, err := io.ReadFull(tmp242, m.Address[0:0+6]); err != nil {
		return err
	}
	return nil
}
func (s *MacAddress) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *MacAddress) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (m *MacAddress) DecodeSlice(tmp242 []byte, tmp242Offset *int) error {
	if len(tmp242)-*tmp242Offset < 6 {
		return errors.New("not enough data to read for field \"MacAddress::Address\"")
	}
	copy(m.Address[:], tmp242[*tmp242Offset:*tmp242Offset+6])
	*tmp242Offset += int(6)
	return nil
}
func (s *MacAddress) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *MacAddress) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Probe struct {
	MacAddress MacAddress
	IpAddress  IPAddress
	Port       uint16
}

func (p *Probe) Write(tmp96 io.Writer) error {
	tmp375 := p.MacAddress.Write(tmp96)
	if tmp375 != nil {
		return tmp375
	}
	tmp368 := p.IpAddress.Write(tmp96)
	if tmp368 != nil {
		return tmp368
	}
	tmp56 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp56[:], uint16(p.Port))
	if _, err := tmp96.Write(tmp56[:2]); err != nil {
		return err
	}
	return nil
}
func (s *Probe) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Probe) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Probe) EncodeSlice(tmp96 []byte, tmp96Offset *int) error {
	tmp375 := p.MacAddress.EncodeSlice(tmp96, tmp96Offset)
	if tmp375 != nil {
		return tmp375
	}
	tmp368 := p.IpAddress.EncodeSlice(tmp96, tmp96Offset)
	if tmp368 != nil {
		return tmp368
	}
	tmp56 := []uint8{}
	if len(tmp96)-*tmp96Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Probe::Port\"")
	}
	tmp56 = tmp96[*tmp96Offset : *tmp96Offset+int(2)]
	binary.BigEndian.PutUint16(tmp56[:], uint16(p.Port))
	*tmp96Offset += int(2)
	return nil
}
func (s *Probe) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Probe) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Probe) Append(tmp96 []byte) ([]byte, error) {
	var tmp375 error
	tmp96, tmp375 = p.MacAddress.Append(tmp96)

	if tmp375 != nil {
		return nil, tmp375
	}
	var tmp368 error
	tmp96, tmp368 = p.IpAddress.Append(tmp96)

	if tmp368 != nil {
		return nil, tmp368
	}
	tmp56 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp56[:], uint16(p.Port))
	tmp96 = append(tmp96, tmp56[:2]...)
	return tmp96, nil
}
func (s *Probe) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *Probe) Read(tmp99 io.Reader) error {
	tmp413 := p.MacAddress.Read(tmp99)
	if tmp413 != nil {
		return tmp413
	}
	tmp404 := p.IpAddress.Read(tmp99)
	if tmp404 != nil {
		return tmp404
	}
	tmp64 := [2]uint8{}
	if _, err := io.ReadFull(tmp99, tmp64[0:0+2]); err != nil {
		return err
	}
	p.Port = binary.BigEndian.Uint16(tmp64[:])
	return nil
}
func (s *Probe) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Probe) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *Probe) DecodeSlice(tmp99 []byte, tmp99Offset *int) error {
	tmp413 := p.MacAddress.DecodeSlice(tmp99, tmp99Offset)
	if tmp413 != nil {
		return tmp413
	}
	tmp404 := p.IpAddress.DecodeSlice(tmp99, tmp99Offset)
	if tmp404 != nil {
		return tmp404
	}
	tmp64 := []uint8{}
	if len(tmp99)-*tmp99Offset < 2 {
		return errors.New("not enough data to read for field \"Probe::Port\"")
	}
	tmp64 = tmp99[*tmp99Offset : *tmp99Offset+2]
	*tmp99Offset += int(2)
	p.Port = binary.BigEndian.Uint16(tmp64[:])
	return nil
}
func (s *Probe) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Probe) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type KeyKind uint16

const (
	KeyKind_Offset KeyKind = 24
	KeyKind_X25519 KeyKind = 52
	KeyKind_P256   KeyKind = 249
	KeyKind_P384   KeyKind = 36
	KeyKind_P521   KeyKind = 51
)

func (e KeyKind) String() string {
	switch e {
	case KeyKind_Offset:
		return "Offset"
	case KeyKind_X25519:
		return "X25519"
	case KeyKind_P256:
		return "P256"
	case KeyKind_P384:
		return "P384"
	case KeyKind_P521:
		return "P521"
	default:
		return fmt.Sprintf("KeyKind(%d)", e)
	}
}

type CommonKeyKind uint16

const (
	CommonKeyKind_Aes128Gcm        CommonKeyKind = 115
	CommonKeyKind_Aes192Gcm        CommonKeyKind = 67
	CommonKeyKind_Aes256Gcm        CommonKeyKind = 34
	CommonKeyKind_Chacha20Poly1305 CommonKeyKind = 62
)

func (e CommonKeyKind) String() string {
	switch e {
	case CommonKeyKind_Aes128Gcm:
		return "Aes128Gcm"
	case CommonKeyKind_Aes192Gcm:
		return "Aes192Gcm"
	case CommonKeyKind_Aes256Gcm:
		return "Aes256Gcm"
	case CommonKeyKind_Chacha20Poly1305:
		return "Chacha20Poly1305"
	default:
		return fmt.Sprintf("CommonKeyKind(%d)", e)
	}
}

type PacketKind uint8

const (
	PacketKind_Handshake    PacketKind = 94
	PacketKind_HandshakeAck PacketKind = 137
	PacketKind_Application  PacketKind = 51
	PacketKind_Probe        PacketKind = 103
)

func (e PacketKind) String() string {
	switch e {
	case PacketKind_Handshake:
		return "Handshake"
	case PacketKind_HandshakeAck:
		return "HandshakeAck"
	case PacketKind_Application:
		return "Application"
	case PacketKind_Probe:
		return "Probe"
	default:
		return fmt.Sprintf("PacketKind(%d)", e)
	}
}

type ControlKind uint8

const (
	ControlKind_Ping ControlKind = 75
)

func (e ControlKind) String() string {
	switch e {
	case ControlKind_Ping:
		return "Ping"
	default:
		return fmt.Sprintf("ControlKind(%d)", e)
	}
}

type tmp355 struct {
	Offset uint16
}

func (v *tmp355) isVariant169() {}

type Variant169 interface {
	isVariant169()
}

type Handshake struct {
	KeyKind       KeyKind
	CommonKeyKind CommonKeyKind
	tmp236        Variant169
	Len           uint16
	KeyShare      []uint8
}

func (h *Handshake) Offset() *uint16 {
	if h.KeyKind == KeyKind_Offset {
		tmp354, ok := h.tmp236.(*tmp355)
		if !ok {
			return nil
		}
		_ = tmp354 // to prevent unused warnings
		return &tmp354.Offset
	}
	return nil
}
func (h *Handshake) SetOffset(tmp418 uint16) bool {
	if h.KeyKind == KeyKind_Offset {
		tmp354, ok := h.tmp236.(*tmp355)
		if !ok {
			tmp354 = &tmp355{}
			h.tmp236 = tmp354
		}
		_ = tmp354 // to prevent unused warnings
		tmp354.Offset = tmp418
		return true
	}
	return false
}

func (h *Handshake) SetKeyShare(tmp350 []uint8) bool {
	if len(tmp350) > int(65535) {
		return false
	}
	h.Len = uint16(len(tmp350))
	h.KeyShare = tmp350
	return true
}

func (h *Handshake) Write(tmp28 io.Writer) error {
	tmp345 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp345[:], uint16(uint16(h.KeyKind)))
	if _, err := tmp28.Write(tmp345[:2]); err != nil {
		return err
	}
	tmp341 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp341[:], uint16(uint16(h.CommonKeyKind)))
	if _, err := tmp28.Write(tmp341[:2]); err != nil {
		return err
	}
	if h.KeyKind == KeyKind_Offset {
		tmp354, ok := h.tmp236.(*tmp355)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp354 // to prevent unused warnings
		tmp337 := [2]uint8{}
		binary.BigEndian.PutUint16(tmp337[:], uint16(tmp354.Offset))
		if _, err := tmp28.Write(tmp337[:2]); err != nil {
			return err
		}
	}
	tmp335 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp335[:], uint16(h.Len))
	if _, err := tmp28.Write(tmp335[:2]); err != nil {
		return err
	}
	if len(h.KeyShare) != int(int(h.Len)) {
		return fmt.Errorf("size mismatch when writing field \"Handshake::KeyShare\": expected %d, got %d", int(int(h.Len)), len(h.KeyShare))
	}
	if _, err := tmp28.Write(h.KeyShare); err != nil {
		return err
	}
	return nil
}
func (s *Handshake) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Handshake) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (h *Handshake) EncodeSlice(tmp28 []byte, tmp28Offset *int) error {
	tmp345 := []uint8{}
	if len(tmp28)-*tmp28Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Handshake::KeyKind\"")
	}
	tmp345 = tmp28[*tmp28Offset : *tmp28Offset+int(2)]
	binary.BigEndian.PutUint16(tmp345[:], uint16(uint16(h.KeyKind)))
	*tmp28Offset += int(2)
	tmp341 := []uint8{}
	if len(tmp28)-*tmp28Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Handshake::CommonKeyKind\"")
	}
	tmp341 = tmp28[*tmp28Offset : *tmp28Offset+int(2)]
	binary.BigEndian.PutUint16(tmp341[:], uint16(uint16(h.CommonKeyKind)))
	*tmp28Offset += int(2)
	if h.KeyKind == KeyKind_Offset {
		tmp354, ok := h.tmp236.(*tmp355)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp354 // to prevent unused warnings
		tmp337 := []uint8{}
		if len(tmp28)-*tmp28Offset < int(2) {
			return errors.New("not enough space to reserve data for field \"Handshake::tmp236::Offset\"")
		}
		tmp337 = tmp28[*tmp28Offset : *tmp28Offset+int(2)]
		binary.BigEndian.PutUint16(tmp337[:], uint16(tmp354.Offset))
		*tmp28Offset += int(2)
	}
	tmp335 := []uint8{}
	if len(tmp28)-*tmp28Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Handshake::Len\"")
	}
	tmp335 = tmp28[*tmp28Offset : *tmp28Offset+int(2)]
	binary.BigEndian.PutUint16(tmp335[:], uint16(h.Len))
	*tmp28Offset += int(2)
	if len(h.KeyShare) != int(int(h.Len)) {
		return fmt.Errorf("size mismatch when writing field \"Handshake::KeyShare\": expected %d, got %d", int(int(h.Len)), len(h.KeyShare))
	}
	if len(tmp28)-*tmp28Offset < int(0+int(h.Len)) {
		return errors.New("not enough space to write for field \"Handshake::KeyShare\"")
	}
	copy(tmp28[*tmp28Offset:*tmp28Offset+int(int(h.Len))], h.KeyShare)
	*tmp28Offset += int(int(h.Len))
	return nil
}
func (s *Handshake) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Handshake) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (h *Handshake) Append(tmp28 []byte) ([]byte, error) {
	tmp345 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp345[:], uint16(uint16(h.KeyKind)))
	tmp28 = append(tmp28, tmp345[:2]...)
	tmp341 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp341[:], uint16(uint16(h.CommonKeyKind)))
	tmp28 = append(tmp28, tmp341[:2]...)
	if h.KeyKind == KeyKind_Offset {
		tmp354, ok := h.tmp236.(*tmp355)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp354 // to prevent unused warnings
		tmp337 := [2]uint8{}
		binary.BigEndian.PutUint16(tmp337[:], uint16(tmp354.Offset))
		tmp28 = append(tmp28, tmp337[:2]...)
	}
	tmp335 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp335[:], uint16(h.Len))
	tmp28 = append(tmp28, tmp335[:2]...)
	if len(h.KeyShare) != int(int(h.Len)) {
		return nil, fmt.Errorf("size mismatch when writing field \"Handshake::KeyShare\": expected %d, got %d", int(int(h.Len)), len(h.KeyShare))
	}
	tmp28 = append(tmp28, h.KeyShare...)
	return tmp28, nil
}
func (s *Handshake) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (h *Handshake) Read(tmp29 io.Reader) error {
	tmp247 := uint16(0)
	tmp412 := [2]uint8{}
	if _, err := io.ReadFull(tmp29, tmp412[0:0+2]); err != nil {
		return err
	}
	tmp247 = binary.BigEndian.Uint16(tmp412[:])
	h.KeyKind = KeyKind(tmp247)
	tmp417 := uint16(0)
	tmp410 := [2]uint8{}
	if _, err := io.ReadFull(tmp29, tmp410[0:0+2]); err != nil {
		return err
	}
	tmp417 = binary.BigEndian.Uint16(tmp410[:])
	h.CommonKeyKind = CommonKeyKind(tmp417)
	if h.KeyKind == KeyKind_Offset {
		tmp354, ok := h.tmp236.(*tmp355)
		if !ok {
			tmp354 = &tmp355{}
			h.tmp236 = tmp354
		}
		_ = tmp354 // to prevent unused warnings
		tmp393 := [2]uint8{}
		if _, err := io.ReadFull(tmp29, tmp393[0:0+2]); err != nil {
			return err
		}
		tmp354.Offset = binary.BigEndian.Uint16(tmp393[:])
	}
	tmp348 := [2]uint8{}
	if _, err := io.ReadFull(tmp29, tmp348[0:0+2]); err != nil {
		return err
	}
	h.Len = binary.BigEndian.Uint16(tmp348[:])
	if seeker, ok := tmp29.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(h.Len)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(h.Len)))
		}
		h.KeyShare = make([]byte, int(h.Len))
		if _, err := io.ReadFull(tmp29, h.KeyShare[0:0+int(h.Len)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_973 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_973, tmp29, int64(int(h.Len))); err != nil {
			return err
		}
		h.KeyShare = io_temp_973.Bytes()
	}
	return nil
}
func (s *Handshake) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Handshake) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (h *Handshake) DecodeSlice(tmp29 []byte, tmp29Offset *int) error {
	tmp247 := uint16(0)
	tmp412 := []uint8{}
	if len(tmp29)-*tmp29Offset < 2 {
		return errors.New("not enough data to read for field \"Handshake::KeyKind\"")
	}
	tmp412 = tmp29[*tmp29Offset : *tmp29Offset+2]
	*tmp29Offset += int(2)
	tmp247 = binary.BigEndian.Uint16(tmp412[:])
	h.KeyKind = KeyKind(tmp247)
	tmp417 := uint16(0)
	tmp410 := []uint8{}
	if len(tmp29)-*tmp29Offset < 2 {
		return errors.New("not enough data to read for field \"Handshake::CommonKeyKind\"")
	}
	tmp410 = tmp29[*tmp29Offset : *tmp29Offset+2]
	*tmp29Offset += int(2)
	tmp417 = binary.BigEndian.Uint16(tmp410[:])
	h.CommonKeyKind = CommonKeyKind(tmp417)
	if h.KeyKind == KeyKind_Offset {
		tmp354, ok := h.tmp236.(*tmp355)
		if !ok {
			tmp354 = &tmp355{}
			h.tmp236 = tmp354
		}
		_ = tmp354 // to prevent unused warnings
		tmp393 := []uint8{}
		if len(tmp29)-*tmp29Offset < 2 {
			return errors.New("not enough data to read for field \"Handshake::tmp236::Offset\"")
		}
		tmp393 = tmp29[*tmp29Offset : *tmp29Offset+2]
		*tmp29Offset += int(2)
		tmp354.Offset = binary.BigEndian.Uint16(tmp393[:])
	}
	tmp348 := []uint8{}
	if len(tmp29)-*tmp29Offset < 2 {
		return errors.New("not enough data to read for field \"Handshake::Len\"")
	}
	tmp348 = tmp29[*tmp29Offset : *tmp29Offset+2]
	*tmp29Offset += int(2)
	h.Len = binary.BigEndian.Uint16(tmp348[:])
	if len(tmp29)-*tmp29Offset < int(h.Len) {
		return errors.New("not enough data to read for field \"Handshake::KeyShare\"")
	}
	h.KeyShare = tmp29[*tmp29Offset : *tmp29Offset+int(h.Len)]
	*tmp29Offset += int(int(h.Len))
	return nil
}
func (s *Handshake) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Handshake) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func (h *PacketHeader) KeyPhase() bool {
	intVal := h.keyPhase()
	return intVal != 0
}
func (p *PacketHeader) keyPhase() uint8 {
	return uint8(((p.tmp77 >> uint8(7)) & uint8(1)))
}

func (p *PacketHeader) SetKeyPhase(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return p.setKeyPhase(intVal)
}
func (p *PacketHeader) setKeyPhase(tmp344 uint8) bool {
	p.tmp77 = (p.tmp77 & (^(uint8(1) << uint8(7)))) | ((uint8(tmp344) & uint8(1)) << uint8(7))
	return true
}

func (p *PacketHeader) MaskSeed() uint8 {
	return uint8(((p.tmp77 >> uint8(0)) & uint8(127)))
}

func (p *PacketHeader) SetMaskSeed(tmp338 uint8) bool {
	p.tmp77 = (p.tmp77 & (^(uint8(127) << uint8(0)))) | ((uint8(tmp338) & uint8(127)) << uint8(0))
	return true
}

type PacketHeader struct {
	tmp77              uint8
	MaskedKind         uint8
	MaskedConnectionId uint16
	Len                uint16
}

func (p *PacketHeader) Write(tmp31 io.Writer) error {
	tmp358 := [1]uint8{}
	tmp358[0] = uint8((p.keyPhase() & 1)) << uint8(7)
	tmp358[0] = tmp358[0] | uint8((p.MaskSeed() & 127))
	if _, err := tmp31.Write(tmp358[:1]); err != nil {
		return err
	}
	tmp321 := [1]uint8{}
	tmp321[0] = p.MaskedKind
	if _, err := tmp31.Write(tmp321[:1]); err != nil {
		return err
	}
	tmp318 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp318[:], uint16(p.MaskedConnectionId))
	if _, err := tmp31.Write(tmp318[:2]); err != nil {
		return err
	}
	tmp316 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp316[:], uint16(p.Len))
	if _, err := tmp31.Write(tmp316[:2]); err != nil {
		return err
	}
	return nil
}
func (s *PacketHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PacketHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) EncodeSlice(tmp31 []byte, tmp31Offset *int) error {
	tmp358 := []uint8{}
	if len(tmp31)-*tmp31Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::MaskSeed\"")
	}
	tmp358 = tmp31[*tmp31Offset : *tmp31Offset+int(1)]
	tmp358[0] = uint8((p.keyPhase() & 1)) << uint8(7)
	tmp358[0] = tmp358[0] | uint8((p.MaskSeed() & 127))
	*tmp31Offset += int(1)
	tmp321 := []uint8{}
	if len(tmp31)-*tmp31Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::MaskedKind\"")
	}
	tmp321 = tmp31[*tmp31Offset : *tmp31Offset+int(1)]
	tmp321[0] = p.MaskedKind
	*tmp31Offset += int(1)
	tmp318 := []uint8{}
	if len(tmp31)-*tmp31Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::MaskedConnectionId\"")
	}
	tmp318 = tmp31[*tmp31Offset : *tmp31Offset+int(2)]
	binary.BigEndian.PutUint16(tmp318[:], uint16(p.MaskedConnectionId))
	*tmp31Offset += int(2)
	tmp316 := []uint8{}
	if len(tmp31)-*tmp31Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::Len\"")
	}
	tmp316 = tmp31[*tmp31Offset : *tmp31Offset+int(2)]
	binary.BigEndian.PutUint16(tmp316[:], uint16(p.Len))
	*tmp31Offset += int(2)
	return nil
}
func (s *PacketHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PacketHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) Append(tmp31 []byte) ([]byte, error) {
	tmp358 := [1]uint8{}
	tmp358[0] = uint8((p.keyPhase() & 1)) << uint8(7)
	tmp358[0] = tmp358[0] | uint8((p.MaskSeed() & 127))
	tmp31 = append(tmp31, tmp358[:1]...)
	tmp321 := [1]uint8{}
	tmp321[0] = p.MaskedKind
	tmp31 = append(tmp31, tmp321[:1]...)
	tmp318 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp318[:], uint16(p.MaskedConnectionId))
	tmp31 = append(tmp31, tmp318[:2]...)
	tmp316 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp316[:], uint16(p.Len))
	tmp31 = append(tmp31, tmp316[:2]...)
	return tmp31, nil
}
func (s *PacketHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PacketHeader) Read(tmp22 io.Reader) error {
	tmp384 := [1]uint8{}
	if _, err := io.ReadFull(tmp22, tmp384[0:0+1]); err != nil {
		return err
	}
	tmp239 := uint8(0)
	tmp239 = uint8(((tmp384[0] & 128) >> uint8(7)))
	p.setKeyPhase(tmp239)
	tmp371 := uint8(0)
	tmp371 = uint8((tmp384[0] & uint8(127)))
	p.SetMaskSeed(tmp371)
	tmp329 := [1]uint8{}
	if _, err := io.ReadFull(tmp22, tmp329[0:0+1]); err != nil {
		return err
	}
	p.MaskedKind = tmp329[0]
	tmp326 := [2]uint8{}
	if _, err := io.ReadFull(tmp22, tmp326[0:0+2]); err != nil {
		return err
	}
	p.MaskedConnectionId = binary.BigEndian.Uint16(tmp326[:])
	tmp324 := [2]uint8{}
	if _, err := io.ReadFull(tmp22, tmp324[0:0+2]); err != nil {
		return err
	}
	p.Len = binary.BigEndian.Uint16(tmp324[:])
	return nil
}
func (s *PacketHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PacketHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PacketHeader) DecodeSlice(tmp22 []byte, tmp22Offset *int) error {
	tmp384 := []uint8{}
	if len(tmp22)-*tmp22Offset < 1 {
		return errors.New("not enough data to read for field \"tmp154\"")
	}
	tmp384 = tmp22[*tmp22Offset : *tmp22Offset+1]
	*tmp22Offset += int(1)
	tmp239 := uint8(0)
	tmp239 = uint8(((tmp384[0] & 128) >> uint8(7)))
	p.setKeyPhase(tmp239)
	tmp371 := uint8(0)
	tmp371 = uint8((tmp384[0] & uint8(127)))
	p.SetMaskSeed(tmp371)
	tmp329 := []uint8{}
	if len(tmp22)-*tmp22Offset < 1 {
		return errors.New("not enough data to read for field \"PacketHeader::MaskedKind\"")
	}
	tmp329 = tmp22[*tmp22Offset : *tmp22Offset+1]
	*tmp22Offset += int(1)
	p.MaskedKind = tmp329[0]
	tmp326 := []uint8{}
	if len(tmp22)-*tmp22Offset < 2 {
		return errors.New("not enough data to read for field \"PacketHeader::MaskedConnectionId\"")
	}
	tmp326 = tmp22[*tmp22Offset : *tmp22Offset+2]
	*tmp22Offset += int(2)
	p.MaskedConnectionId = binary.BigEndian.Uint16(tmp326[:])
	tmp324 := []uint8{}
	if len(tmp22)-*tmp22Offset < 2 {
		return errors.New("not enough data to read for field \"PacketHeader::Len\"")
	}
	tmp324 = tmp22[*tmp22Offset : *tmp22Offset+2]
	*tmp22Offset += int(2)
	p.Len = binary.BigEndian.Uint16(tmp324[:])
	return nil
}
func (s *PacketHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PacketHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func (p *ProtectedHeader) Control() bool {
	intVal := p.control()
	return intVal != 0
}
func (p *ProtectedHeader) control() uint8 {
	return uint8(((p.tmp72 >> uint64(63)) & uint64(1)))
}

func (p *ProtectedHeader) SetControl(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return p.setControl(intVal)
}
func (p *ProtectedHeader) setControl(tmp312 uint8) bool {
	p.tmp72 = (p.tmp72 & (^(uint64(1) << uint64(63)))) | ((uint64(tmp312) & uint64(1)) << uint64(63))
	return true
}

func (p *ProtectedHeader) NonceCounter() uint64 {
	return uint64(((p.tmp72 >> uint64(0)) & uint64(9223372036854775807)))
}

func (p *ProtectedHeader) SetNonceCounter(tmp310 uint64) bool {
	p.tmp72 = (p.tmp72 & (^(uint64(9223372036854775807) << uint64(0)))) | ((uint64(tmp310) & uint64(9223372036854775807)) << uint64(0))
	return true
}

type ProtectedHeader struct {
	tmp72 uint64
}

func (p *ProtectedHeader) Write(tmp108 io.Writer) error {
	tmp275 := [8]uint8{}
	tmp275[0] = uint8((p.control() & 1)) << uint8(7)
	tmp275[0] = tmp275[0] | uint8(((p.NonceCounter() >> uint64(56)) & uint64(127)))
	tmp275[1] = uint8(((p.NonceCounter() >> uint64(48)) & uint64(255)))
	tmp275[2] = uint8(((p.NonceCounter() >> uint64(40)) & uint64(255)))
	tmp275[3] = uint8(((p.NonceCounter() >> uint64(32)) & uint64(255)))
	tmp275[4] = uint8(((p.NonceCounter() >> uint64(24)) & uint64(255)))
	tmp275[5] = uint8(((p.NonceCounter() >> uint64(16)) & uint64(255)))
	tmp275[6] = uint8(((p.NonceCounter() >> uint64(8)) & uint64(255)))
	tmp275[7] = uint8((p.NonceCounter() & uint64(255)))
	if _, err := tmp108.Write(tmp275[:8]); err != nil {
		return err
	}
	return nil
}
func (s *ProtectedHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *ProtectedHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *ProtectedHeader) EncodeSlice(tmp108 []byte, tmp108Offset *int) error {
	tmp275 := []uint8{}
	if len(tmp108)-*tmp108Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"ProtectedHeader::NonceCounter\"")
	}
	tmp275 = tmp108[*tmp108Offset : *tmp108Offset+int(8)]
	tmp275[0] = uint8((p.control() & 1)) << uint8(7)
	tmp275[0] = tmp275[0] | uint8(((p.NonceCounter() >> uint64(56)) & uint64(127)))
	tmp275[1] = uint8(((p.NonceCounter() >> uint64(48)) & uint64(255)))
	tmp275[2] = uint8(((p.NonceCounter() >> uint64(40)) & uint64(255)))
	tmp275[3] = uint8(((p.NonceCounter() >> uint64(32)) & uint64(255)))
	tmp275[4] = uint8(((p.NonceCounter() >> uint64(24)) & uint64(255)))
	tmp275[5] = uint8(((p.NonceCounter() >> uint64(16)) & uint64(255)))
	tmp275[6] = uint8(((p.NonceCounter() >> uint64(8)) & uint64(255)))
	tmp275[7] = uint8((p.NonceCounter() & uint64(255)))
	*tmp108Offset += int(8)
	return nil
}
func (s *ProtectedHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *ProtectedHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *ProtectedHeader) Append(tmp108 []byte) ([]byte, error) {
	tmp275 := [8]uint8{}
	tmp275[0] = uint8((p.control() & 1)) << uint8(7)
	tmp275[0] = tmp275[0] | uint8(((p.NonceCounter() >> uint64(56)) & uint64(127)))
	tmp275[1] = uint8(((p.NonceCounter() >> uint64(48)) & uint64(255)))
	tmp275[2] = uint8(((p.NonceCounter() >> uint64(40)) & uint64(255)))
	tmp275[3] = uint8(((p.NonceCounter() >> uint64(32)) & uint64(255)))
	tmp275[4] = uint8(((p.NonceCounter() >> uint64(24)) & uint64(255)))
	tmp275[5] = uint8(((p.NonceCounter() >> uint64(16)) & uint64(255)))
	tmp275[6] = uint8(((p.NonceCounter() >> uint64(8)) & uint64(255)))
	tmp275[7] = uint8((p.NonceCounter() & uint64(255)))
	tmp108 = append(tmp108, tmp275[:8]...)
	return tmp108, nil
}
func (s *ProtectedHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *ProtectedHeader) Read(tmp10 io.Reader) error {
	tmp309 := [8]uint8{}
	if _, err := io.ReadFull(tmp10, tmp309[0:0+8]); err != nil {
		return err
	}
	tmp291 := uint8(0)
	tmp291 = uint8(((tmp309[0] & 128) >> uint8(7)))
	p.setControl(tmp291)
	tmp289 := uint64(0)
	tmp289 = (((((((uint64((tmp309[0] & uint8(127))) << uint64(56)) | (uint64(tmp309[1]) << uint64(48))) | (uint64(tmp309[2]) << uint64(40))) | (uint64(tmp309[3]) << uint64(32))) | (uint64(tmp309[4]) << uint64(24))) | (uint64(tmp309[5]) << uint64(16))) | (uint64(tmp309[6]) << uint64(8))) | uint64(tmp309[7])
	p.SetNonceCounter(tmp289)
	return nil
}
func (s *ProtectedHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *ProtectedHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *ProtectedHeader) DecodeSlice(tmp10 []byte, tmp10Offset *int) error {
	tmp309 := []uint8{}
	if len(tmp10)-*tmp10Offset < 8 {
		return errors.New("not enough data to read for field \"tmp16\"")
	}
	tmp309 = tmp10[*tmp10Offset : *tmp10Offset+8]
	*tmp10Offset += int(8)
	tmp291 := uint8(0)
	tmp291 = uint8(((tmp309[0] & 128) >> uint8(7)))
	p.setControl(tmp291)
	tmp289 := uint64(0)
	tmp289 = (((((((uint64((tmp309[0] & uint8(127))) << uint64(56)) | (uint64(tmp309[1]) << uint64(48))) | (uint64(tmp309[2]) << uint64(40))) | (uint64(tmp309[3]) << uint64(32))) | (uint64(tmp309[4]) << uint64(24))) | (uint64(tmp309[5]) << uint64(16))) | (uint64(tmp309[6]) << uint64(8))) | uint64(tmp309[7])
	p.SetNonceCounter(tmp289)
	return nil
}
func (s *ProtectedHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *ProtectedHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type EncryptedData struct {
	NonceCounter uint64
	Data         []uint8
}

func (e *EncryptedData) Write(tmp135 io.Writer) error {
	tmp204 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp204[:], uint64(e.NonceCounter))
	if _, err := tmp135.Write(tmp204[:8]); err != nil {
		return err
	}
	if _, err := tmp135.Write(e.Data); err != nil {
		return err
	}
	return nil
}
func (s *EncryptedData) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *EncryptedData) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (e *EncryptedData) EncodeSlice(tmp135 []byte, tmp135Offset *int) error {
	tmp204 := []uint8{}
	if len(tmp135)-*tmp135Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"EncryptedData::NonceCounter\"")
	}
	tmp204 = tmp135[*tmp135Offset : *tmp135Offset+int(8)]
	binary.BigEndian.PutUint64(tmp204[:], uint64(e.NonceCounter))
	*tmp135Offset += int(8)
	if len(tmp135)-*tmp135Offset < int(0+len(e.Data)) {
		return errors.New("not enough space to write for field \"EncryptedData::Data\"")
	}
	copy(tmp135[*tmp135Offset:*tmp135Offset+int(len(e.Data))], e.Data)
	*tmp135Offset += int(len(e.Data))
	return nil
}
func (s *EncryptedData) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *EncryptedData) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (e *EncryptedData) Append(tmp135 []byte) ([]byte, error) {
	tmp204 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp204[:], uint64(e.NonceCounter))
	tmp135 = append(tmp135, tmp204[:8]...)
	tmp135 = append(tmp135, e.Data...)
	return tmp135, nil
}
func (s *EncryptedData) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (e *EncryptedData) Read(tmp106 io.Reader) error {
	tmp213 := [8]uint8{}
	if _, err := io.ReadFull(tmp106, tmp213[0:0+8]); err != nil {
		return err
	}
	e.NonceCounter = binary.BigEndian.Uint64(tmp213[:])
	{
		var readErr error
		e.Data, readErr = io.ReadAll(tmp106)
		if readErr != nil {
			return readErr
		}
	}
	return nil
}
func (s *EncryptedData) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *EncryptedData) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (e *EncryptedData) DecodeSlice(tmp106 []byte, tmp106Offset *int) error {
	tmp213 := []uint8{}
	if len(tmp106)-*tmp106Offset < 8 {
		return errors.New("not enough data to read for field \"EncryptedData::NonceCounter\"")
	}
	tmp213 = tmp106[*tmp106Offset : *tmp106Offset+8]
	*tmp106Offset += int(8)
	e.NonceCounter = binary.BigEndian.Uint64(tmp213[:])
	e.Data = tmp106[*tmp106Offset:]
	*tmp106Offset += len(e.Data)
	return nil
}
func (s *EncryptedData) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *EncryptedData) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Packet struct {
	Header PacketHeader
	Data   []uint8
}

func (p *Packet) SetData(tmp252 []uint8) bool {
	if len(tmp252) > int(65535) {
		return false
	}
	p.Header.Len = uint16(len(tmp252))
	p.Data = tmp252
	return true
}

func (p *Packet) Write(tmp131 io.Writer) error {
	tmp257 := p.Header.Write(tmp131)
	if tmp257 != nil {
		return tmp257
	}
	if len(p.Data) != int(int(p.Header.Len)) {
		return fmt.Errorf("size mismatch when writing field \"Packet::Data\": expected %d, got %d", int(int(p.Header.Len)), len(p.Data))
	}
	if _, err := tmp131.Write(p.Data); err != nil {
		return err
	}
	return nil
}
func (s *Packet) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Packet) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Packet) EncodeSlice(tmp131 []byte, tmp131Offset *int) error {
	tmp257 := p.Header.EncodeSlice(tmp131, tmp131Offset)
	if tmp257 != nil {
		return tmp257
	}
	if len(p.Data) != int(int(p.Header.Len)) {
		return fmt.Errorf("size mismatch when writing field \"Packet::Data\": expected %d, got %d", int(int(p.Header.Len)), len(p.Data))
	}
	if len(tmp131)-*tmp131Offset < int(0+int(p.Header.Len)) {
		return errors.New("not enough space to write for field \"Packet::Data\"")
	}
	copy(tmp131[*tmp131Offset:*tmp131Offset+int(int(p.Header.Len))], p.Data)
	*tmp131Offset += int(int(p.Header.Len))
	return nil
}
func (s *Packet) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Packet) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Packet) Append(tmp131 []byte) ([]byte, error) {
	var tmp257 error
	tmp131, tmp257 = p.Header.Append(tmp131)

	if tmp257 != nil {
		return nil, tmp257
	}
	if len(p.Data) != int(int(p.Header.Len)) {
		return nil, fmt.Errorf("size mismatch when writing field \"Packet::Data\": expected %d, got %d", int(int(p.Header.Len)), len(p.Data))
	}
	tmp131 = append(tmp131, p.Data...)
	return tmp131, nil
}
func (s *Packet) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *Packet) Read(tmp133 io.Reader) error {
	tmp260 := p.Header.Read(tmp133)
	if tmp260 != nil {
		return tmp260
	}
	if seeker, ok := tmp133.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(p.Header.Len)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(p.Header.Len)))
		}
		p.Data = make([]byte, int(p.Header.Len))
		if _, err := io.ReadFull(tmp133, p.Data[0:0+int(p.Header.Len)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_476 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_476, tmp133, int64(int(p.Header.Len))); err != nil {
			return err
		}
		p.Data = io_temp_476.Bytes()
	}
	return nil
}
func (s *Packet) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Packet) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *Packet) DecodeSlice(tmp133 []byte, tmp133Offset *int) error {
	tmp260 := p.Header.DecodeSlice(tmp133, tmp133Offset)
	if tmp260 != nil {
		return tmp260
	}
	if len(tmp133)-*tmp133Offset < int(p.Header.Len) {
		return errors.New("not enough data to read for field \"Packet::Data\"")
	}
	p.Data = tmp133[*tmp133Offset : *tmp133Offset+int(p.Header.Len)]
	*tmp133Offset += int(int(p.Header.Len))
	return nil
}
func (s *Packet) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Packet) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func IsCommonKeyKindDefined(Kind CommonKeyKind) bool {
	return ((((Kind == CommonKeyKind_Aes128Gcm) || (Kind == CommonKeyKind_Aes192Gcm)) || (Kind == CommonKeyKind_Aes256Gcm)) || (Kind == CommonKeyKind_Chacha20Poly1305))
}
