// Code generated by ebm2go at https://github.com/on-keyday/brgen, DO NOT EDIT.
package packet

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("packet")*/
type IPAddress struct {
	Len     uint8
	Address []uint8
}

func (i *IPAddress) SetAddress(tmp401 []uint8) bool {
	if len(tmp401) > int(255) {
		return false
	}
	i.Len = uint8(len(tmp401))
	i.Address = tmp401
	return true
}

func (i *IPAddress) Write(tmp126 io.Writer) error {
	tmp126ByteIO, _ := tmp126.(io.ByteWriter)
	_ = tmp126ByteIO
	if tmp126ByteIO != nil {
		if err := tmp126ByteIO.WriteByte(i.Len); err != nil {
			return err
		}
	} else {
		if _, err := tmp126.Write([]byte{i.Len}); err != nil {
			return err
		}
	}
	if !((i.Len == 4) || (i.Len == 16)) {
		return errors.New("Assertion failed")
	}
	if len(i.Address) != int(int(i.Len)) {
		return fmt.Errorf("size mismatch when writing field \"IPAddress::Address\": expected %d, got %d", int(int(i.Len)), len(i.Address))
	}
	if _, err := tmp126.Write(i.Address); err != nil {
		return err
	}
	return nil
}
func (s *IPAddress) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *IPAddress) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (i *IPAddress) EncodeSlice(tmp126 []byte, tmp126Offset *int) error {
	tmp180 := []uint8{}
	if len(tmp126)-*tmp126Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"IPAddress::Len\"")
	}
	tmp180 = tmp126[*tmp126Offset : *tmp126Offset+int(1)]
	tmp180[0] = i.Len
	*tmp126Offset += int(1)
	if !((i.Len == 4) || (i.Len == 16)) {
		return errors.New("Assertion failed")
	}
	if len(i.Address) != int(int(i.Len)) {
		return fmt.Errorf("size mismatch when writing field \"IPAddress::Address\": expected %d, got %d", int(int(i.Len)), len(i.Address))
	}
	if len(tmp126)-*tmp126Offset < int(0+int(i.Len)) {
		return errors.New("not enough space to write for field \"IPAddress::Address\"")
	}
	copy(tmp126[*tmp126Offset:*tmp126Offset+int(int(i.Len))], i.Address)
	*tmp126Offset += int(int(i.Len))
	return nil
}
func (s *IPAddress) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *IPAddress) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (i *IPAddress) Append(tmp126 []byte) ([]byte, error) {
	tmp180 := [1]uint8{}
	tmp180[0] = i.Len
	tmp126 = append(tmp126, tmp180[:1]...)
	if !((i.Len == 4) || (i.Len == 16)) {
		return nil, errors.New("Assertion failed")
	}
	if len(i.Address) != int(int(i.Len)) {
		return nil, fmt.Errorf("size mismatch when writing field \"IPAddress::Address\": expected %d, got %d", int(int(i.Len)), len(i.Address))
	}
	tmp126 = append(tmp126, i.Address...)
	return tmp126, nil
}
func (s *IPAddress) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (i *IPAddress) Read(tmp129 io.Reader) error {
	tmp129ByteIO, _ := tmp129.(io.ByteReader)
	_ = tmp129ByteIO
	if tmp129ByteIO != nil {
		var err error
		i.Len, err = tmp129ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp129, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"IPAddress::Len\": expected to read 1 byte, but read %d bytes", n)
		}
		i.Len = buf[0]
	}
	if !((i.Len == 4) || (i.Len == 16)) {
		return errors.New("Assertion failed")
	}
	if seeker, ok := tmp129.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(i.Len)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(i.Len)))
		}
		i.Address = make([]byte, int(i.Len))
		if _, err := io.ReadFull(tmp129, i.Address[0:0+int(i.Len)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_1214 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_1214, tmp129, int64(int(i.Len))); err != nil {
			return err
		}
		i.Address = io_temp_1214.Bytes()
	}
	return nil
}
func (s *IPAddress) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *IPAddress) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (i *IPAddress) DecodeSlice(tmp129 []byte, tmp129Offset *int) error {
	tmp29 := []uint8{}
	if len(tmp129)-*tmp129Offset < 1 {
		return errors.New("not enough data to read for field \"IPAddress::Len\"")
	}
	tmp29 = tmp129[*tmp129Offset : *tmp129Offset+1]
	*tmp129Offset += int(1)
	i.Len = tmp29[0]
	if !((i.Len == 4) || (i.Len == 16)) {
		return errors.New("Assertion failed")
	}
	if len(tmp129)-*tmp129Offset < int(i.Len) {
		return errors.New("not enough data to read for field \"IPAddress::Address\"")
	}
	i.Address = tmp129[*tmp129Offset : *tmp129Offset+int(i.Len)]
	*tmp129Offset += int(int(i.Len))
	return nil
}
func (s *IPAddress) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *IPAddress) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type MacAddress struct {
	Address [6]uint8
}

func (m *MacAddress) Write(tmp239 io.Writer) error {
	if _, err := tmp239.Write(m.Address[:6]); err != nil {
		return err
	}
	return nil
}
func (s *MacAddress) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *MacAddress) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (m *MacAddress) EncodeSlice(tmp239 []byte, tmp239Offset *int) error {
	if len(tmp239)-*tmp239Offset < int(6) {
		return errors.New("not enough space to write for field \"MacAddress::Address\"")
	}
	copy(tmp239[*tmp239Offset:*tmp239Offset+int(6)], m.Address[:])
	*tmp239Offset += int(6)
	return nil
}
func (s *MacAddress) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *MacAddress) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (m *MacAddress) Append(tmp239 []byte) ([]byte, error) {
	tmp239 = append(tmp239, m.Address[:6]...)
	return tmp239, nil
}
func (s *MacAddress) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (m *MacAddress) Read(tmp240 io.Reader) error {
	if _, err := io.ReadFull(tmp240, m.Address[0:0+6]); err != nil {
		return err
	}
	return nil
}
func (s *MacAddress) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *MacAddress) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (m *MacAddress) DecodeSlice(tmp240 []byte, tmp240Offset *int) error {
	if len(tmp240)-*tmp240Offset < 6 {
		return errors.New("not enough data to read for field \"MacAddress::Address\"")
	}
	copy(m.Address[:], tmp240[*tmp240Offset:*tmp240Offset+6])
	*tmp240Offset += int(6)
	return nil
}
func (s *MacAddress) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *MacAddress) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Probe struct {
	MacAddress MacAddress
	IpAddress  IPAddress
	Port       uint16
}

func (p *Probe) Write(tmp96 io.Writer) error {
	tmp363 := p.MacAddress.Write(tmp96)
	if tmp363 != nil {
		return tmp363
	}
	tmp360 := p.IpAddress.Write(tmp96)
	if tmp360 != nil {
		return tmp360
	}
	tmp54 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp54[:], uint16(p.Port))
	if _, err := tmp96.Write(tmp54[:2]); err != nil {
		return err
	}
	return nil
}
func (s *Probe) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Probe) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Probe) EncodeSlice(tmp96 []byte, tmp96Offset *int) error {
	tmp363 := p.MacAddress.EncodeSlice(tmp96, tmp96Offset)
	if tmp363 != nil {
		return tmp363
	}
	tmp360 := p.IpAddress.EncodeSlice(tmp96, tmp96Offset)
	if tmp360 != nil {
		return tmp360
	}
	tmp54 := []uint8{}
	if len(tmp96)-*tmp96Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Probe::Port\"")
	}
	tmp54 = tmp96[*tmp96Offset : *tmp96Offset+int(2)]
	binary.BigEndian.PutUint16(tmp54[:], uint16(p.Port))
	*tmp96Offset += int(2)
	return nil
}
func (s *Probe) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Probe) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Probe) Append(tmp96 []byte) ([]byte, error) {
	var tmp363 error
	tmp96, tmp363 = p.MacAddress.Append(tmp96)

	if tmp363 != nil {
		return nil, tmp363
	}
	var tmp360 error
	tmp96, tmp360 = p.IpAddress.Append(tmp96)

	if tmp360 != nil {
		return nil, tmp360
	}
	tmp54 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp54[:], uint16(p.Port))
	tmp96 = append(tmp96, tmp54[:2]...)
	return tmp96, nil
}
func (s *Probe) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *Probe) Read(tmp99 io.Reader) error {
	tmp407 := p.MacAddress.Read(tmp99)
	if tmp407 != nil {
		return tmp407
	}
	tmp393 := p.IpAddress.Read(tmp99)
	if tmp393 != nil {
		return tmp393
	}
	tmp62 := [2]uint8{}
	if _, err := io.ReadFull(tmp99, tmp62[0:0+2]); err != nil {
		return err
	}
	p.Port = binary.BigEndian.Uint16(tmp62[:])
	return nil
}
func (s *Probe) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Probe) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *Probe) DecodeSlice(tmp99 []byte, tmp99Offset *int) error {
	tmp407 := p.MacAddress.DecodeSlice(tmp99, tmp99Offset)
	if tmp407 != nil {
		return tmp407
	}
	tmp393 := p.IpAddress.DecodeSlice(tmp99, tmp99Offset)
	if tmp393 != nil {
		return tmp393
	}
	tmp62 := []uint8{}
	if len(tmp99)-*tmp99Offset < 2 {
		return errors.New("not enough data to read for field \"Probe::Port\"")
	}
	tmp62 = tmp99[*tmp99Offset : *tmp99Offset+2]
	*tmp99Offset += int(2)
	p.Port = binary.BigEndian.Uint16(tmp62[:])
	return nil
}
func (s *Probe) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Probe) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type KeyKind uint16

const (
	KeyKind_Offset KeyKind = 24
	KeyKind_X25519 KeyKind = 52
	KeyKind_P256   KeyKind = 249
	KeyKind_P384   KeyKind = 36
	KeyKind_P521   KeyKind = 51
)

func (e KeyKind) String() string {
	switch e {
	case KeyKind_Offset:
		return "Offset"
	case KeyKind_X25519:
		return "X25519"
	case KeyKind_P256:
		return "P256"
	case KeyKind_P384:
		return "P384"
	case KeyKind_P521:
		return "P521"
	default:
		return fmt.Sprintf("KeyKind(%d)", e)
	}
}

type CommonKeyKind uint16

const (
	CommonKeyKind_Aes128Gcm        CommonKeyKind = 115
	CommonKeyKind_Aes192Gcm        CommonKeyKind = 67
	CommonKeyKind_Aes256Gcm        CommonKeyKind = 34
	CommonKeyKind_Chacha20Poly1305 CommonKeyKind = 62
)

func (e CommonKeyKind) String() string {
	switch e {
	case CommonKeyKind_Aes128Gcm:
		return "Aes128Gcm"
	case CommonKeyKind_Aes192Gcm:
		return "Aes192Gcm"
	case CommonKeyKind_Aes256Gcm:
		return "Aes256Gcm"
	case CommonKeyKind_Chacha20Poly1305:
		return "Chacha20Poly1305"
	default:
		return fmt.Sprintf("CommonKeyKind(%d)", e)
	}
}

type PacketKind uint8

const (
	PacketKind_Handshake    PacketKind = 94
	PacketKind_HandshakeAck PacketKind = 137
	PacketKind_Application  PacketKind = 51
	PacketKind_Probe        PacketKind = 103
)

func (e PacketKind) String() string {
	switch e {
	case PacketKind_Handshake:
		return "Handshake"
	case PacketKind_HandshakeAck:
		return "HandshakeAck"
	case PacketKind_Application:
		return "Application"
	case PacketKind_Probe:
		return "Probe"
	default:
		return fmt.Sprintf("PacketKind(%d)", e)
	}
}

type ControlKind uint8

const (
	ControlKind_Ping ControlKind = 75
)

func (e ControlKind) String() string {
	switch e {
	case ControlKind_Ping:
		return "Ping"
	default:
		return fmt.Sprintf("ControlKind(%d)", e)
	}
}

type tmp352 struct {
	Offset uint16
}

func (v *tmp352) isVariant168() {}

type Variant168 interface {
	isVariant168()
}

type Handshake struct {
	KeyKind       KeyKind
	CommonKeyKind CommonKeyKind
	tmp234        Variant168
	Len           uint16
	KeyShare      []uint8
}

func (h *Handshake) Offset() *uint16 {
	if h.KeyKind == KeyKind_Offset {
		tmp351, ok := h.tmp234.(*tmp352)
		if !ok {
			return nil
		}
		_ = tmp351 // to prevent unused warnings
		return &tmp351.Offset
	}
	return nil
}
func (h *Handshake) SetOffset(tmp331 uint16) bool {
	if h.KeyKind == KeyKind_Offset {
		tmp351, ok := h.tmp234.(*tmp352)
		if !ok {
			tmp351 = &tmp352{}
			h.tmp234 = tmp351
		}
		_ = tmp351 // to prevent unused warnings
		tmp351.Offset = tmp331
		return true
	}
	return false
}

func (h *Handshake) SetKeyShare(tmp383 []uint8) bool {
	if len(tmp383) > int(65535) {
		return false
	}
	h.Len = uint16(len(tmp383))
	h.KeyShare = tmp383
	return true
}

func (h *Handshake) Write(tmp27 io.Writer) error {
	tmp342 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp342[:], uint16(uint16(h.KeyKind)))
	if _, err := tmp27.Write(tmp342[:2]); err != nil {
		return err
	}
	tmp339 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp339[:], uint16(uint16(h.CommonKeyKind)))
	if _, err := tmp27.Write(tmp339[:2]); err != nil {
		return err
	}
	if h.KeyKind == KeyKind_Offset {
		tmp351, ok := h.tmp234.(*tmp352)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp351 // to prevent unused warnings
		tmp337 := [2]uint8{}
		binary.BigEndian.PutUint16(tmp337[:], uint16(tmp351.Offset))
		if _, err := tmp27.Write(tmp337[:2]); err != nil {
			return err
		}
	}
	tmp335 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp335[:], uint16(h.Len))
	if _, err := tmp27.Write(tmp335[:2]); err != nil {
		return err
	}
	if len(h.KeyShare) != int(int(h.Len)) {
		return fmt.Errorf("size mismatch when writing field \"Handshake::KeyShare\": expected %d, got %d", int(int(h.Len)), len(h.KeyShare))
	}
	if _, err := tmp27.Write(h.KeyShare); err != nil {
		return err
	}
	return nil
}
func (s *Handshake) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Handshake) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (h *Handshake) EncodeSlice(tmp27 []byte, tmp27Offset *int) error {
	tmp342 := []uint8{}
	if len(tmp27)-*tmp27Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Handshake::KeyKind\"")
	}
	tmp342 = tmp27[*tmp27Offset : *tmp27Offset+int(2)]
	binary.BigEndian.PutUint16(tmp342[:], uint16(uint16(h.KeyKind)))
	*tmp27Offset += int(2)
	tmp339 := []uint8{}
	if len(tmp27)-*tmp27Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Handshake::CommonKeyKind\"")
	}
	tmp339 = tmp27[*tmp27Offset : *tmp27Offset+int(2)]
	binary.BigEndian.PutUint16(tmp339[:], uint16(uint16(h.CommonKeyKind)))
	*tmp27Offset += int(2)
	if h.KeyKind == KeyKind_Offset {
		tmp351, ok := h.tmp234.(*tmp352)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp351 // to prevent unused warnings
		tmp337 := []uint8{}
		if len(tmp27)-*tmp27Offset < int(2) {
			return errors.New("not enough space to reserve data for field \"Handshake::tmp234::Offset\"")
		}
		tmp337 = tmp27[*tmp27Offset : *tmp27Offset+int(2)]
		binary.BigEndian.PutUint16(tmp337[:], uint16(tmp351.Offset))
		*tmp27Offset += int(2)
	}
	tmp335 := []uint8{}
	if len(tmp27)-*tmp27Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Handshake::Len\"")
	}
	tmp335 = tmp27[*tmp27Offset : *tmp27Offset+int(2)]
	binary.BigEndian.PutUint16(tmp335[:], uint16(h.Len))
	*tmp27Offset += int(2)
	if len(h.KeyShare) != int(int(h.Len)) {
		return fmt.Errorf("size mismatch when writing field \"Handshake::KeyShare\": expected %d, got %d", int(int(h.Len)), len(h.KeyShare))
	}
	if len(tmp27)-*tmp27Offset < int(0+int(h.Len)) {
		return errors.New("not enough space to write for field \"Handshake::KeyShare\"")
	}
	copy(tmp27[*tmp27Offset:*tmp27Offset+int(int(h.Len))], h.KeyShare)
	*tmp27Offset += int(int(h.Len))
	return nil
}
func (s *Handshake) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Handshake) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (h *Handshake) Append(tmp27 []byte) ([]byte, error) {
	tmp342 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp342[:], uint16(uint16(h.KeyKind)))
	tmp27 = append(tmp27, tmp342[:2]...)
	tmp339 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp339[:], uint16(uint16(h.CommonKeyKind)))
	tmp27 = append(tmp27, tmp339[:2]...)
	if h.KeyKind == KeyKind_Offset {
		tmp351, ok := h.tmp234.(*tmp352)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp351 // to prevent unused warnings
		tmp337 := [2]uint8{}
		binary.BigEndian.PutUint16(tmp337[:], uint16(tmp351.Offset))
		tmp27 = append(tmp27, tmp337[:2]...)
	}
	tmp335 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp335[:], uint16(h.Len))
	tmp27 = append(tmp27, tmp335[:2]...)
	if len(h.KeyShare) != int(int(h.Len)) {
		return nil, fmt.Errorf("size mismatch when writing field \"Handshake::KeyShare\": expected %d, got %d", int(int(h.Len)), len(h.KeyShare))
	}
	tmp27 = append(tmp27, h.KeyShare...)
	return tmp27, nil
}
func (s *Handshake) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (h *Handshake) Read(tmp28 io.Reader) error {
	tmp245 := uint16(0)
	tmp406 := [2]uint8{}
	if _, err := io.ReadFull(tmp28, tmp406[0:0+2]); err != nil {
		return err
	}
	tmp245 = binary.BigEndian.Uint16(tmp406[:])
	h.KeyKind = KeyKind(tmp245)
	tmp398 := uint16(0)
	tmp399 := [2]uint8{}
	if _, err := io.ReadFull(tmp28, tmp399[0:0+2]); err != nil {
		return err
	}
	tmp398 = binary.BigEndian.Uint16(tmp399[:])
	h.CommonKeyKind = CommonKeyKind(tmp398)
	if h.KeyKind == KeyKind_Offset {
		tmp351, ok := h.tmp234.(*tmp352)
		if !ok {
			tmp351 = &tmp352{}
			h.tmp234 = tmp351
		}
		_ = tmp351 // to prevent unused warnings
		tmp380 := [2]uint8{}
		if _, err := io.ReadFull(tmp28, tmp380[0:0+2]); err != nil {
			return err
		}
		tmp351.Offset = binary.BigEndian.Uint16(tmp380[:])
	}
	tmp344 := [2]uint8{}
	if _, err := io.ReadFull(tmp28, tmp344[0:0+2]); err != nil {
		return err
	}
	h.Len = binary.BigEndian.Uint16(tmp344[:])
	if seeker, ok := tmp28.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(h.Len)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(h.Len)))
		}
		h.KeyShare = make([]byte, int(h.Len))
		if _, err := io.ReadFull(tmp28, h.KeyShare[0:0+int(h.Len)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_949 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_949, tmp28, int64(int(h.Len))); err != nil {
			return err
		}
		h.KeyShare = io_temp_949.Bytes()
	}
	return nil
}
func (s *Handshake) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Handshake) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (h *Handshake) DecodeSlice(tmp28 []byte, tmp28Offset *int) error {
	tmp245 := uint16(0)
	tmp406 := []uint8{}
	if len(tmp28)-*tmp28Offset < 2 {
		return errors.New("not enough data to read for field \"Handshake::KeyKind\"")
	}
	tmp406 = tmp28[*tmp28Offset : *tmp28Offset+2]
	*tmp28Offset += int(2)
	tmp245 = binary.BigEndian.Uint16(tmp406[:])
	h.KeyKind = KeyKind(tmp245)
	tmp398 := uint16(0)
	tmp399 := []uint8{}
	if len(tmp28)-*tmp28Offset < 2 {
		return errors.New("not enough data to read for field \"Handshake::CommonKeyKind\"")
	}
	tmp399 = tmp28[*tmp28Offset : *tmp28Offset+2]
	*tmp28Offset += int(2)
	tmp398 = binary.BigEndian.Uint16(tmp399[:])
	h.CommonKeyKind = CommonKeyKind(tmp398)
	if h.KeyKind == KeyKind_Offset {
		tmp351, ok := h.tmp234.(*tmp352)
		if !ok {
			tmp351 = &tmp352{}
			h.tmp234 = tmp351
		}
		_ = tmp351 // to prevent unused warnings
		tmp380 := []uint8{}
		if len(tmp28)-*tmp28Offset < 2 {
			return errors.New("not enough data to read for field \"Handshake::tmp234::Offset\"")
		}
		tmp380 = tmp28[*tmp28Offset : *tmp28Offset+2]
		*tmp28Offset += int(2)
		tmp351.Offset = binary.BigEndian.Uint16(tmp380[:])
	}
	tmp344 := []uint8{}
	if len(tmp28)-*tmp28Offset < 2 {
		return errors.New("not enough data to read for field \"Handshake::Len\"")
	}
	tmp344 = tmp28[*tmp28Offset : *tmp28Offset+2]
	*tmp28Offset += int(2)
	h.Len = binary.BigEndian.Uint16(tmp344[:])
	if len(tmp28)-*tmp28Offset < int(h.Len) {
		return errors.New("not enough data to read for field \"Handshake::KeyShare\"")
	}
	h.KeyShare = tmp28[*tmp28Offset : *tmp28Offset+int(h.Len)]
	*tmp28Offset += int(int(h.Len))
	return nil
}
func (s *Handshake) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Handshake) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func (h *PacketHeader) KeyPhase() bool {
	intVal := h.keyPhase()
	return intVal != 0
}
func (p *PacketHeader) keyPhase() uint8 {
	return uint8(((p.tmp78 >> uint8(7)) & uint8(1)))
}

func (p *PacketHeader) SetKeyPhase(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return p.setKeyPhase(intVal)
}
func (p *PacketHeader) setKeyPhase(tmp347 uint8) bool {
	p.tmp78 = (p.tmp78 & (^(uint8(1) << uint8(7)))) | ((uint8(tmp347) & uint8(1)) << uint8(7))
	return true
}

func (p *PacketHeader) MaskSeed() uint8 {
	return uint8(((p.tmp78 >> uint8(0)) & uint8(127)))
}

func (p *PacketHeader) SetMaskSeed(tmp341 uint8) bool {
	p.tmp78 = (p.tmp78 & (^(uint8(127) << uint8(0)))) | ((uint8(tmp341) & uint8(127)) << uint8(0))
	return true
}

type PacketHeader struct {
	tmp78              uint8
	MaskedKind         uint8
	MaskedConnectionId uint16
	Len                uint16
}

func (p *PacketHeader) Write(tmp30 io.Writer) error {
	tmp356 := [1]uint8{}
	tmp356[0] = uint8((p.keyPhase() & 1)) << uint8(7)
	tmp356[0] = tmp356[0] | uint8((p.MaskSeed() & 127))
	if _, err := tmp30.Write(tmp356[:1]); err != nil {
		return err
	}
	tmp318 := [1]uint8{}
	tmp318[0] = p.MaskedKind
	if _, err := tmp30.Write(tmp318[:1]); err != nil {
		return err
	}
	tmp315 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp315[:], uint16(p.MaskedConnectionId))
	if _, err := tmp30.Write(tmp315[:2]); err != nil {
		return err
	}
	tmp313 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp313[:], uint16(p.Len))
	if _, err := tmp30.Write(tmp313[:2]); err != nil {
		return err
	}
	return nil
}
func (s *PacketHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PacketHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) EncodeSlice(tmp30 []byte, tmp30Offset *int) error {
	tmp356 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::MaskSeed\"")
	}
	tmp356 = tmp30[*tmp30Offset : *tmp30Offset+int(1)]
	tmp356[0] = uint8((p.keyPhase() & 1)) << uint8(7)
	tmp356[0] = tmp356[0] | uint8((p.MaskSeed() & 127))
	*tmp30Offset += int(1)
	tmp318 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::MaskedKind\"")
	}
	tmp318 = tmp30[*tmp30Offset : *tmp30Offset+int(1)]
	tmp318[0] = p.MaskedKind
	*tmp30Offset += int(1)
	tmp315 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::MaskedConnectionId\"")
	}
	tmp315 = tmp30[*tmp30Offset : *tmp30Offset+int(2)]
	binary.BigEndian.PutUint16(tmp315[:], uint16(p.MaskedConnectionId))
	*tmp30Offset += int(2)
	tmp313 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::Len\"")
	}
	tmp313 = tmp30[*tmp30Offset : *tmp30Offset+int(2)]
	binary.BigEndian.PutUint16(tmp313[:], uint16(p.Len))
	*tmp30Offset += int(2)
	return nil
}
func (s *PacketHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PacketHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) Append(tmp30 []byte) ([]byte, error) {
	tmp356 := [1]uint8{}
	tmp356[0] = uint8((p.keyPhase() & 1)) << uint8(7)
	tmp356[0] = tmp356[0] | uint8((p.MaskSeed() & 127))
	tmp30 = append(tmp30, tmp356[:1]...)
	tmp318 := [1]uint8{}
	tmp318[0] = p.MaskedKind
	tmp30 = append(tmp30, tmp318[:1]...)
	tmp315 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp315[:], uint16(p.MaskedConnectionId))
	tmp30 = append(tmp30, tmp315[:2]...)
	tmp313 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp313[:], uint16(p.Len))
	tmp30 = append(tmp30, tmp313[:2]...)
	return tmp30, nil
}
func (s *PacketHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PacketHeader) Read(tmp21 io.Reader) error {
	tmp378 := [1]uint8{}
	if _, err := io.ReadFull(tmp21, tmp378[0:0+1]); err != nil {
		return err
	}
	tmp221 := uint8(0)
	tmp221 = uint8(((tmp378[0] & 128) >> uint8(7)))
	p.setKeyPhase(tmp221)
	tmp371 := uint8(0)
	tmp371 = uint8((tmp378[0] & uint8(127)))
	p.SetMaskSeed(tmp371)
	tmp326 := [1]uint8{}
	if _, err := io.ReadFull(tmp21, tmp326[0:0+1]); err != nil {
		return err
	}
	p.MaskedKind = tmp326[0]
	tmp323 := [2]uint8{}
	if _, err := io.ReadFull(tmp21, tmp323[0:0+2]); err != nil {
		return err
	}
	p.MaskedConnectionId = binary.BigEndian.Uint16(tmp323[:])
	tmp321 := [2]uint8{}
	if _, err := io.ReadFull(tmp21, tmp321[0:0+2]); err != nil {
		return err
	}
	p.Len = binary.BigEndian.Uint16(tmp321[:])
	return nil
}
func (s *PacketHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PacketHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PacketHeader) DecodeSlice(tmp21 []byte, tmp21Offset *int) error {
	tmp378 := []uint8{}
	if len(tmp21)-*tmp21Offset < 1 {
		return errors.New("not enough data to read for field \"tmp153\"")
	}
	tmp378 = tmp21[*tmp21Offset : *tmp21Offset+1]
	*tmp21Offset += int(1)
	tmp221 := uint8(0)
	tmp221 = uint8(((tmp378[0] & 128) >> uint8(7)))
	p.setKeyPhase(tmp221)
	tmp371 := uint8(0)
	tmp371 = uint8((tmp378[0] & uint8(127)))
	p.SetMaskSeed(tmp371)
	tmp326 := []uint8{}
	if len(tmp21)-*tmp21Offset < 1 {
		return errors.New("not enough data to read for field \"PacketHeader::MaskedKind\"")
	}
	tmp326 = tmp21[*tmp21Offset : *tmp21Offset+1]
	*tmp21Offset += int(1)
	p.MaskedKind = tmp326[0]
	tmp323 := []uint8{}
	if len(tmp21)-*tmp21Offset < 2 {
		return errors.New("not enough data to read for field \"PacketHeader::MaskedConnectionId\"")
	}
	tmp323 = tmp21[*tmp21Offset : *tmp21Offset+2]
	*tmp21Offset += int(2)
	p.MaskedConnectionId = binary.BigEndian.Uint16(tmp323[:])
	tmp321 := []uint8{}
	if len(tmp21)-*tmp21Offset < 2 {
		return errors.New("not enough data to read for field \"PacketHeader::Len\"")
	}
	tmp321 = tmp21[*tmp21Offset : *tmp21Offset+2]
	*tmp21Offset += int(2)
	p.Len = binary.BigEndian.Uint16(tmp321[:])
	return nil
}
func (s *PacketHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PacketHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func (p *ProtectedHeader) Control() bool {
	intVal := p.control()
	return intVal != 0
}
func (p *ProtectedHeader) control() uint8 {
	return uint8(((p.tmp70 >> uint64(63)) & uint64(1)))
}

func (p *ProtectedHeader) SetControl(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return p.setControl(intVal)
}
func (p *ProtectedHeader) setControl(tmp309 uint8) bool {
	p.tmp70 = (p.tmp70 & (^(uint64(1) << uint64(63)))) | ((uint64(tmp309) & uint64(1)) << uint64(63))
	return true
}

func (p *ProtectedHeader) NonceCounter() uint64 {
	return uint64(((p.tmp70 >> uint64(0)) & uint64(9223372036854775807)))
}

func (p *ProtectedHeader) SetNonceCounter(tmp307 uint64) bool {
	p.tmp70 = (p.tmp70 & (^(uint64(9223372036854775807) << uint64(0)))) | ((uint64(tmp307) & uint64(9223372036854775807)) << uint64(0))
	return true
}

type ProtectedHeader struct {
	tmp70 uint64
}

func (p *ProtectedHeader) Write(tmp107 io.Writer) error {
	tmp272 := [8]uint8{}
	tmp272[0] = uint8((p.control() & 1)) << uint8(7)
	tmp272[0] = tmp272[0] | uint8(((p.NonceCounter() >> uint64(56)) & uint64(127)))
	tmp272[1] = uint8(((p.NonceCounter() >> uint64(48)) & uint64(255)))
	tmp272[2] = uint8(((p.NonceCounter() >> uint64(40)) & uint64(255)))
	tmp272[3] = uint8(((p.NonceCounter() >> uint64(32)) & uint64(255)))
	tmp272[4] = uint8(((p.NonceCounter() >> uint64(24)) & uint64(255)))
	tmp272[5] = uint8(((p.NonceCounter() >> uint64(16)) & uint64(255)))
	tmp272[6] = uint8(((p.NonceCounter() >> uint64(8)) & uint64(255)))
	tmp272[7] = uint8((p.NonceCounter() & uint64(255)))
	if _, err := tmp107.Write(tmp272[:8]); err != nil {
		return err
	}
	return nil
}
func (s *ProtectedHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *ProtectedHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *ProtectedHeader) EncodeSlice(tmp107 []byte, tmp107Offset *int) error {
	tmp272 := []uint8{}
	if len(tmp107)-*tmp107Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"ProtectedHeader::NonceCounter\"")
	}
	tmp272 = tmp107[*tmp107Offset : *tmp107Offset+int(8)]
	tmp272[0] = uint8((p.control() & 1)) << uint8(7)
	tmp272[0] = tmp272[0] | uint8(((p.NonceCounter() >> uint64(56)) & uint64(127)))
	tmp272[1] = uint8(((p.NonceCounter() >> uint64(48)) & uint64(255)))
	tmp272[2] = uint8(((p.NonceCounter() >> uint64(40)) & uint64(255)))
	tmp272[3] = uint8(((p.NonceCounter() >> uint64(32)) & uint64(255)))
	tmp272[4] = uint8(((p.NonceCounter() >> uint64(24)) & uint64(255)))
	tmp272[5] = uint8(((p.NonceCounter() >> uint64(16)) & uint64(255)))
	tmp272[6] = uint8(((p.NonceCounter() >> uint64(8)) & uint64(255)))
	tmp272[7] = uint8((p.NonceCounter() & uint64(255)))
	*tmp107Offset += int(8)
	return nil
}
func (s *ProtectedHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *ProtectedHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *ProtectedHeader) Append(tmp107 []byte) ([]byte, error) {
	tmp272 := [8]uint8{}
	tmp272[0] = uint8((p.control() & 1)) << uint8(7)
	tmp272[0] = tmp272[0] | uint8(((p.NonceCounter() >> uint64(56)) & uint64(127)))
	tmp272[1] = uint8(((p.NonceCounter() >> uint64(48)) & uint64(255)))
	tmp272[2] = uint8(((p.NonceCounter() >> uint64(40)) & uint64(255)))
	tmp272[3] = uint8(((p.NonceCounter() >> uint64(32)) & uint64(255)))
	tmp272[4] = uint8(((p.NonceCounter() >> uint64(24)) & uint64(255)))
	tmp272[5] = uint8(((p.NonceCounter() >> uint64(16)) & uint64(255)))
	tmp272[6] = uint8(((p.NonceCounter() >> uint64(8)) & uint64(255)))
	tmp272[7] = uint8((p.NonceCounter() & uint64(255)))
	tmp107 = append(tmp107, tmp272[:8]...)
	return tmp107, nil
}
func (s *ProtectedHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *ProtectedHeader) Read(tmp10 io.Reader) error {
	tmp306 := [8]uint8{}
	if _, err := io.ReadFull(tmp10, tmp306[0:0+8]); err != nil {
		return err
	}
	tmp288 := uint8(0)
	tmp288 = uint8(((tmp306[0] & 128) >> uint8(7)))
	p.setControl(tmp288)
	tmp286 := uint64(0)
	tmp286 = (((((((uint64((tmp306[0] & uint8(127))) << uint64(56)) | (uint64(tmp306[1]) << uint64(48))) | (uint64(tmp306[2]) << uint64(40))) | (uint64(tmp306[3]) << uint64(32))) | (uint64(tmp306[4]) << uint64(24))) | (uint64(tmp306[5]) << uint64(16))) | (uint64(tmp306[6]) << uint64(8))) | uint64(tmp306[7])
	p.SetNonceCounter(tmp286)
	return nil
}
func (s *ProtectedHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *ProtectedHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *ProtectedHeader) DecodeSlice(tmp10 []byte, tmp10Offset *int) error {
	tmp306 := []uint8{}
	if len(tmp10)-*tmp10Offset < 8 {
		return errors.New("not enough data to read for field \"tmp16\"")
	}
	tmp306 = tmp10[*tmp10Offset : *tmp10Offset+8]
	*tmp10Offset += int(8)
	tmp288 := uint8(0)
	tmp288 = uint8(((tmp306[0] & 128) >> uint8(7)))
	p.setControl(tmp288)
	tmp286 := uint64(0)
	tmp286 = (((((((uint64((tmp306[0] & uint8(127))) << uint64(56)) | (uint64(tmp306[1]) << uint64(48))) | (uint64(tmp306[2]) << uint64(40))) | (uint64(tmp306[3]) << uint64(32))) | (uint64(tmp306[4]) << uint64(24))) | (uint64(tmp306[5]) << uint64(16))) | (uint64(tmp306[6]) << uint64(8))) | uint64(tmp306[7])
	p.SetNonceCounter(tmp286)
	return nil
}
func (s *ProtectedHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *ProtectedHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type EncryptedData struct {
	NonceCounter uint64
	Data         []uint8
}

func (e *EncryptedData) Write(tmp134 io.Writer) error {
	tmp202 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp202[:], uint64(e.NonceCounter))
	if _, err := tmp134.Write(tmp202[:8]); err != nil {
		return err
	}
	if _, err := tmp134.Write(e.Data); err != nil {
		return err
	}
	return nil
}
func (s *EncryptedData) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *EncryptedData) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (e *EncryptedData) EncodeSlice(tmp134 []byte, tmp134Offset *int) error {
	tmp202 := []uint8{}
	if len(tmp134)-*tmp134Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"EncryptedData::NonceCounter\"")
	}
	tmp202 = tmp134[*tmp134Offset : *tmp134Offset+int(8)]
	binary.BigEndian.PutUint64(tmp202[:], uint64(e.NonceCounter))
	*tmp134Offset += int(8)
	if len(tmp134)-*tmp134Offset < int(0+len(e.Data)) {
		return errors.New("not enough space to write for field \"EncryptedData::Data\"")
	}
	copy(tmp134[*tmp134Offset:*tmp134Offset+int(len(e.Data))], e.Data)
	*tmp134Offset += int(len(e.Data))
	return nil
}
func (s *EncryptedData) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *EncryptedData) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (e *EncryptedData) Append(tmp134 []byte) ([]byte, error) {
	tmp202 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp202[:], uint64(e.NonceCounter))
	tmp134 = append(tmp134, tmp202[:8]...)
	tmp134 = append(tmp134, e.Data...)
	return tmp134, nil
}
func (s *EncryptedData) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (e *EncryptedData) Read(tmp105 io.Reader) error {
	tmp211 := [8]uint8{}
	if _, err := io.ReadFull(tmp105, tmp211[0:0+8]); err != nil {
		return err
	}
	e.NonceCounter = binary.BigEndian.Uint64(tmp211[:])
	{
		var readErr error
		e.Data, readErr = io.ReadAll(tmp105)
		if readErr != nil {
			return readErr
		}
	}
	return nil
}
func (s *EncryptedData) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *EncryptedData) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (e *EncryptedData) DecodeSlice(tmp105 []byte, tmp105Offset *int) error {
	tmp211 := []uint8{}
	if len(tmp105)-*tmp105Offset < 8 {
		return errors.New("not enough data to read for field \"EncryptedData::NonceCounter\"")
	}
	tmp211 = tmp105[*tmp105Offset : *tmp105Offset+8]
	*tmp105Offset += int(8)
	e.NonceCounter = binary.BigEndian.Uint64(tmp211[:])
	e.Data = tmp105[*tmp105Offset:]
	*tmp105Offset += len(e.Data)
	return nil
}
func (s *EncryptedData) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *EncryptedData) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Packet struct {
	Header PacketHeader
	Data   []uint8
}

func (p *Packet) SetData(tmp249 []uint8) bool {
	if len(tmp249) > int(65535) {
		return false
	}
	p.Header.Len = uint16(len(tmp249))
	p.Data = tmp249
	return true
}

func (p *Packet) Write(tmp130 io.Writer) error {
	tmp254 := p.Header.Write(tmp130)
	if tmp254 != nil {
		return tmp254
	}
	if len(p.Data) != int(int(p.Header.Len)) {
		return fmt.Errorf("size mismatch when writing field \"Packet::Data\": expected %d, got %d", int(int(p.Header.Len)), len(p.Data))
	}
	if _, err := tmp130.Write(p.Data); err != nil {
		return err
	}
	return nil
}
func (s *Packet) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Packet) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Packet) EncodeSlice(tmp130 []byte, tmp130Offset *int) error {
	tmp254 := p.Header.EncodeSlice(tmp130, tmp130Offset)
	if tmp254 != nil {
		return tmp254
	}
	if len(p.Data) != int(int(p.Header.Len)) {
		return fmt.Errorf("size mismatch when writing field \"Packet::Data\": expected %d, got %d", int(int(p.Header.Len)), len(p.Data))
	}
	if len(tmp130)-*tmp130Offset < int(0+int(p.Header.Len)) {
		return errors.New("not enough space to write for field \"Packet::Data\"")
	}
	copy(tmp130[*tmp130Offset:*tmp130Offset+int(int(p.Header.Len))], p.Data)
	*tmp130Offset += int(int(p.Header.Len))
	return nil
}
func (s *Packet) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Packet) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Packet) Append(tmp130 []byte) ([]byte, error) {
	var tmp254 error
	tmp130, tmp254 = p.Header.Append(tmp130)

	if tmp254 != nil {
		return nil, tmp254
	}
	if len(p.Data) != int(int(p.Header.Len)) {
		return nil, fmt.Errorf("size mismatch when writing field \"Packet::Data\": expected %d, got %d", int(int(p.Header.Len)), len(p.Data))
	}
	tmp130 = append(tmp130, p.Data...)
	return tmp130, nil
}
func (s *Packet) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *Packet) Read(tmp132 io.Reader) error {
	tmp257 := p.Header.Read(tmp132)
	if tmp257 != nil {
		return tmp257
	}
	if seeker, ok := tmp132.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(p.Header.Len)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(p.Header.Len)))
		}
		p.Data = make([]byte, int(p.Header.Len))
		if _, err := io.ReadFull(tmp132, p.Data[0:0+int(p.Header.Len)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_448 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_448, tmp132, int64(int(p.Header.Len))); err != nil {
			return err
		}
		p.Data = io_temp_448.Bytes()
	}
	return nil
}
func (s *Packet) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Packet) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *Packet) DecodeSlice(tmp132 []byte, tmp132Offset *int) error {
	tmp257 := p.Header.DecodeSlice(tmp132, tmp132Offset)
	if tmp257 != nil {
		return tmp257
	}
	if len(tmp132)-*tmp132Offset < int(p.Header.Len) {
		return errors.New("not enough data to read for field \"Packet::Data\"")
	}
	p.Data = tmp132[*tmp132Offset : *tmp132Offset+int(p.Header.Len)]
	*tmp132Offset += int(int(p.Header.Len))
	return nil
}
func (s *Packet) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Packet) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
