// Code generated by ebm2go at https://github.com/on-keyday/rebrgen, DO NOT EDIT.
package packet

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
)

/* config.go.package("packet")*/
type IPAddress struct {
	Len     uint8
	Address []uint8
}

func (i *IPAddress) SetAddress(tmp364 []uint8) bool {
	if len(tmp364) > int(255) {
		return false
	}
	i.Len = uint8(len(tmp364))
	i.Address = tmp364
	return true
}

func (i *IPAddress) Write(tmp175 io.Writer) error {
	tmp175ByteIO, _ := tmp175.(io.ByteWriter)
	_ = tmp175ByteIO
	if tmp175ByteIO != nil {
		if err := tmp175ByteIO.WriteByte(i.Len); err != nil {
			return err
		}
	} else {
		if _, err := tmp175.Write([]byte{i.Len}); err != nil {
			return err
		}
	}
	if !((i.Len == 4) || (i.Len == 16)) {
		return errors.New("Assertion failed")
	}
	if len(i.Address) != int(i.Len) {
		return fmt.Errorf("size mismatch when writing field \"IPAddress::Address\": expected %d, got %d", int(i.Len), len(i.Address))
	}
	if _, err := tmp175.Write(i.Address); err != nil {
		return err
	}
	return nil
}
func (s *IPAddress) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *IPAddress) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (i *IPAddress) EncodeSlice(tmp175 []byte, tmp175Offset *int) error {
	tmp174 := []uint8{}
	if len(tmp175)-*tmp175Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"IPAddress::Len\"")
	}
	tmp174 = tmp175[*tmp175Offset : *tmp175Offset+int(1)]
	tmp174[0] = i.Len
	*tmp175Offset += int(1)
	if !((i.Len == 4) || (i.Len == 16)) {
		return errors.New("Assertion failed")
	}
	if len(i.Address) != int(i.Len) {
		return fmt.Errorf("size mismatch when writing field \"IPAddress::Address\": expected %d, got %d", int(i.Len), len(i.Address))
	}
	if len(tmp175)-*tmp175Offset < int(0+i.Len) {
		return errors.New("not enough space to write for field \"IPAddress::Address\"")
	}
	copy(tmp175[*tmp175Offset:*tmp175Offset+int(i.Len)], i.Address)
	*tmp175Offset += int(i.Len)
	return nil
}
func (s *IPAddress) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *IPAddress) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (i *IPAddress) Append(tmp175 []byte) ([]byte, error) {
	tmp174 := [1]uint8{}
	tmp174[0] = i.Len
	tmp175 = append(tmp175, tmp174[:1]...)
	if !((i.Len == 4) || (i.Len == 16)) {
		return nil, errors.New("Assertion failed")
	}
	if len(i.Address) != int(i.Len) {
		return nil, fmt.Errorf("size mismatch when writing field \"IPAddress::Address\": expected %d, got %d", int(i.Len), len(i.Address))
	}
	tmp175 = append(tmp175, i.Address...)
	return tmp175, nil
}
func (s *IPAddress) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (i *IPAddress) Read(tmp183 io.Reader) error {
	tmp183ByteIO, _ := tmp183.(io.ByteReader)
	_ = tmp183ByteIO
	if tmp183ByteIO != nil {
		var err error
		i.Len, err = tmp183ByteIO.ReadByte()
		if err != nil {
			return err
		}
	} else {
		var err error
		var n int
		buf := [1]byte{0}
		if n, err = io.ReadFull(tmp183, buf[:]); err != nil {
			return err
		}
		if n != 1 {
			return fmt.Errorf("failed to read byte for field \"IPAddress::Len\": expected to read 1 byte, but read %d bytes", n)
		}
		i.Len = buf[0]
	}
	if !((i.Len == 4) || (i.Len == 16)) {
		return errors.New("Assertion failed")
	}
	if seeker, ok := tmp183.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(i.Len)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(i.Len)))
		}
		i.Address = make([]byte, int(i.Len))
		if _, err := io.ReadFull(tmp183, i.Address[0:0+int(i.Len)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_1135 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_1135, tmp183, int64(int(i.Len))); err != nil {
			return err
		}
		i.Address = io_temp_1135.Bytes()
	}
	return nil
}
func (s *IPAddress) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *IPAddress) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (i *IPAddress) DecodeSlice(tmp183 []byte, tmp183Offset *int) error {
	tmp28 := []uint8{}
	if len(tmp183)-*tmp183Offset < 1 {
		return errors.New("not enough data to read for field \"IPAddress::Len\"")
	}
	tmp28 = tmp183[*tmp183Offset : *tmp183Offset+1]
	*tmp183Offset += int(1)
	i.Len = tmp28[0]
	if !((i.Len == 4) || (i.Len == 16)) {
		return errors.New("Assertion failed")
	}
	if len(tmp183)-*tmp183Offset < int(i.Len) {
		return errors.New("not enough data to read for field \"IPAddress::Address\"")
	}
	i.Address = tmp183[*tmp183Offset : *tmp183Offset+int(i.Len)]
	*tmp183Offset += int(int(i.Len))
	return nil
}
func (s *IPAddress) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *IPAddress) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type MacAddress struct {
	Address [6]uint8
}

func (m *MacAddress) Write(tmp344 io.Writer) error {
	if _, err := tmp344.Write(m.Address[:6]); err != nil {
		return err
	}
	return nil
}
func (s *MacAddress) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *MacAddress) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (m *MacAddress) EncodeSlice(tmp344 []byte, tmp344Offset *int) error {
	if len(tmp344)-*tmp344Offset < int(6) {
		return errors.New("not enough space to write for field \"MacAddress::Address\"")
	}
	copy(tmp344[*tmp344Offset:*tmp344Offset+int(6)], m.Address[:])
	*tmp344Offset += int(6)
	return nil
}
func (s *MacAddress) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *MacAddress) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (m *MacAddress) Append(tmp344 []byte) ([]byte, error) {
	tmp344 = append(tmp344, m.Address[:6]...)
	return tmp344, nil
}
func (s *MacAddress) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (m *MacAddress) Read(tmp348 io.Reader) error {
	if _, err := io.ReadFull(tmp348, m.Address[0:0+6]); err != nil {
		return err
	}
	return nil
}
func (s *MacAddress) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *MacAddress) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (m *MacAddress) DecodeSlice(tmp348 []byte, tmp348Offset *int) error {
	if len(tmp348)-*tmp348Offset < 6 {
		return errors.New("not enough data to read for field \"MacAddress::Address\"")
	}
	copy(m.Address[:], tmp348[*tmp348Offset:*tmp348Offset+6])
	*tmp348Offset += int(6)
	return nil
}
func (s *MacAddress) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *MacAddress) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Probe struct {
	MacAddress MacAddress
	IpAddress  IPAddress
	Port       uint16
}

func (p *Probe) Write(tmp94 io.Writer) error {
	tmp333 := p.MacAddress.Write(tmp94)
	if tmp333 != nil {
		return tmp333
	}
	tmp330 := p.IpAddress.Write(tmp94)
	if tmp330 != nil {
		return tmp330
	}
	tmp51 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp51[:], uint16(p.Port))
	if _, err := tmp94.Write(tmp51[:2]); err != nil {
		return err
	}
	return nil
}
func (s *Probe) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Probe) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Probe) EncodeSlice(tmp94 []byte, tmp94Offset *int) error {
	tmp333 := p.MacAddress.EncodeSlice(tmp94, tmp94Offset)
	if tmp333 != nil {
		return tmp333
	}
	tmp330 := p.IpAddress.EncodeSlice(tmp94, tmp94Offset)
	if tmp330 != nil {
		return tmp330
	}
	tmp51 := []uint8{}
	if len(tmp94)-*tmp94Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Probe::Port\"")
	}
	tmp51 = tmp94[*tmp94Offset : *tmp94Offset+int(2)]
	binary.BigEndian.PutUint16(tmp51[:], uint16(p.Port))
	*tmp94Offset += int(2)
	return nil
}
func (s *Probe) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Probe) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Probe) Append(tmp94 []byte) ([]byte, error) {
	var tmp333 error
	tmp94, tmp333 = p.MacAddress.Append(tmp94)

	if tmp333 != nil {
		return nil, tmp333
	}
	var tmp330 error
	tmp94, tmp330 = p.IpAddress.Append(tmp94)

	if tmp330 != nil {
		return nil, tmp330
	}
	tmp51 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp51[:], uint16(p.Port))
	tmp94 = append(tmp94, tmp51[:2]...)
	return tmp94, nil
}
func (s *Probe) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *Probe) Read(tmp97 io.Reader) error {
	tmp362 := p.MacAddress.Read(tmp97)
	if tmp362 != nil {
		return tmp362
	}
	tmp338 := p.IpAddress.Read(tmp97)
	if tmp338 != nil {
		return tmp338
	}
	tmp59 := [2]uint8{}
	if _, err := io.ReadFull(tmp97, tmp59[0:0+2]); err != nil {
		return err
	}
	p.Port = binary.BigEndian.Uint16(tmp59[:])
	return nil
}
func (s *Probe) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Probe) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *Probe) DecodeSlice(tmp97 []byte, tmp97Offset *int) error {
	tmp362 := p.MacAddress.DecodeSlice(tmp97, tmp97Offset)
	if tmp362 != nil {
		return tmp362
	}
	tmp338 := p.IpAddress.DecodeSlice(tmp97, tmp97Offset)
	if tmp338 != nil {
		return tmp338
	}
	tmp59 := []uint8{}
	if len(tmp97)-*tmp97Offset < 2 {
		return errors.New("not enough data to read for field \"Probe::Port\"")
	}
	tmp59 = tmp97[*tmp97Offset : *tmp97Offset+2]
	*tmp97Offset += int(2)
	p.Port = binary.BigEndian.Uint16(tmp59[:])
	return nil
}
func (s *Probe) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Probe) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type KeyKind uint16

const (
	KeyKind_Offset KeyKind = 24
	KeyKind_X25519 KeyKind = 52
	KeyKind_P256   KeyKind = 249
	KeyKind_P384   KeyKind = 36
	KeyKind_P521   KeyKind = 51
)

func (e KeyKind) String() string {
	switch e {
	case KeyKind_Offset:
		return "Offset"
	case KeyKind_X25519:
		return "X25519"
	case KeyKind_P256:
		return "P256"
	case KeyKind_P384:
		return "P384"
	case KeyKind_P521:
		return "P521"
	default:
		return fmt.Sprintf("KeyKind(%d)", e)
	}
}

type CommonKeyKind uint16

const (
	CommonKeyKind_Aes128Gcm        CommonKeyKind = 115
	CommonKeyKind_Aes192Gcm        CommonKeyKind = 67
	CommonKeyKind_Aes256Gcm        CommonKeyKind = 34
	CommonKeyKind_Chacha20Poly1305 CommonKeyKind = 62
)

func (e CommonKeyKind) String() string {
	switch e {
	case CommonKeyKind_Aes128Gcm:
		return "Aes128Gcm"
	case CommonKeyKind_Aes192Gcm:
		return "Aes192Gcm"
	case CommonKeyKind_Aes256Gcm:
		return "Aes256Gcm"
	case CommonKeyKind_Chacha20Poly1305:
		return "Chacha20Poly1305"
	default:
		return fmt.Sprintf("CommonKeyKind(%d)", e)
	}
}

type PacketKind uint8

const (
	PacketKind_Handshake    PacketKind = 94
	PacketKind_HandshakeAck PacketKind = 137
	PacketKind_Application  PacketKind = 51
	PacketKind_Probe        PacketKind = 103
)

func (e PacketKind) String() string {
	switch e {
	case PacketKind_Handshake:
		return "Handshake"
	case PacketKind_HandshakeAck:
		return "HandshakeAck"
	case PacketKind_Application:
		return "Application"
	case PacketKind_Probe:
		return "Probe"
	default:
		return fmt.Sprintf("PacketKind(%d)", e)
	}
}

type tmp325 struct {
	Offset uint16
}

func (v *tmp325) isVariant161() {}

type Variant161 interface {
	isVariant161()
}

type Handshake struct {
	KeyKind       KeyKind
	CommonKeyKind CommonKeyKind
	tmp214        Variant161
	Len           uint16
	KeyShare      []uint8
}

func (h *Handshake) Offset() *uint16 {
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp214.(*tmp325)
		if !ok {
			return nil
		}
		_ = tmp324 // to prevent unused warnings
		return &tmp324.Offset
	}
	return nil
}
func (h *Handshake) SetOffset(tmp314 uint16) bool {
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp214.(*tmp325)
		if !ok {
			tmp324 = &tmp325{}
			h.tmp214 = tmp324
		}
		_ = tmp324 // to prevent unused warnings
		tmp324.Offset = tmp314
		return true
	}
	return false
}

func (h *Handshake) SetKeyShare(tmp309 []uint8) bool {
	if len(tmp309) > int(65535) {
		return false
	}
	h.Len = uint16(len(tmp309))
	h.KeyShare = tmp309
	return true
}

func (h *Handshake) Write(tmp23 io.Writer) error {
	tmp316 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp316[:], uint16(uint16(h.KeyKind)))
	if _, err := tmp23.Write(tmp316[:2]); err != nil {
		return err
	}
	tmp313 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp313[:], uint16(uint16(h.CommonKeyKind)))
	if _, err := tmp23.Write(tmp313[:2]); err != nil {
		return err
	}
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp214.(*tmp325)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp324 // to prevent unused warnings
		tmp352 := [2]uint8{}
		binary.BigEndian.PutUint16(tmp352[:], uint16(tmp324.Offset))
		if _, err := tmp23.Write(tmp352[:2]); err != nil {
			return err
		}
	}
	tmp307 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp307[:], uint16(h.Len))
	if _, err := tmp23.Write(tmp307[:2]); err != nil {
		return err
	}
	if len(h.KeyShare) != int(h.Len) {
		return fmt.Errorf("size mismatch when writing field \"Handshake::KeyShare\": expected %d, got %d", int(h.Len), len(h.KeyShare))
	}
	if _, err := tmp23.Write(h.KeyShare); err != nil {
		return err
	}
	return nil
}
func (s *Handshake) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Handshake) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (h *Handshake) EncodeSlice(tmp23 []byte, tmp23Offset *int) error {
	tmp316 := []uint8{}
	if len(tmp23)-*tmp23Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Handshake::KeyKind\"")
	}
	tmp316 = tmp23[*tmp23Offset : *tmp23Offset+int(2)]
	binary.BigEndian.PutUint16(tmp316[:], uint16(uint16(h.KeyKind)))
	*tmp23Offset += int(2)
	tmp313 := []uint8{}
	if len(tmp23)-*tmp23Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Handshake::CommonKeyKind\"")
	}
	tmp313 = tmp23[*tmp23Offset : *tmp23Offset+int(2)]
	binary.BigEndian.PutUint16(tmp313[:], uint16(uint16(h.CommonKeyKind)))
	*tmp23Offset += int(2)
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp214.(*tmp325)
		if !ok {
			return errors.New("invalid union type for encoding")
		}
		_ = tmp324 // to prevent unused warnings
		tmp352 := []uint8{}
		if len(tmp23)-*tmp23Offset < int(2) {
			return errors.New("not enough space to reserve data for field \"Handshake::tmp214::Offset\"")
		}
		tmp352 = tmp23[*tmp23Offset : *tmp23Offset+int(2)]
		binary.BigEndian.PutUint16(tmp352[:], uint16(tmp324.Offset))
		*tmp23Offset += int(2)
	}
	tmp307 := []uint8{}
	if len(tmp23)-*tmp23Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"Handshake::Len\"")
	}
	tmp307 = tmp23[*tmp23Offset : *tmp23Offset+int(2)]
	binary.BigEndian.PutUint16(tmp307[:], uint16(h.Len))
	*tmp23Offset += int(2)
	if len(h.KeyShare) != int(h.Len) {
		return fmt.Errorf("size mismatch when writing field \"Handshake::KeyShare\": expected %d, got %d", int(h.Len), len(h.KeyShare))
	}
	if len(tmp23)-*tmp23Offset < int(0+h.Len) {
		return errors.New("not enough space to write for field \"Handshake::KeyShare\"")
	}
	copy(tmp23[*tmp23Offset:*tmp23Offset+int(h.Len)], h.KeyShare)
	*tmp23Offset += int(h.Len)
	return nil
}
func (s *Handshake) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Handshake) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (h *Handshake) Append(tmp23 []byte) ([]byte, error) {
	tmp316 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp316[:], uint16(uint16(h.KeyKind)))
	tmp23 = append(tmp23, tmp316[:2]...)
	tmp313 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp313[:], uint16(uint16(h.CommonKeyKind)))
	tmp23 = append(tmp23, tmp313[:2]...)
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp214.(*tmp325)
		if !ok {
			return nil, errors.New("invalid union type for encoding")
		}
		_ = tmp324 // to prevent unused warnings
		tmp352 := [2]uint8{}
		binary.BigEndian.PutUint16(tmp352[:], uint16(tmp324.Offset))
		tmp23 = append(tmp23, tmp352[:2]...)
	}
	tmp307 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp307[:], uint16(h.Len))
	tmp23 = append(tmp23, tmp307[:2]...)
	if len(h.KeyShare) != int(h.Len) {
		return nil, fmt.Errorf("size mismatch when writing field \"Handshake::KeyShare\": expected %d, got %d", int(h.Len), len(h.KeyShare))
	}
	tmp23 = append(tmp23, h.KeyShare...)
	return tmp23, nil
}
func (s *Handshake) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (h *Handshake) Read(tmp24 io.Reader) error {
	tmp224 := uint16(0)
	tmp372 := [2]uint8{}
	if _, err := io.ReadFull(tmp24, tmp372[0:0+2]); err != nil {
		return err
	}
	tmp224 = binary.BigEndian.Uint16(tmp372[:])
	h.KeyKind = KeyKind(tmp224)
	tmp356 := uint16(0)
	tmp355 := [2]uint8{}
	if _, err := io.ReadFull(tmp24, tmp355[0:0+2]); err != nil {
		return err
	}
	tmp356 = binary.BigEndian.Uint16(tmp355[:])
	h.CommonKeyKind = CommonKeyKind(tmp356)
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp214.(*tmp325)
		if !ok {
			tmp324 = &tmp325{}
			h.tmp214 = tmp324
		}
		_ = tmp324 // to prevent unused warnings
		tmp347 := [2]uint8{}
		if _, err := io.ReadFull(tmp24, tmp347[0:0+2]); err != nil {
			return err
		}
		tmp324.Offset = binary.BigEndian.Uint16(tmp347[:])
	}
	tmp318 := [2]uint8{}
	if _, err := io.ReadFull(tmp24, tmp318[0:0+2]); err != nil {
		return err
	}
	h.Len = binary.BigEndian.Uint16(tmp318[:])
	if seeker, ok := tmp24.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(h.Len)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(h.Len)))
		}
		h.KeyShare = make([]byte, int(h.Len))
		if _, err := io.ReadFull(tmp24, h.KeyShare[0:0+int(h.Len)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_887 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_887, tmp24, int64(int(h.Len))); err != nil {
			return err
		}
		h.KeyShare = io_temp_887.Bytes()
	}
	return nil
}
func (s *Handshake) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Handshake) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (h *Handshake) DecodeSlice(tmp24 []byte, tmp24Offset *int) error {
	tmp224 := uint16(0)
	tmp372 := []uint8{}
	if len(tmp24)-*tmp24Offset < 2 {
		return errors.New("not enough data to read for field \"Handshake::KeyKind\"")
	}
	tmp372 = tmp24[*tmp24Offset : *tmp24Offset+2]
	*tmp24Offset += int(2)
	tmp224 = binary.BigEndian.Uint16(tmp372[:])
	h.KeyKind = KeyKind(tmp224)
	tmp356 := uint16(0)
	tmp355 := []uint8{}
	if len(tmp24)-*tmp24Offset < 2 {
		return errors.New("not enough data to read for field \"Handshake::CommonKeyKind\"")
	}
	tmp355 = tmp24[*tmp24Offset : *tmp24Offset+2]
	*tmp24Offset += int(2)
	tmp356 = binary.BigEndian.Uint16(tmp355[:])
	h.CommonKeyKind = CommonKeyKind(tmp356)
	if h.KeyKind == KeyKind_Offset {
		tmp324, ok := h.tmp214.(*tmp325)
		if !ok {
			tmp324 = &tmp325{}
			h.tmp214 = tmp324
		}
		_ = tmp324 // to prevent unused warnings
		tmp347 := []uint8{}
		if len(tmp24)-*tmp24Offset < 2 {
			return errors.New("not enough data to read for field \"Handshake::tmp214::Offset\"")
		}
		tmp347 = tmp24[*tmp24Offset : *tmp24Offset+2]
		*tmp24Offset += int(2)
		tmp324.Offset = binary.BigEndian.Uint16(tmp347[:])
	}
	tmp318 := []uint8{}
	if len(tmp24)-*tmp24Offset < 2 {
		return errors.New("not enough data to read for field \"Handshake::Len\"")
	}
	tmp318 = tmp24[*tmp24Offset : *tmp24Offset+2]
	*tmp24Offset += int(2)
	h.Len = binary.BigEndian.Uint16(tmp318[:])
	if len(tmp24)-*tmp24Offset < int(h.Len) {
		return errors.New("not enough data to read for field \"Handshake::KeyShare\"")
	}
	h.KeyShare = tmp24[*tmp24Offset : *tmp24Offset+int(h.Len)]
	*tmp24Offset += int(int(h.Len))
	return nil
}
func (s *Handshake) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Handshake) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type PacketHeader struct {
	Version      uint8
	Kind         PacketKind
	ConnectionId uint16
	Len          uint16
}

func (p *PacketHeader) Write(tmp30 io.Writer) error {
	tmp294 := [1]uint8{}
	tmp294[0] = p.Version
	if _, err := tmp30.Write(tmp294[:1]); err != nil {
		return err
	}
	tmp290 := [1]uint8{}
	tmp290[0] = uint8(p.Kind)
	if _, err := tmp30.Write(tmp290[:1]); err != nil {
		return err
	}
	tmp287 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp287[:], uint16(p.ConnectionId))
	if _, err := tmp30.Write(tmp287[:2]); err != nil {
		return err
	}
	tmp285 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp285[:], uint16(p.Len))
	if _, err := tmp30.Write(tmp285[:2]); err != nil {
		return err
	}
	return nil
}
func (s *PacketHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *PacketHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) EncodeSlice(tmp30 []byte, tmp30Offset *int) error {
	tmp294 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::Version\"")
	}
	tmp294 = tmp30[*tmp30Offset : *tmp30Offset+int(1)]
	tmp294[0] = p.Version
	*tmp30Offset += int(1)
	tmp290 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(1) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::Kind\"")
	}
	tmp290 = tmp30[*tmp30Offset : *tmp30Offset+int(1)]
	tmp290[0] = uint8(p.Kind)
	*tmp30Offset += int(1)
	tmp287 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::ConnectionId\"")
	}
	tmp287 = tmp30[*tmp30Offset : *tmp30Offset+int(2)]
	binary.BigEndian.PutUint16(tmp287[:], uint16(p.ConnectionId))
	*tmp30Offset += int(2)
	tmp285 := []uint8{}
	if len(tmp30)-*tmp30Offset < int(2) {
		return errors.New("not enough space to reserve data for field \"PacketHeader::Len\"")
	}
	tmp285 = tmp30[*tmp30Offset : *tmp30Offset+int(2)]
	binary.BigEndian.PutUint16(tmp285[:], uint16(p.Len))
	*tmp30Offset += int(2)
	return nil
}
func (s *PacketHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *PacketHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *PacketHeader) Append(tmp30 []byte) ([]byte, error) {
	tmp294 := [1]uint8{}
	tmp294[0] = p.Version
	tmp30 = append(tmp30, tmp294[:1]...)
	tmp290 := [1]uint8{}
	tmp290[0] = uint8(p.Kind)
	tmp30 = append(tmp30, tmp290[:1]...)
	tmp287 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp287[:], uint16(p.ConnectionId))
	tmp30 = append(tmp30, tmp287[:2]...)
	tmp285 := [2]uint8{}
	binary.BigEndian.PutUint16(tmp285[:], uint16(p.Len))
	tmp30 = append(tmp30, tmp285[:2]...)
	return tmp30, nil
}
func (s *PacketHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *PacketHeader) Read(tmp31 io.Reader) error {
	tmp302 := [1]uint8{}
	if _, err := io.ReadFull(tmp31, tmp302[0:0+1]); err != nil {
		return err
	}
	p.Version = tmp302[0]
	tmp300 := uint8(0)
	tmp299 := [1]uint8{}
	if _, err := io.ReadFull(tmp31, tmp299[0:0+1]); err != nil {
		return err
	}
	tmp300 = tmp299[0]
	p.Kind = PacketKind(tmp300)
	tmp297 := [2]uint8{}
	if _, err := io.ReadFull(tmp31, tmp297[0:0+2]); err != nil {
		return err
	}
	p.ConnectionId = binary.BigEndian.Uint16(tmp297[:])
	tmp296 := [2]uint8{}
	if _, err := io.ReadFull(tmp31, tmp296[0:0+2]); err != nil {
		return err
	}
	p.Len = binary.BigEndian.Uint16(tmp296[:])
	return nil
}
func (s *PacketHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *PacketHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *PacketHeader) DecodeSlice(tmp31 []byte, tmp31Offset *int) error {
	tmp302 := []uint8{}
	if len(tmp31)-*tmp31Offset < 1 {
		return errors.New("not enough data to read for field \"PacketHeader::Version\"")
	}
	tmp302 = tmp31[*tmp31Offset : *tmp31Offset+1]
	*tmp31Offset += int(1)
	p.Version = tmp302[0]
	tmp300 := uint8(0)
	tmp299 := []uint8{}
	if len(tmp31)-*tmp31Offset < 1 {
		return errors.New("not enough data to read for field \"PacketHeader::Kind\"")
	}
	tmp299 = tmp31[*tmp31Offset : *tmp31Offset+1]
	*tmp31Offset += int(1)
	tmp300 = tmp299[0]
	p.Kind = PacketKind(tmp300)
	tmp297 := []uint8{}
	if len(tmp31)-*tmp31Offset < 2 {
		return errors.New("not enough data to read for field \"PacketHeader::ConnectionId\"")
	}
	tmp297 = tmp31[*tmp31Offset : *tmp31Offset+2]
	*tmp31Offset += int(2)
	p.ConnectionId = binary.BigEndian.Uint16(tmp297[:])
	tmp296 := []uint8{}
	if len(tmp31)-*tmp31Offset < 2 {
		return errors.New("not enough data to read for field \"PacketHeader::Len\"")
	}
	tmp296 = tmp31[*tmp31Offset : *tmp31Offset+2]
	*tmp31Offset += int(2)
	p.Len = binary.BigEndian.Uint16(tmp296[:])
	return nil
}
func (s *PacketHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *PacketHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

func (p *ProtectedHeader) RawPayload() bool {
	intVal := p.rawPayload()
	return intVal != 0
}
func (p *ProtectedHeader) rawPayload() uint8 {
	return uint8(((p.tmp73 >> uint64(63)) & uint64(1)))
}

func (p *ProtectedHeader) SetRawPayload(value bool) bool {
	var intVal uint8
	if value {
		intVal = 1
	} else {
		intVal = 0
	}
	return p.setRawPayload(intVal)
}
func (p *ProtectedHeader) setRawPayload(tmp323 uint8) bool {
	p.tmp73 = (p.tmp73 & (^(uint64(1) << uint64(63)))) | ((uint64(tmp323) & uint64(1)) << uint64(63))
	return true
}

func (p *ProtectedHeader) NonceCounter() uint64 {
	return uint64(((p.tmp73 >> uint64(0)) & uint64(9223372036854775807)))
}

func (p *ProtectedHeader) SetNonceCounter(tmp319 uint64) bool {
	p.tmp73 = (p.tmp73 & (^(uint64(9223372036854775807) << uint64(0)))) | ((uint64(tmp319) & uint64(9223372036854775807)) << uint64(0))
	return true
}

type ProtectedHeader struct {
	tmp73 uint64
}

func (p *ProtectedHeader) Write(tmp107 io.Writer) error {
	tmp250 := [8]uint8{}
	tmp250[0] = uint8((p.rawPayload() & 1)) << uint8(7)
	tmp250[0] = tmp250[0] | uint8(((p.NonceCounter() >> uint64(56)) & uint64(127)))
	tmp250[1] = uint8(((p.NonceCounter() >> uint64(48)) & uint64(255)))
	tmp250[2] = uint8(((p.NonceCounter() >> uint64(40)) & uint64(255)))
	tmp250[3] = uint8(((p.NonceCounter() >> uint64(32)) & uint64(255)))
	tmp250[4] = uint8(((p.NonceCounter() >> uint64(24)) & uint64(255)))
	tmp250[5] = uint8(((p.NonceCounter() >> uint64(16)) & uint64(255)))
	tmp250[6] = uint8(((p.NonceCounter() >> uint64(8)) & uint64(255)))
	tmp250[7] = uint8((p.NonceCounter() & uint64(255)))
	if _, err := tmp107.Write(tmp250[:8]); err != nil {
		return err
	}
	return nil
}
func (s *ProtectedHeader) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *ProtectedHeader) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *ProtectedHeader) EncodeSlice(tmp107 []byte, tmp107Offset *int) error {
	tmp250 := []uint8{}
	if len(tmp107)-*tmp107Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"ProtectedHeader::NonceCounter\"")
	}
	tmp250 = tmp107[*tmp107Offset : *tmp107Offset+int(8)]
	tmp250[0] = uint8((p.rawPayload() & 1)) << uint8(7)
	tmp250[0] = tmp250[0] | uint8(((p.NonceCounter() >> uint64(56)) & uint64(127)))
	tmp250[1] = uint8(((p.NonceCounter() >> uint64(48)) & uint64(255)))
	tmp250[2] = uint8(((p.NonceCounter() >> uint64(40)) & uint64(255)))
	tmp250[3] = uint8(((p.NonceCounter() >> uint64(32)) & uint64(255)))
	tmp250[4] = uint8(((p.NonceCounter() >> uint64(24)) & uint64(255)))
	tmp250[5] = uint8(((p.NonceCounter() >> uint64(16)) & uint64(255)))
	tmp250[6] = uint8(((p.NonceCounter() >> uint64(8)) & uint64(255)))
	tmp250[7] = uint8((p.NonceCounter() & uint64(255)))
	*tmp107Offset += int(8)
	return nil
}
func (s *ProtectedHeader) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *ProtectedHeader) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *ProtectedHeader) Append(tmp107 []byte) ([]byte, error) {
	tmp250 := [8]uint8{}
	tmp250[0] = uint8((p.rawPayload() & 1)) << uint8(7)
	tmp250[0] = tmp250[0] | uint8(((p.NonceCounter() >> uint64(56)) & uint64(127)))
	tmp250[1] = uint8(((p.NonceCounter() >> uint64(48)) & uint64(255)))
	tmp250[2] = uint8(((p.NonceCounter() >> uint64(40)) & uint64(255)))
	tmp250[3] = uint8(((p.NonceCounter() >> uint64(32)) & uint64(255)))
	tmp250[4] = uint8(((p.NonceCounter() >> uint64(24)) & uint64(255)))
	tmp250[5] = uint8(((p.NonceCounter() >> uint64(16)) & uint64(255)))
	tmp250[6] = uint8(((p.NonceCounter() >> uint64(8)) & uint64(255)))
	tmp250[7] = uint8((p.NonceCounter() & uint64(255)))
	tmp107 = append(tmp107, tmp250[:8]...)
	return tmp107, nil
}
func (s *ProtectedHeader) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *ProtectedHeader) Read(tmp8 io.Reader) error {
	tmp346 := [8]uint8{}
	if _, err := io.ReadFull(tmp8, tmp346[0:0+8]); err != nil {
		return err
	}
	tmp268 := uint8(0)
	tmp268 = uint8(((tmp346[0] & 128) >> uint8(7)))
	p.setRawPayload(tmp268)
	tmp265 := uint64(0)
	tmp265 = (((((((uint64((tmp346[0] & uint8(127))) << uint64(56)) | (uint64(tmp346[1]) << uint64(48))) | (uint64(tmp346[2]) << uint64(40))) | (uint64(tmp346[3]) << uint64(32))) | (uint64(tmp346[4]) << uint64(24))) | (uint64(tmp346[5]) << uint64(16))) | (uint64(tmp346[6]) << uint64(8))) | uint64(tmp346[7])
	p.SetNonceCounter(tmp265)
	return nil
}
func (s *ProtectedHeader) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *ProtectedHeader) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *ProtectedHeader) DecodeSlice(tmp8 []byte, tmp8Offset *int) error {
	tmp346 := []uint8{}
	if len(tmp8)-*tmp8Offset < 8 {
		return errors.New("not enough data to read for field \"tmp15\"")
	}
	tmp346 = tmp8[*tmp8Offset : *tmp8Offset+8]
	*tmp8Offset += int(8)
	tmp268 := uint8(0)
	tmp268 = uint8(((tmp346[0] & 128) >> uint8(7)))
	p.setRawPayload(tmp268)
	tmp265 := uint64(0)
	tmp265 = (((((((uint64((tmp346[0] & uint8(127))) << uint64(56)) | (uint64(tmp346[1]) << uint64(48))) | (uint64(tmp346[2]) << uint64(40))) | (uint64(tmp346[3]) << uint64(32))) | (uint64(tmp346[4]) << uint64(24))) | (uint64(tmp346[5]) << uint64(16))) | (uint64(tmp346[6]) << uint64(8))) | uint64(tmp346[7])
	p.SetNonceCounter(tmp265)
	return nil
}
func (s *ProtectedHeader) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *ProtectedHeader) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type EncryptedData struct {
	NonceCounter uint64
	Data         []uint8
}

func (e *EncryptedData) Write(tmp129 io.Writer) error {
	tmp192 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp192[:], uint64(e.NonceCounter))
	if _, err := tmp129.Write(tmp192[:8]); err != nil {
		return err
	}
	if _, err := tmp129.Write(e.Data); err != nil {
		return err
	}
	return nil
}
func (s *EncryptedData) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *EncryptedData) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (e *EncryptedData) EncodeSlice(tmp129 []byte, tmp129Offset *int) error {
	tmp192 := []uint8{}
	if len(tmp129)-*tmp129Offset < int(8) {
		return errors.New("not enough space to reserve data for field \"EncryptedData::NonceCounter\"")
	}
	tmp192 = tmp129[*tmp129Offset : *tmp129Offset+int(8)]
	binary.BigEndian.PutUint64(tmp192[:], uint64(e.NonceCounter))
	*tmp129Offset += int(8)
	if len(tmp129)-*tmp129Offset < int(0+len(e.Data)) {
		return errors.New("not enough space to write for field \"EncryptedData::Data\"")
	}
	copy(tmp129[*tmp129Offset:*tmp129Offset+int(len(e.Data))], e.Data)
	*tmp129Offset += int(len(e.Data))
	return nil
}
func (s *EncryptedData) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *EncryptedData) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (e *EncryptedData) Append(tmp129 []byte) ([]byte, error) {
	tmp192 := [8]uint8{}
	binary.BigEndian.PutUint64(tmp192[:], uint64(e.NonceCounter))
	tmp129 = append(tmp129, tmp192[:8]...)
	tmp129 = append(tmp129, e.Data...)
	return tmp129, nil
}
func (s *EncryptedData) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (e *EncryptedData) Read(tmp105 io.Reader) error {
	tmp222 := [8]uint8{}
	if _, err := io.ReadFull(tmp105, tmp222[0:0+8]); err != nil {
		return err
	}
	e.NonceCounter = binary.BigEndian.Uint64(tmp222[:])
	{
		var readErr error
		e.Data, readErr = io.ReadAll(tmp105)
		if readErr != nil {
			return readErr
		}
	}
	return nil
}
func (s *EncryptedData) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *EncryptedData) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (e *EncryptedData) DecodeSlice(tmp105 []byte, tmp105Offset *int) error {
	tmp222 := []uint8{}
	if len(tmp105)-*tmp105Offset < 8 {
		return errors.New("not enough data to read for field \"EncryptedData::NonceCounter\"")
	}
	tmp222 = tmp105[*tmp105Offset : *tmp105Offset+8]
	*tmp105Offset += int(8)
	e.NonceCounter = binary.BigEndian.Uint64(tmp222[:])
	e.Data = tmp105[*tmp105Offset:]
	*tmp105Offset += len(e.Data)
	return nil
}
func (s *EncryptedData) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *EncryptedData) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}

type Packet struct {
	Header PacketHeader
	Data   []uint8
}

func (p *Packet) SetData(tmp229 []uint8) bool {
	if len(tmp229) > int(65535) {
		return false
	}
	p.Header.Len = uint16(len(tmp229))
	p.Data = tmp229
	return true
}

func (p *Packet) Write(tmp125 io.Writer) error {
	tmp233 := p.Header.Write(tmp125)
	if tmp233 != nil {
		return tmp233
	}
	if len(p.Data) != int(p.Header.Len) {
		return fmt.Errorf("size mismatch when writing field \"Packet::Data\": expected %d, got %d", int(p.Header.Len), len(p.Data))
	}
	if _, err := tmp125.Write(p.Data); err != nil {
		return err
	}
	return nil
}
func (s *Packet) EncodeCopy(reserved []byte) ([]byte, error) {
	buf := bytes.NewBuffer(reserved)
	err := s.Write(buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (s *Packet) MustEncodeCopy(reserved []byte) []byte {
	buf, err := s.EncodeCopy(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Packet) EncodeSlice(tmp125 []byte, tmp125Offset *int) error {
	tmp233 := p.Header.EncodeSlice(tmp125, tmp125Offset)
	if tmp233 != nil {
		return tmp233
	}
	if len(p.Data) != int(p.Header.Len) {
		return fmt.Errorf("size mismatch when writing field \"Packet::Data\": expected %d, got %d", int(p.Header.Len), len(p.Data))
	}
	if len(tmp125)-*tmp125Offset < int(0+p.Header.Len) {
		return errors.New("not enough space to write for field \"Packet::Data\"")
	}
	copy(tmp125[*tmp125Offset:*tmp125Offset+int(p.Header.Len)], p.Data)
	*tmp125Offset += int(p.Header.Len)
	return nil
}
func (s *Packet) Encode(buf []byte) ([]byte, error) {
	var offset int
	err := s.EncodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[:offset], nil
}
func (s *Packet) MustEncode(reserved []byte) []byte {
	buf, err := s.Encode(reserved)
	if err != nil {
		panic(err)
	}
	return buf
}
func (p *Packet) Append(tmp125 []byte) ([]byte, error) {
	var tmp233 error
	tmp125, tmp233 = p.Header.Append(tmp125)

	if tmp233 != nil {
		return nil, tmp233
	}
	if len(p.Data) != int(p.Header.Len) {
		return nil, fmt.Errorf("size mismatch when writing field \"Packet::Data\": expected %d, got %d", int(p.Header.Len), len(p.Data))
	}
	tmp125 = append(tmp125, p.Data...)
	return tmp125, nil
}
func (s *Packet) MustAppend(buf []byte) []byte {
	var err error
	buf, err = s.Append(buf)
	if err != nil {
		panic(err)
	}
	return buf
}

func (p *Packet) Read(tmp127 io.Reader) error {
	tmp236 := p.Header.Read(tmp127)
	if tmp236 != nil {
		return tmp236
	}
	if seeker, ok := tmp127.(io.Seeker); ok {
		current, err := seeker.Seek(0, io.SeekCurrent)
		if err != nil {
			return err
		}
		endOffset, err := seeker.Seek(0, io.SeekEnd)
		if err != nil {
			return err
		}
		_, err = seeker.Seek(current, io.SeekStart)
		if err != nil {
			return err
		}
		if (endOffset - current) < int64(int(p.Header.Len)) {
			return fmt.Errorf("Too large length requested: %d < %d", endOffset-current, int64(int(p.Header.Len)))
		}
		p.Data = make([]byte, int(p.Header.Len))
		if _, err := io.ReadFull(tmp127, p.Data[0:0+int(p.Header.Len)]); err != nil {
			return err
		}
	} else {
		// To mitigate DoS attack, use incremental buffer allocation
		// for more performance, use (assert on DSL or safe-len-limit option) and trust-input-len option
		io_temp_411 := bytes.NewBuffer(nil)
		if _, err := io.CopyN(io_temp_411, tmp127, int64(int(p.Header.Len))); err != nil {
			return err
		}
		p.Data = io_temp_411.Bytes()
	}
	return nil
}
func (s *Packet) DecodeCopy(buf []byte) ([]byte, error) {
	r := bytes.NewReader(buf)
	err := s.Read(r)
	if err != nil {
		return nil, err
	}
	return buf[int(r.Size())-r.Len():], nil
}
func (s *Packet) DecodeExactCopy(buf []byte) error {
	remain, err := s.DecodeCopy(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
func (p *Packet) DecodeSlice(tmp127 []byte, tmp127Offset *int) error {
	tmp236 := p.Header.DecodeSlice(tmp127, tmp127Offset)
	if tmp236 != nil {
		return tmp236
	}
	if len(tmp127)-*tmp127Offset < int(p.Header.Len) {
		return errors.New("not enough data to read for field \"Packet::Data\"")
	}
	p.Data = tmp127[*tmp127Offset : *tmp127Offset+int(p.Header.Len)]
	*tmp127Offset += int(int(p.Header.Len))
	return nil
}
func (s *Packet) Decode(buf []byte) ([]byte, error) {
	var offset int
	err := s.DecodeSlice(buf, &offset)
	if err != nil {
		return nil, err
	}
	return buf[offset:], nil
}
func (s *Packet) DecodeExact(buf []byte) error {
	remain, err := s.Decode(buf)
	if err != nil {
		return err
	}
	if len(remain) != 0 {
		return fmt.Errorf("expect no remaining bytes but got %d bytes", len(remain))
	}
	return nil
}
